`include "B_CPM5N_defines.vh"

reg [`CPM5N_DATA_SZ-1:0] ATTR [0:`CPM5N_ADDR_N-1];
reg [`CPM5N__CDX_MODE_SZ:1] CDX_MODE_REG = CDX_MODE;
reg [`CPM5N__CPM5N_MPIOBOT_MODE_SZ:1] CPM5N_MPIOBOT_MODE_REG = CPM5N_MPIOBOT_MODE;
reg [`CPM5N__CPM5N_MPIOTOP_MODE_SZ:1] CPM5N_MPIOTOP_MODE_REG = CPM5N_MPIOTOP_MODE;
reg [`CPM5N__DPU_MODE_SZ:1] DPU_MODE_REG = DPU_MODE;
reg [`CPM5N__LINK_SPEED_0_SZ:1] LINK_SPEED_0_REG = LINK_SPEED_0;
reg [`CPM5N__LINK_SPEED_1_SZ:1] LINK_SPEED_1_REG = LINK_SPEED_1;
reg [`CPM5N__LINK_SPEED_2_SZ:1] LINK_SPEED_2_REG = LINK_SPEED_2;
reg [`CPM5N__LINK_SPEED_3_SZ:1] LINK_SPEED_3_REG = LINK_SPEED_3;
reg [`CPM5N__LINK_WIDTH_0_SZ-1:0] LINK_WIDTH_0_REG = LINK_WIDTH_0;
reg [`CPM5N__LINK_WIDTH_1_SZ-1:0] LINK_WIDTH_1_REG = LINK_WIDTH_1;
reg [`CPM5N__LINK_WIDTH_2_SZ-1:0] LINK_WIDTH_2_REG = LINK_WIDTH_2;
reg [`CPM5N__LINK_WIDTH_3_SZ-1:0] LINK_WIDTH_3_REG = LINK_WIDTH_3;
reg [`CPM5N__PACKET_SIZE_SZ-1:0] PACKET_SIZE_REG = PACKET_SIZE;
reg [`CPM5N__PCIE_MODE_A0_SZ:1] PCIE_MODE_A0_REG = PCIE_MODE_A0;
reg [`CPM5N__PCIE_MODE_A1_SZ:1] PCIE_MODE_A1_REG = PCIE_MODE_A1;
reg [`CPM5N__PCIE_MODE_A2_SZ:1] PCIE_MODE_A2_REG = PCIE_MODE_A2;
reg [`CPM5N__PCIE_MODE_A3_SZ:1] PCIE_MODE_A3_REG = PCIE_MODE_A3;
reg [`CPM5N__SIM_CPM_CDO_FILE_NAME_SZ:1] SIM_CPM_CDO_FILE_NAME_REG = SIM_CPM_CDO_FILE_NAME;
reg [`CPM5N__SIM_CPM_CDO_MODE_SZ-1:0] SIM_CPM_CDO_MODE_REG = SIM_CPM_CDO_MODE;

initial begin
  ATTR[`CPM5N__CDX_MODE] = CDX_MODE;
  ATTR[`CPM5N__CPM5N_MPIOBOT_MODE] = CPM5N_MPIOBOT_MODE;
  ATTR[`CPM5N__CPM5N_MPIOTOP_MODE] = CPM5N_MPIOTOP_MODE;
  ATTR[`CPM5N__DPU_MODE] = DPU_MODE;
  ATTR[`CPM5N__LINK_SPEED_0] = LINK_SPEED_0;
  ATTR[`CPM5N__LINK_SPEED_1] = LINK_SPEED_1;
  ATTR[`CPM5N__LINK_SPEED_2] = LINK_SPEED_2;
  ATTR[`CPM5N__LINK_SPEED_3] = LINK_SPEED_3;
  ATTR[`CPM5N__LINK_WIDTH_0] = LINK_WIDTH_0;
  ATTR[`CPM5N__LINK_WIDTH_1] = LINK_WIDTH_1;
  ATTR[`CPM5N__LINK_WIDTH_2] = LINK_WIDTH_2;
  ATTR[`CPM5N__LINK_WIDTH_3] = LINK_WIDTH_3;
  ATTR[`CPM5N__PACKET_SIZE] = PACKET_SIZE;
  ATTR[`CPM5N__PCIE_MODE_A0] = PCIE_MODE_A0;
  ATTR[`CPM5N__PCIE_MODE_A1] = PCIE_MODE_A1;
  ATTR[`CPM5N__PCIE_MODE_A2] = PCIE_MODE_A2;
  ATTR[`CPM5N__PCIE_MODE_A3] = PCIE_MODE_A3;
  ATTR[`CPM5N__SIM_CPM_CDO_FILE_NAME] = SIM_CPM_CDO_FILE_NAME;
  ATTR[`CPM5N__SIM_CPM_CDO_MODE] = SIM_CPM_CDO_MODE;
end

always @(trig_attr) begin
  CDX_MODE_REG = ATTR[`CPM5N__CDX_MODE];
  CPM5N_MPIOBOT_MODE_REG = ATTR[`CPM5N__CPM5N_MPIOBOT_MODE];
  CPM5N_MPIOTOP_MODE_REG = ATTR[`CPM5N__CPM5N_MPIOTOP_MODE];
  DPU_MODE_REG = ATTR[`CPM5N__DPU_MODE];
  LINK_SPEED_0_REG = ATTR[`CPM5N__LINK_SPEED_0];
  LINK_SPEED_1_REG = ATTR[`CPM5N__LINK_SPEED_1];
  LINK_SPEED_2_REG = ATTR[`CPM5N__LINK_SPEED_2];
  LINK_SPEED_3_REG = ATTR[`CPM5N__LINK_SPEED_3];
  LINK_WIDTH_0_REG = ATTR[`CPM5N__LINK_WIDTH_0];
  LINK_WIDTH_1_REG = ATTR[`CPM5N__LINK_WIDTH_1];
  LINK_WIDTH_2_REG = ATTR[`CPM5N__LINK_WIDTH_2];
  LINK_WIDTH_3_REG = ATTR[`CPM5N__LINK_WIDTH_3];
  PACKET_SIZE_REG = ATTR[`CPM5N__PACKET_SIZE];
  PCIE_MODE_A0_REG = ATTR[`CPM5N__PCIE_MODE_A0];
  PCIE_MODE_A1_REG = ATTR[`CPM5N__PCIE_MODE_A1];
  PCIE_MODE_A2_REG = ATTR[`CPM5N__PCIE_MODE_A2];
  PCIE_MODE_A3_REG = ATTR[`CPM5N__PCIE_MODE_A3];
  SIM_CPM_CDO_FILE_NAME_REG = ATTR[`CPM5N__SIM_CPM_CDO_FILE_NAME];
  SIM_CPM_CDO_MODE_REG = ATTR[`CPM5N__SIM_CPM_CDO_MODE];
end

// procedures to override, read attribute values

task write_attr;
  input  [`CPM5N_ADDR_SZ-1:0] addr;
  input  [`CPM5N_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`CPM5N_DATA_SZ-1:0] read_attr;
  input  [`CPM5N_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
