`include "B_CPM6_defines.vh"

reg [`CPM6_DATA_SZ-1:0] ATTR [0:`CPM6_ADDR_N-1];
reg [`CPM6__BOT_CHIPPIPE_MODE_SZ:1] BOT_CHIPPIPE_MODE_REG = BOT_CHIPPIPE_MODE;
reg [`CPM6__BOT_PL_MUX_MODE_SZ:1] BOT_PL_MUX_MODE_REG = BOT_PL_MUX_MODE;
reg [`CPM6__CONTROLLER_0_CXL_MODE_SZ:1] CONTROLLER_0_CXL_MODE_REG = CONTROLLER_0_CXL_MODE;
reg [`CPM6__CONTROLLER_0_IDE_MODE_SZ:1] CONTROLLER_0_IDE_MODE_REG = CONTROLLER_0_IDE_MODE;
reg [`CPM6__CONTROLLER_0_LINK_SPEED_SZ:1] CONTROLLER_0_LINK_SPEED_REG = CONTROLLER_0_LINK_SPEED;
reg [`CPM6__CONTROLLER_0_LINK_WIDTH_SZ:1] CONTROLLER_0_LINK_WIDTH_REG = CONTROLLER_0_LINK_WIDTH;
reg [`CPM6__CONTROLLER_0_TLP_BYPASS_MODE_SZ:1] CONTROLLER_0_TLP_BYPASS_MODE_REG = CONTROLLER_0_TLP_BYPASS_MODE;
reg [`CPM6__CONTROLLER_1_CXL_MODE_SZ:1] CONTROLLER_1_CXL_MODE_REG = CONTROLLER_1_CXL_MODE;
reg [`CPM6__CONTROLLER_1_IDE_MODE_SZ:1] CONTROLLER_1_IDE_MODE_REG = CONTROLLER_1_IDE_MODE;
reg [`CPM6__CONTROLLER_1_LINK_SPEED_SZ:1] CONTROLLER_1_LINK_SPEED_REG = CONTROLLER_1_LINK_SPEED;
reg [`CPM6__CONTROLLER_1_LINK_WIDTH_SZ:1] CONTROLLER_1_LINK_WIDTH_REG = CONTROLLER_1_LINK_WIDTH;
reg [`CPM6__CONTROLLER_1_TLP_BYPASS_MODE_SZ:1] CONTROLLER_1_TLP_BYPASS_MODE_REG = CONTROLLER_1_TLP_BYPASS_MODE;
reg [`CPM6__SIM_CPM_CDO_FILE_NAME_SZ:1] SIM_CPM_CDO_FILE_NAME_REG = SIM_CPM_CDO_FILE_NAME;
reg [`CPM6__SIM_CPM_CDO_MODE_SZ-1:0] SIM_CPM_CDO_MODE_REG = SIM_CPM_CDO_MODE;
reg [`CPM6__TOP_CHIPPIPE_MODE_SZ:1] TOP_CHIPPIPE_MODE_REG = TOP_CHIPPIPE_MODE;
reg [`CPM6__TOP_PL_MUX_MODE_SZ:1] TOP_PL_MUX_MODE_REG = TOP_PL_MUX_MODE;

initial begin
  ATTR[`CPM6__BOT_CHIPPIPE_MODE] = BOT_CHIPPIPE_MODE;
  ATTR[`CPM6__BOT_PL_MUX_MODE] = BOT_PL_MUX_MODE;
  ATTR[`CPM6__CONTROLLER_0_CXL_MODE] = CONTROLLER_0_CXL_MODE;
  ATTR[`CPM6__CONTROLLER_0_IDE_MODE] = CONTROLLER_0_IDE_MODE;
  ATTR[`CPM6__CONTROLLER_0_LINK_SPEED] = CONTROLLER_0_LINK_SPEED;
  ATTR[`CPM6__CONTROLLER_0_LINK_WIDTH] = CONTROLLER_0_LINK_WIDTH;
  ATTR[`CPM6__CONTROLLER_0_TLP_BYPASS_MODE] = CONTROLLER_0_TLP_BYPASS_MODE;
  ATTR[`CPM6__CONTROLLER_1_CXL_MODE] = CONTROLLER_1_CXL_MODE;
  ATTR[`CPM6__CONTROLLER_1_IDE_MODE] = CONTROLLER_1_IDE_MODE;
  ATTR[`CPM6__CONTROLLER_1_LINK_SPEED] = CONTROLLER_1_LINK_SPEED;
  ATTR[`CPM6__CONTROLLER_1_LINK_WIDTH] = CONTROLLER_1_LINK_WIDTH;
  ATTR[`CPM6__CONTROLLER_1_TLP_BYPASS_MODE] = CONTROLLER_1_TLP_BYPASS_MODE;
  ATTR[`CPM6__SIM_CPM_CDO_FILE_NAME] = SIM_CPM_CDO_FILE_NAME;
  ATTR[`CPM6__SIM_CPM_CDO_MODE] = SIM_CPM_CDO_MODE;
  ATTR[`CPM6__TOP_CHIPPIPE_MODE] = TOP_CHIPPIPE_MODE;
  ATTR[`CPM6__TOP_PL_MUX_MODE] = TOP_PL_MUX_MODE;
end

always @(trig_attr) begin
  BOT_CHIPPIPE_MODE_REG = ATTR[`CPM6__BOT_CHIPPIPE_MODE];
  BOT_PL_MUX_MODE_REG = ATTR[`CPM6__BOT_PL_MUX_MODE];
  CONTROLLER_0_CXL_MODE_REG = ATTR[`CPM6__CONTROLLER_0_CXL_MODE];
  CONTROLLER_0_IDE_MODE_REG = ATTR[`CPM6__CONTROLLER_0_IDE_MODE];
  CONTROLLER_0_LINK_SPEED_REG = ATTR[`CPM6__CONTROLLER_0_LINK_SPEED];
  CONTROLLER_0_LINK_WIDTH_REG = ATTR[`CPM6__CONTROLLER_0_LINK_WIDTH];
  CONTROLLER_0_TLP_BYPASS_MODE_REG = ATTR[`CPM6__CONTROLLER_0_TLP_BYPASS_MODE];
  CONTROLLER_1_CXL_MODE_REG = ATTR[`CPM6__CONTROLLER_1_CXL_MODE];
  CONTROLLER_1_IDE_MODE_REG = ATTR[`CPM6__CONTROLLER_1_IDE_MODE];
  CONTROLLER_1_LINK_SPEED_REG = ATTR[`CPM6__CONTROLLER_1_LINK_SPEED];
  CONTROLLER_1_LINK_WIDTH_REG = ATTR[`CPM6__CONTROLLER_1_LINK_WIDTH];
  CONTROLLER_1_TLP_BYPASS_MODE_REG = ATTR[`CPM6__CONTROLLER_1_TLP_BYPASS_MODE];
  SIM_CPM_CDO_FILE_NAME_REG = ATTR[`CPM6__SIM_CPM_CDO_FILE_NAME];
  SIM_CPM_CDO_MODE_REG = ATTR[`CPM6__SIM_CPM_CDO_MODE];
  TOP_CHIPPIPE_MODE_REG = ATTR[`CPM6__TOP_CHIPPIPE_MODE];
  TOP_PL_MUX_MODE_REG = ATTR[`CPM6__TOP_PL_MUX_MODE];
end

// procedures to override, read attribute values

task write_attr;
  input  [`CPM6_ADDR_SZ-1:0] addr;
  input  [`CPM6_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`CPM6_DATA_SZ-1:0] read_attr;
  input  [`CPM6_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
