`include "B_DFE_CHANNELIZER_defines.vh"

reg [`DFE_CHANNELIZER_DATA_SZ-1:0] ATTR [0:`DFE_CHANNELIZER_ADDR_N-1];
real ACTIVE_DUTYCYCLE_REG = ACTIVE_DUTYCYCLE;
reg [`DFE_CHANNELIZER__CH0_NUM_TAPS_SZ:1] CH0_NUM_TAPS_REG = CH0_NUM_TAPS;
reg [`DFE_CHANNELIZER__CH1_NUM_TAPS_SZ:1] CH1_NUM_TAPS_REG = CH1_NUM_TAPS;
reg [`DFE_CHANNELIZER__CH2_NUM_TAPS_SZ:1] CH2_NUM_TAPS_REG = CH2_NUM_TAPS;
reg [`DFE_CHANNELIZER__CH3_NUM_TAPS_SZ:1] CH3_NUM_TAPS_REG = CH3_NUM_TAPS;
reg [`DFE_CHANNELIZER__FIR_COEFF_TYPE_SZ:1] FIR_COEFF_TYPE_REG = FIR_COEFF_TYPE;
reg [`DFE_CHANNELIZER__MAX_FIR_LENGTH_SZ:1] MAX_FIR_LENGTH_REG = MAX_FIR_LENGTH;
reg [`DFE_CHANNELIZER__MODE_SZ:1] MODE_REG = MODE;
reg [`DFE_CHANNELIZER__NUMBER_INSTANCE_SZ-1:0] NUMBER_INSTANCE_REG = NUMBER_INSTANCE;
reg [`DFE_CHANNELIZER__SAMPLE_RATE_SZ:1] SAMPLE_RATE_REG = SAMPLE_RATE;
reg [`DFE_CHANNELIZER__SPARE_SZ-1:0] SPARE_REG = SPARE;
real TOGGLE_RATE_REG = TOGGLE_RATE;

initial begin
  ATTR[`DFE_CHANNELIZER__ACTIVE_DUTYCYCLE] = $realtobits(ACTIVE_DUTYCYCLE);
  ATTR[`DFE_CHANNELIZER__CH0_NUM_TAPS] = CH0_NUM_TAPS;
  ATTR[`DFE_CHANNELIZER__CH1_NUM_TAPS] = CH1_NUM_TAPS;
  ATTR[`DFE_CHANNELIZER__CH2_NUM_TAPS] = CH2_NUM_TAPS;
  ATTR[`DFE_CHANNELIZER__CH3_NUM_TAPS] = CH3_NUM_TAPS;
  ATTR[`DFE_CHANNELIZER__FIR_COEFF_TYPE] = FIR_COEFF_TYPE;
  ATTR[`DFE_CHANNELIZER__MAX_FIR_LENGTH] = MAX_FIR_LENGTH;
  ATTR[`DFE_CHANNELIZER__MODE] = MODE;
  ATTR[`DFE_CHANNELIZER__NUMBER_INSTANCE] = NUMBER_INSTANCE;
  ATTR[`DFE_CHANNELIZER__SAMPLE_RATE] = SAMPLE_RATE;
  ATTR[`DFE_CHANNELIZER__SPARE] = SPARE;
  ATTR[`DFE_CHANNELIZER__TOGGLE_RATE] = $realtobits(TOGGLE_RATE);
end

always @(trig_attr) begin
  ACTIVE_DUTYCYCLE_REG = $bitstoreal(ATTR[`DFE_CHANNELIZER__ACTIVE_DUTYCYCLE]);
  CH0_NUM_TAPS_REG = ATTR[`DFE_CHANNELIZER__CH0_NUM_TAPS];
  CH1_NUM_TAPS_REG = ATTR[`DFE_CHANNELIZER__CH1_NUM_TAPS];
  CH2_NUM_TAPS_REG = ATTR[`DFE_CHANNELIZER__CH2_NUM_TAPS];
  CH3_NUM_TAPS_REG = ATTR[`DFE_CHANNELIZER__CH3_NUM_TAPS];
  FIR_COEFF_TYPE_REG = ATTR[`DFE_CHANNELIZER__FIR_COEFF_TYPE];
  MAX_FIR_LENGTH_REG = ATTR[`DFE_CHANNELIZER__MAX_FIR_LENGTH];
  MODE_REG = ATTR[`DFE_CHANNELIZER__MODE];
  NUMBER_INSTANCE_REG = ATTR[`DFE_CHANNELIZER__NUMBER_INSTANCE];
  SAMPLE_RATE_REG = ATTR[`DFE_CHANNELIZER__SAMPLE_RATE];
  SPARE_REG = ATTR[`DFE_CHANNELIZER__SPARE];
  TOGGLE_RATE_REG = $bitstoreal(ATTR[`DFE_CHANNELIZER__TOGGLE_RATE]);
end

// procedures to override, read attribute values

task write_attr;
  input  [`DFE_CHANNELIZER_ADDR_SZ-1:0] addr;
  input  [`DFE_CHANNELIZER_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`DFE_CHANNELIZER_DATA_SZ-1:0] read_attr;
  input  [`DFE_CHANNELIZER_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
