`include "B_DSP58_defines.vh"

reg [`DSP58_DATA_SZ-1:0] ATTR [0:`DSP58_ADDR_N-1];
reg [`DSP58__ACASCREG_SZ-1:0] ACASCREG_REG = ACASCREG;
reg [`DSP58__ADREG_SZ-1:0] ADREG_REG = ADREG;
reg [`DSP58__ALUMODEREG_SZ-1:0] ALUMODEREG_REG = ALUMODEREG;
reg [`DSP58__AMULTSEL_SZ:1] AMULTSEL_REG = AMULTSEL;
reg [`DSP58__AREG_SZ-1:0] AREG_REG = AREG;
reg [`DSP58__AUTORESET_PATDET_SZ:1] AUTORESET_PATDET_REG = AUTORESET_PATDET;
reg [`DSP58__AUTORESET_PRIORITY_SZ:1] AUTORESET_PRIORITY_REG = AUTORESET_PRIORITY;
reg [`DSP58__A_INPUT_SZ:1] A_INPUT_REG = A_INPUT;
reg [`DSP58__BCASCREG_SZ-1:0] BCASCREG_REG = BCASCREG;
reg [`DSP58__BMULTSEL_SZ:1] BMULTSEL_REG = BMULTSEL;
reg [`DSP58__BREG_SZ-1:0] BREG_REG = BREG;
reg [`DSP58__B_INPUT_SZ:1] B_INPUT_REG = B_INPUT;
reg [`DSP58__CARRYINREG_SZ-1:0] CARRYINREG_REG = CARRYINREG;
reg [`DSP58__CARRYINSELREG_SZ-1:0] CARRYINSELREG_REG = CARRYINSELREG;
reg [`DSP58__CREG_SZ-1:0] CREG_REG = CREG;
reg [`DSP58__DREG_SZ-1:0] DREG_REG = DREG;
reg [`DSP58__DSP_MODE_SZ:1] DSP_MODE_REG = DSP_MODE;
reg [`DSP58__INMODEREG_SZ-1:0] INMODEREG_REG = INMODEREG;
reg [`DSP58__IS_ALUMODE_INVERTED_SZ-1:0] IS_ALUMODE_INVERTED_REG = IS_ALUMODE_INVERTED;
reg IS_ASYNC_RST_INVERTED_REG = IS_ASYNC_RST_INVERTED;
reg IS_CARRYIN_INVERTED_REG = IS_CARRYIN_INVERTED;
reg IS_CLK_INVERTED_REG = IS_CLK_INVERTED;
reg [`DSP58__IS_INMODE_INVERTED_SZ-1:0] IS_INMODE_INVERTED_REG = IS_INMODE_INVERTED;
reg [`DSP58__IS_NEGATE_INVERTED_SZ-1:0] IS_NEGATE_INVERTED_REG = IS_NEGATE_INVERTED;
reg [`DSP58__IS_OPMODE_INVERTED_SZ-1:0] IS_OPMODE_INVERTED_REG = IS_OPMODE_INVERTED;
reg IS_RSTALLCARRYIN_INVERTED_REG = IS_RSTALLCARRYIN_INVERTED;
reg IS_RSTALUMODE_INVERTED_REG = IS_RSTALUMODE_INVERTED;
reg IS_RSTA_INVERTED_REG = IS_RSTA_INVERTED;
reg IS_RSTB_INVERTED_REG = IS_RSTB_INVERTED;
reg IS_RSTCTRL_INVERTED_REG = IS_RSTCTRL_INVERTED;
reg IS_RSTC_INVERTED_REG = IS_RSTC_INVERTED;
reg IS_RSTD_INVERTED_REG = IS_RSTD_INVERTED;
reg IS_RSTINMODE_INVERTED_REG = IS_RSTINMODE_INVERTED;
reg IS_RSTM_INVERTED_REG = IS_RSTM_INVERTED;
reg IS_RSTP_INVERTED_REG = IS_RSTP_INVERTED;
reg [`DSP58__MASK_SZ-1:0] MASK_REG = MASK;
reg [`DSP58__MREG_SZ-1:0] MREG_REG = MREG;
reg [`DSP58__OPMODEREG_SZ-1:0] OPMODEREG_REG = OPMODEREG;
reg [`DSP58__PATTERN_SZ-1:0] PATTERN_REG = PATTERN;
reg [`DSP58__PREADDINSEL_SZ:1] PREADDINSEL_REG = PREADDINSEL;
reg [`DSP58__PREG_SZ-1:0] PREG_REG = PREG;
reg [`DSP58__RESET_MODE_SZ:1] RESET_MODE_REG = RESET_MODE;
reg [`DSP58__RND_SZ-1:0] RND_REG = RND;
reg [`DSP58__SEL_MASK_SZ:1] SEL_MASK_REG = SEL_MASK;
reg [`DSP58__SEL_PATTERN_SZ:1] SEL_PATTERN_REG = SEL_PATTERN;
reg [`DSP58__USE_MULT_SZ:1] USE_MULT_REG = USE_MULT;
reg [`DSP58__USE_PATTERN_DETECT_SZ:1] USE_PATTERN_DETECT_REG = USE_PATTERN_DETECT;
reg [`DSP58__USE_SIMD_SZ:1] USE_SIMD_REG = USE_SIMD;
reg [`DSP58__USE_WIDEXOR_SZ:1] USE_WIDEXOR_REG = USE_WIDEXOR;
reg [`DSP58__XORSIMD_SZ:1] XORSIMD_REG = XORSIMD;

initial begin
  ATTR[`DSP58__ACASCREG] = ACASCREG;
  ATTR[`DSP58__ADREG] = ADREG;
  ATTR[`DSP58__ALUMODEREG] = ALUMODEREG;
  ATTR[`DSP58__AMULTSEL] = AMULTSEL;
  ATTR[`DSP58__AREG] = AREG;
  ATTR[`DSP58__AUTORESET_PATDET] = AUTORESET_PATDET;
  ATTR[`DSP58__AUTORESET_PRIORITY] = AUTORESET_PRIORITY;
  ATTR[`DSP58__A_INPUT] = A_INPUT;
  ATTR[`DSP58__BCASCREG] = BCASCREG;
  ATTR[`DSP58__BMULTSEL] = BMULTSEL;
  ATTR[`DSP58__BREG] = BREG;
  ATTR[`DSP58__B_INPUT] = B_INPUT;
  ATTR[`DSP58__CARRYINREG] = CARRYINREG;
  ATTR[`DSP58__CARRYINSELREG] = CARRYINSELREG;
  ATTR[`DSP58__CREG] = CREG;
  ATTR[`DSP58__DREG] = DREG;
  ATTR[`DSP58__DSP_MODE] = DSP_MODE;
  ATTR[`DSP58__INMODEREG] = INMODEREG;
  ATTR[`DSP58__IS_ALUMODE_INVERTED] = IS_ALUMODE_INVERTED;
  ATTR[`DSP58__IS_ASYNC_RST_INVERTED] = IS_ASYNC_RST_INVERTED;
  ATTR[`DSP58__IS_CARRYIN_INVERTED] = IS_CARRYIN_INVERTED;
  ATTR[`DSP58__IS_CLK_INVERTED] = IS_CLK_INVERTED;
  ATTR[`DSP58__IS_INMODE_INVERTED] = IS_INMODE_INVERTED;
  ATTR[`DSP58__IS_NEGATE_INVERTED] = IS_NEGATE_INVERTED;
  ATTR[`DSP58__IS_OPMODE_INVERTED] = IS_OPMODE_INVERTED;
  ATTR[`DSP58__IS_RSTALLCARRYIN_INVERTED] = IS_RSTALLCARRYIN_INVERTED;
  ATTR[`DSP58__IS_RSTALUMODE_INVERTED] = IS_RSTALUMODE_INVERTED;
  ATTR[`DSP58__IS_RSTA_INVERTED] = IS_RSTA_INVERTED;
  ATTR[`DSP58__IS_RSTB_INVERTED] = IS_RSTB_INVERTED;
  ATTR[`DSP58__IS_RSTCTRL_INVERTED] = IS_RSTCTRL_INVERTED;
  ATTR[`DSP58__IS_RSTC_INVERTED] = IS_RSTC_INVERTED;
  ATTR[`DSP58__IS_RSTD_INVERTED] = IS_RSTD_INVERTED;
  ATTR[`DSP58__IS_RSTINMODE_INVERTED] = IS_RSTINMODE_INVERTED;
  ATTR[`DSP58__IS_RSTM_INVERTED] = IS_RSTM_INVERTED;
  ATTR[`DSP58__IS_RSTP_INVERTED] = IS_RSTP_INVERTED;
  ATTR[`DSP58__MASK] = MASK;
  ATTR[`DSP58__MREG] = MREG;
  ATTR[`DSP58__OPMODEREG] = OPMODEREG;
  ATTR[`DSP58__PATTERN] = PATTERN;
  ATTR[`DSP58__PREADDINSEL] = PREADDINSEL;
  ATTR[`DSP58__PREG] = PREG;
  ATTR[`DSP58__RESET_MODE] = RESET_MODE;
  ATTR[`DSP58__RND] = RND;
  ATTR[`DSP58__SEL_MASK] = SEL_MASK;
  ATTR[`DSP58__SEL_PATTERN] = SEL_PATTERN;
  ATTR[`DSP58__USE_MULT] = USE_MULT;
  ATTR[`DSP58__USE_PATTERN_DETECT] = USE_PATTERN_DETECT;
  ATTR[`DSP58__USE_SIMD] = USE_SIMD;
  ATTR[`DSP58__USE_WIDEXOR] = USE_WIDEXOR;
  ATTR[`DSP58__XORSIMD] = XORSIMD;
end

always @(trig_attr) begin
  ACASCREG_REG = ATTR[`DSP58__ACASCREG];
  ADREG_REG = ATTR[`DSP58__ADREG];
  ALUMODEREG_REG = ATTR[`DSP58__ALUMODEREG];
  AMULTSEL_REG = ATTR[`DSP58__AMULTSEL];
  AREG_REG = ATTR[`DSP58__AREG];
  AUTORESET_PATDET_REG = ATTR[`DSP58__AUTORESET_PATDET];
  AUTORESET_PRIORITY_REG = ATTR[`DSP58__AUTORESET_PRIORITY];
  A_INPUT_REG = ATTR[`DSP58__A_INPUT];
  BCASCREG_REG = ATTR[`DSP58__BCASCREG];
  BMULTSEL_REG = ATTR[`DSP58__BMULTSEL];
  BREG_REG = ATTR[`DSP58__BREG];
  B_INPUT_REG = ATTR[`DSP58__B_INPUT];
  CARRYINREG_REG = ATTR[`DSP58__CARRYINREG];
  CARRYINSELREG_REG = ATTR[`DSP58__CARRYINSELREG];
  CREG_REG = ATTR[`DSP58__CREG];
  DREG_REG = ATTR[`DSP58__DREG];
  DSP_MODE_REG = ATTR[`DSP58__DSP_MODE];
  INMODEREG_REG = ATTR[`DSP58__INMODEREG];
  IS_ALUMODE_INVERTED_REG = ATTR[`DSP58__IS_ALUMODE_INVERTED];
  IS_ASYNC_RST_INVERTED_REG = ATTR[`DSP58__IS_ASYNC_RST_INVERTED];
  IS_CARRYIN_INVERTED_REG = ATTR[`DSP58__IS_CARRYIN_INVERTED];
  IS_CLK_INVERTED_REG = ATTR[`DSP58__IS_CLK_INVERTED];
  IS_INMODE_INVERTED_REG = ATTR[`DSP58__IS_INMODE_INVERTED];
  IS_NEGATE_INVERTED_REG = ATTR[`DSP58__IS_NEGATE_INVERTED];
  IS_OPMODE_INVERTED_REG = ATTR[`DSP58__IS_OPMODE_INVERTED];
  IS_RSTALLCARRYIN_INVERTED_REG = ATTR[`DSP58__IS_RSTALLCARRYIN_INVERTED];
  IS_RSTALUMODE_INVERTED_REG = ATTR[`DSP58__IS_RSTALUMODE_INVERTED];
  IS_RSTA_INVERTED_REG = ATTR[`DSP58__IS_RSTA_INVERTED];
  IS_RSTB_INVERTED_REG = ATTR[`DSP58__IS_RSTB_INVERTED];
  IS_RSTCTRL_INVERTED_REG = ATTR[`DSP58__IS_RSTCTRL_INVERTED];
  IS_RSTC_INVERTED_REG = ATTR[`DSP58__IS_RSTC_INVERTED];
  IS_RSTD_INVERTED_REG = ATTR[`DSP58__IS_RSTD_INVERTED];
  IS_RSTINMODE_INVERTED_REG = ATTR[`DSP58__IS_RSTINMODE_INVERTED];
  IS_RSTM_INVERTED_REG = ATTR[`DSP58__IS_RSTM_INVERTED];
  IS_RSTP_INVERTED_REG = ATTR[`DSP58__IS_RSTP_INVERTED];
  MASK_REG = ATTR[`DSP58__MASK];
  MREG_REG = ATTR[`DSP58__MREG];
  OPMODEREG_REG = ATTR[`DSP58__OPMODEREG];
  PATTERN_REG = ATTR[`DSP58__PATTERN];
  PREADDINSEL_REG = ATTR[`DSP58__PREADDINSEL];
  PREG_REG = ATTR[`DSP58__PREG];
  RESET_MODE_REG = ATTR[`DSP58__RESET_MODE];
  RND_REG = ATTR[`DSP58__RND];
  SEL_MASK_REG = ATTR[`DSP58__SEL_MASK];
  SEL_PATTERN_REG = ATTR[`DSP58__SEL_PATTERN];
  USE_MULT_REG = ATTR[`DSP58__USE_MULT];
  USE_PATTERN_DETECT_REG = ATTR[`DSP58__USE_PATTERN_DETECT];
  USE_SIMD_REG = ATTR[`DSP58__USE_SIMD];
  USE_WIDEXOR_REG = ATTR[`DSP58__USE_WIDEXOR];
  XORSIMD_REG = ATTR[`DSP58__XORSIMD];
end

// procedures to override, read attribute values

task write_attr;
  input  [`DSP58_ADDR_SZ-1:0] addr;
  input  [`DSP58_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`DSP58_DATA_SZ-1:0] read_attr;
  input  [`DSP58_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
