`include "B_GTM2_QUAD_defines.vh"

reg [`GTM2_QUAD_DATA_SZ-1:0] ATTR [0:`GTM2_QUAD_ADDR_N-1];
real CH0_RXOUTCLK_FREQ_REG = CH0_RXOUTCLK_FREQ;
real CH0_RXOUTCLK_REF_FREQ_REG = CH0_RXOUTCLK_REF_FREQ;
reg [`GTM2_QUAD__CH0_RXOUTCLK_REF_SOURCE_SZ:1] CH0_RXOUTCLK_REF_SOURCE_REG = CH0_RXOUTCLK_REF_SOURCE;
real CH0_TXOUTCLK_FREQ_REG = CH0_TXOUTCLK_FREQ;
real CH0_TXOUTCLK_REF_FREQ_REG = CH0_TXOUTCLK_REF_FREQ;
reg [`GTM2_QUAD__CH0_TXOUTCLK_REF_SOURCE_SZ:1] CH0_TXOUTCLK_REF_SOURCE_REG = CH0_TXOUTCLK_REF_SOURCE;
real CH1_RXOUTCLK_FREQ_REG = CH1_RXOUTCLK_FREQ;
real CH1_RXOUTCLK_REF_FREQ_REG = CH1_RXOUTCLK_REF_FREQ;
reg [`GTM2_QUAD__CH1_RXOUTCLK_REF_SOURCE_SZ:1] CH1_RXOUTCLK_REF_SOURCE_REG = CH1_RXOUTCLK_REF_SOURCE;
real CH1_TXOUTCLK_FREQ_REG = CH1_TXOUTCLK_FREQ;
real CH1_TXOUTCLK_REF_FREQ_REG = CH1_TXOUTCLK_REF_FREQ;
reg [`GTM2_QUAD__CH1_TXOUTCLK_REF_SOURCE_SZ:1] CH1_TXOUTCLK_REF_SOURCE_REG = CH1_TXOUTCLK_REF_SOURCE;
real CH2_RXOUTCLK_FREQ_REG = CH2_RXOUTCLK_FREQ;
real CH2_RXOUTCLK_REF_FREQ_REG = CH2_RXOUTCLK_REF_FREQ;
reg [`GTM2_QUAD__CH2_RXOUTCLK_REF_SOURCE_SZ:1] CH2_RXOUTCLK_REF_SOURCE_REG = CH2_RXOUTCLK_REF_SOURCE;
real CH2_TXOUTCLK_FREQ_REG = CH2_TXOUTCLK_FREQ;
real CH2_TXOUTCLK_REF_FREQ_REG = CH2_TXOUTCLK_REF_FREQ;
reg [`GTM2_QUAD__CH2_TXOUTCLK_REF_SOURCE_SZ:1] CH2_TXOUTCLK_REF_SOURCE_REG = CH2_TXOUTCLK_REF_SOURCE;
real CH3_RXOUTCLK_FREQ_REG = CH3_RXOUTCLK_FREQ;
real CH3_RXOUTCLK_REF_FREQ_REG = CH3_RXOUTCLK_REF_FREQ;
reg [`GTM2_QUAD__CH3_RXOUTCLK_REF_SOURCE_SZ:1] CH3_RXOUTCLK_REF_SOURCE_REG = CH3_RXOUTCLK_REF_SOURCE;
real CH3_TXOUTCLK_FREQ_REG = CH3_TXOUTCLK_FREQ;
real CH3_TXOUTCLK_REF_FREQ_REG = CH3_TXOUTCLK_REF_FREQ;
reg [`GTM2_QUAD__CH3_TXOUTCLK_REF_SOURCE_SZ:1] CH3_TXOUTCLK_REF_SOURCE_REG = CH3_TXOUTCLK_REF_SOURCE;
reg [`GTM2_QUAD__CHANNEL_CONNECTIVITY_SZ:1] CHANNEL_CONNECTIVITY_REG = CHANNEL_CONNECTIVITY;
reg [`GTM2_QUAD__MEMORY_INIT_FILE_SZ:1] MEMORY_INIT_FILE_REG = MEMORY_INIT_FILE;
reg [`GTM2_QUAD__STAT_NPI_REG_LIST_SZ:1] STAT_NPI_REG_LIST_REG = STAT_NPI_REG_LIST;

initial begin
  ATTR[`GTM2_QUAD__CH0_RXOUTCLK_FREQ] = $realtobits(CH0_RXOUTCLK_FREQ);
  ATTR[`GTM2_QUAD__CH0_RXOUTCLK_REF_FREQ] = $realtobits(CH0_RXOUTCLK_REF_FREQ);
  ATTR[`GTM2_QUAD__CH0_RXOUTCLK_REF_SOURCE] = CH0_RXOUTCLK_REF_SOURCE;
  ATTR[`GTM2_QUAD__CH0_TXOUTCLK_FREQ] = $realtobits(CH0_TXOUTCLK_FREQ);
  ATTR[`GTM2_QUAD__CH0_TXOUTCLK_REF_FREQ] = $realtobits(CH0_TXOUTCLK_REF_FREQ);
  ATTR[`GTM2_QUAD__CH0_TXOUTCLK_REF_SOURCE] = CH0_TXOUTCLK_REF_SOURCE;
  ATTR[`GTM2_QUAD__CH1_RXOUTCLK_FREQ] = $realtobits(CH1_RXOUTCLK_FREQ);
  ATTR[`GTM2_QUAD__CH1_RXOUTCLK_REF_FREQ] = $realtobits(CH1_RXOUTCLK_REF_FREQ);
  ATTR[`GTM2_QUAD__CH1_RXOUTCLK_REF_SOURCE] = CH1_RXOUTCLK_REF_SOURCE;
  ATTR[`GTM2_QUAD__CH1_TXOUTCLK_FREQ] = $realtobits(CH1_TXOUTCLK_FREQ);
  ATTR[`GTM2_QUAD__CH1_TXOUTCLK_REF_FREQ] = $realtobits(CH1_TXOUTCLK_REF_FREQ);
  ATTR[`GTM2_QUAD__CH1_TXOUTCLK_REF_SOURCE] = CH1_TXOUTCLK_REF_SOURCE;
  ATTR[`GTM2_QUAD__CH2_RXOUTCLK_FREQ] = $realtobits(CH2_RXOUTCLK_FREQ);
  ATTR[`GTM2_QUAD__CH2_RXOUTCLK_REF_FREQ] = $realtobits(CH2_RXOUTCLK_REF_FREQ);
  ATTR[`GTM2_QUAD__CH2_RXOUTCLK_REF_SOURCE] = CH2_RXOUTCLK_REF_SOURCE;
  ATTR[`GTM2_QUAD__CH2_TXOUTCLK_FREQ] = $realtobits(CH2_TXOUTCLK_FREQ);
  ATTR[`GTM2_QUAD__CH2_TXOUTCLK_REF_FREQ] = $realtobits(CH2_TXOUTCLK_REF_FREQ);
  ATTR[`GTM2_QUAD__CH2_TXOUTCLK_REF_SOURCE] = CH2_TXOUTCLK_REF_SOURCE;
  ATTR[`GTM2_QUAD__CH3_RXOUTCLK_FREQ] = $realtobits(CH3_RXOUTCLK_FREQ);
  ATTR[`GTM2_QUAD__CH3_RXOUTCLK_REF_FREQ] = $realtobits(CH3_RXOUTCLK_REF_FREQ);
  ATTR[`GTM2_QUAD__CH3_RXOUTCLK_REF_SOURCE] = CH3_RXOUTCLK_REF_SOURCE;
  ATTR[`GTM2_QUAD__CH3_TXOUTCLK_FREQ] = $realtobits(CH3_TXOUTCLK_FREQ);
  ATTR[`GTM2_QUAD__CH3_TXOUTCLK_REF_FREQ] = $realtobits(CH3_TXOUTCLK_REF_FREQ);
  ATTR[`GTM2_QUAD__CH3_TXOUTCLK_REF_SOURCE] = CH3_TXOUTCLK_REF_SOURCE;
  ATTR[`GTM2_QUAD__CHANNEL_CONNECTIVITY] = CHANNEL_CONNECTIVITY;
  ATTR[`GTM2_QUAD__MEMORY_INIT_FILE] = MEMORY_INIT_FILE;
  ATTR[`GTM2_QUAD__STAT_NPI_REG_LIST] = STAT_NPI_REG_LIST;
end

always @(trig_attr) begin
  CH0_RXOUTCLK_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH0_RXOUTCLK_FREQ]);
  CH0_RXOUTCLK_REF_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH0_RXOUTCLK_REF_FREQ]);
  CH0_RXOUTCLK_REF_SOURCE_REG = ATTR[`GTM2_QUAD__CH0_RXOUTCLK_REF_SOURCE];
  CH0_TXOUTCLK_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH0_TXOUTCLK_FREQ]);
  CH0_TXOUTCLK_REF_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH0_TXOUTCLK_REF_FREQ]);
  CH0_TXOUTCLK_REF_SOURCE_REG = ATTR[`GTM2_QUAD__CH0_TXOUTCLK_REF_SOURCE];
  CH1_RXOUTCLK_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH1_RXOUTCLK_FREQ]);
  CH1_RXOUTCLK_REF_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH1_RXOUTCLK_REF_FREQ]);
  CH1_RXOUTCLK_REF_SOURCE_REG = ATTR[`GTM2_QUAD__CH1_RXOUTCLK_REF_SOURCE];
  CH1_TXOUTCLK_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH1_TXOUTCLK_FREQ]);
  CH1_TXOUTCLK_REF_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH1_TXOUTCLK_REF_FREQ]);
  CH1_TXOUTCLK_REF_SOURCE_REG = ATTR[`GTM2_QUAD__CH1_TXOUTCLK_REF_SOURCE];
  CH2_RXOUTCLK_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH2_RXOUTCLK_FREQ]);
  CH2_RXOUTCLK_REF_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH2_RXOUTCLK_REF_FREQ]);
  CH2_RXOUTCLK_REF_SOURCE_REG = ATTR[`GTM2_QUAD__CH2_RXOUTCLK_REF_SOURCE];
  CH2_TXOUTCLK_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH2_TXOUTCLK_FREQ]);
  CH2_TXOUTCLK_REF_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH2_TXOUTCLK_REF_FREQ]);
  CH2_TXOUTCLK_REF_SOURCE_REG = ATTR[`GTM2_QUAD__CH2_TXOUTCLK_REF_SOURCE];
  CH3_RXOUTCLK_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH3_RXOUTCLK_FREQ]);
  CH3_RXOUTCLK_REF_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH3_RXOUTCLK_REF_FREQ]);
  CH3_RXOUTCLK_REF_SOURCE_REG = ATTR[`GTM2_QUAD__CH3_RXOUTCLK_REF_SOURCE];
  CH3_TXOUTCLK_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH3_TXOUTCLK_FREQ]);
  CH3_TXOUTCLK_REF_FREQ_REG = $bitstoreal(ATTR[`GTM2_QUAD__CH3_TXOUTCLK_REF_FREQ]);
  CH3_TXOUTCLK_REF_SOURCE_REG = ATTR[`GTM2_QUAD__CH3_TXOUTCLK_REF_SOURCE];
  CHANNEL_CONNECTIVITY_REG = ATTR[`GTM2_QUAD__CHANNEL_CONNECTIVITY];
  MEMORY_INIT_FILE_REG = ATTR[`GTM2_QUAD__MEMORY_INIT_FILE];
  STAT_NPI_REG_LIST_REG = ATTR[`GTM2_QUAD__STAT_NPI_REG_LIST];
end

// procedures to override, read attribute values

task write_attr;
  input  [`GTM2_QUAD_ADDR_SZ-1:0] addr;
  input  [`GTM2_QUAD_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`GTM2_QUAD_DATA_SZ-1:0] read_attr;
  input  [`GTM2_QUAD_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
