`include "B_HBM_ONE_STACK_INTF_TEST_defines.vh"

reg [`HBM_ONE_STACK_INTF_TEST_DATA_SZ-1:0] ATTR [0:`HBM_ONE_STACK_INTF_TEST_ADDR_N-1];
reg [40:1] APB_BYPASS_EN_REG = APB_BYPASS_EN;
reg [40:1] AXI_BYPASS_EN_REG = AXI_BYPASS_EN;
reg [40:1] CLK_SEL_00_REG = CLK_SEL_00;
reg [40:1] CLK_SEL_01_REG = CLK_SEL_01;
reg [40:1] CLK_SEL_02_REG = CLK_SEL_02;
reg [40:1] CLK_SEL_03_REG = CLK_SEL_03;
reg [40:1] CLK_SEL_04_REG = CLK_SEL_04;
reg [40:1] CLK_SEL_05_REG = CLK_SEL_05;
reg [40:1] CLK_SEL_06_REG = CLK_SEL_06;
reg [40:1] CLK_SEL_07_REG = CLK_SEL_07;
reg [40:1] CLK_SEL_08_REG = CLK_SEL_08;
reg [40:1] CLK_SEL_09_REG = CLK_SEL_09;
reg [40:1] CLK_SEL_10_REG = CLK_SEL_10;
reg [40:1] CLK_SEL_11_REG = CLK_SEL_11;
reg [40:1] CLK_SEL_12_REG = CLK_SEL_12;
reg [40:1] CLK_SEL_13_REG = CLK_SEL_13;
reg [40:1] CLK_SEL_14_REG = CLK_SEL_14;
reg [40:1] CLK_SEL_15_REG = CLK_SEL_15;
reg [51:0] DBG_BYPASS_VAL_REG = DBG_BYPASS_VAL;
reg [40:1] DEBUG_MODE_REG = DEBUG_MODE;
reg [31:0] DFI_BYPASS_VAL_REG = DFI_BYPASS_VAL;
reg [40:1] MC_ENABLE_0_REG = MC_ENABLE_0;
reg [40:1] MC_ENABLE_1_REG = MC_ENABLE_1;
reg [40:1] MC_ENABLE_2_REG = MC_ENABLE_2;
reg [40:1] MC_ENABLE_3_REG = MC_ENABLE_3;
reg [40:1] MC_ENABLE_4_REG = MC_ENABLE_4;
reg [40:1] MC_ENABLE_5_REG = MC_ENABLE_5;
reg [40:1] MC_ENABLE_6_REG = MC_ENABLE_6;
reg [40:1] MC_ENABLE_7_REG = MC_ENABLE_7;
reg [40:1] PHY_ENABLE_0_REG = PHY_ENABLE_0;
reg [40:1] PHY_ENABLE_1_REG = PHY_ENABLE_1;
reg [40:1] PHY_ENABLE_2_REG = PHY_ENABLE_2;
reg [40:1] PHY_ENABLE_3_REG = PHY_ENABLE_3;
reg [40:1] PHY_ENABLE_4_REG = PHY_ENABLE_4;
reg [40:1] PHY_ENABLE_5_REG = PHY_ENABLE_5;
reg [40:1] PHY_ENABLE_6_REG = PHY_ENABLE_6;
reg [40:1] PHY_ENABLE_7_REG = PHY_ENABLE_7;
reg [40:1] SWITCH_ENABLE_REG = SWITCH_ENABLE;

initial begin
  ATTR[`HBM_ONE_STACK_INTF_TEST__APB_BYPASS_EN] = APB_BYPASS_EN;
  ATTR[`HBM_ONE_STACK_INTF_TEST__AXI_BYPASS_EN] = AXI_BYPASS_EN;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_00] = CLK_SEL_00;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_01] = CLK_SEL_01;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_02] = CLK_SEL_02;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_03] = CLK_SEL_03;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_04] = CLK_SEL_04;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_05] = CLK_SEL_05;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_06] = CLK_SEL_06;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_07] = CLK_SEL_07;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_08] = CLK_SEL_08;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_09] = CLK_SEL_09;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_10] = CLK_SEL_10;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_11] = CLK_SEL_11;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_12] = CLK_SEL_12;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_13] = CLK_SEL_13;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_14] = CLK_SEL_14;
  ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_15] = CLK_SEL_15;
  ATTR[`HBM_ONE_STACK_INTF_TEST__DBG_BYPASS_VAL] = DBG_BYPASS_VAL;
  ATTR[`HBM_ONE_STACK_INTF_TEST__DEBUG_MODE] = DEBUG_MODE;
  ATTR[`HBM_ONE_STACK_INTF_TEST__DFI_BYPASS_VAL] = DFI_BYPASS_VAL;
  ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_0] = MC_ENABLE_0;
  ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_1] = MC_ENABLE_1;
  ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_2] = MC_ENABLE_2;
  ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_3] = MC_ENABLE_3;
  ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_4] = MC_ENABLE_4;
  ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_5] = MC_ENABLE_5;
  ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_6] = MC_ENABLE_6;
  ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_7] = MC_ENABLE_7;
  ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_0] = PHY_ENABLE_0;
  ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_1] = PHY_ENABLE_1;
  ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_2] = PHY_ENABLE_2;
  ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_3] = PHY_ENABLE_3;
  ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_4] = PHY_ENABLE_4;
  ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_5] = PHY_ENABLE_5;
  ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_6] = PHY_ENABLE_6;
  ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_7] = PHY_ENABLE_7;
  ATTR[`HBM_ONE_STACK_INTF_TEST__SWITCH_ENABLE] = SWITCH_ENABLE;
end

always @(trig_attr) begin
  APB_BYPASS_EN_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__APB_BYPASS_EN];
  AXI_BYPASS_EN_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__AXI_BYPASS_EN];
  CLK_SEL_00_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_00];
  CLK_SEL_01_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_01];
  CLK_SEL_02_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_02];
  CLK_SEL_03_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_03];
  CLK_SEL_04_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_04];
  CLK_SEL_05_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_05];
  CLK_SEL_06_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_06];
  CLK_SEL_07_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_07];
  CLK_SEL_08_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_08];
  CLK_SEL_09_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_09];
  CLK_SEL_10_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_10];
  CLK_SEL_11_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_11];
  CLK_SEL_12_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_12];
  CLK_SEL_13_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_13];
  CLK_SEL_14_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_14];
  CLK_SEL_15_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__CLK_SEL_15];
  DBG_BYPASS_VAL_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__DBG_BYPASS_VAL];
  DEBUG_MODE_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__DEBUG_MODE];
  DFI_BYPASS_VAL_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__DFI_BYPASS_VAL];
  MC_ENABLE_0_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_0];
  MC_ENABLE_1_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_1];
  MC_ENABLE_2_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_2];
  MC_ENABLE_3_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_3];
  MC_ENABLE_4_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_4];
  MC_ENABLE_5_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_5];
  MC_ENABLE_6_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_6];
  MC_ENABLE_7_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__MC_ENABLE_7];
  PHY_ENABLE_0_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_0];
  PHY_ENABLE_1_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_1];
  PHY_ENABLE_2_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_2];
  PHY_ENABLE_3_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_3];
  PHY_ENABLE_4_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_4];
  PHY_ENABLE_5_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_5];
  PHY_ENABLE_6_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_6];
  PHY_ENABLE_7_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__PHY_ENABLE_7];
  SWITCH_ENABLE_REG = ATTR[`HBM_ONE_STACK_INTF_TEST__SWITCH_ENABLE];
end

// procedures to override, read attribute values

task write_attr;
  input  [`HBM_ONE_STACK_INTF_TEST_ADDR_SZ-1:0] addr;
  input  [`HBM_ONE_STACK_INTF_TEST_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`HBM_ONE_STACK_INTF_TEST_DATA_SZ-1:0] read_attr;
  input  [`HBM_ONE_STACK_INTF_TEST_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
