`include "B_HNICPIPE_QUAD_defines.vh"

reg [`HNICPIPE_QUAD_DATA_SZ-1:0] ATTR [0:`HNICPIPE_QUAD_ADDR_N-1];
reg [`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG0_SZ-1:0] HNICPIPE_HPIPE_CFG0_REG = HNICPIPE_HPIPE_CFG0;
reg [`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG1_SZ-1:0] HNICPIPE_HPIPE_CFG1_REG = HNICPIPE_HPIPE_CFG1;
reg [`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG2_SZ-1:0] HNICPIPE_HPIPE_CFG2_REG = HNICPIPE_HPIPE_CFG2;
reg [`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG3_SZ-1:0] HNICPIPE_HPIPE_CFG3_REG = HNICPIPE_HPIPE_CFG3;
reg [`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG4_SZ-1:0] HNICPIPE_HPIPE_CFG4_REG = HNICPIPE_HPIPE_CFG4;
reg [`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG5_SZ-1:0] HNICPIPE_HPIPE_CFG5_REG = HNICPIPE_HPIPE_CFG5;
reg [`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG6_SZ-1:0] HNICPIPE_HPIPE_CFG6_REG = HNICPIPE_HPIPE_CFG6;
reg [`HNICPIPE_QUAD__HNICPIPE_OPTDLY_CFG0_SZ-1:0] HNICPIPE_OPTDLY_CFG0_REG = HNICPIPE_OPTDLY_CFG0;
reg [`HNICPIPE_QUAD__HNICPIPE_OPTDLY_CFG1_SZ-1:0] HNICPIPE_OPTDLY_CFG1_REG = HNICPIPE_OPTDLY_CFG1;
reg [`HNICPIPE_QUAD__HNICPIPE_PIPE_CFG_SZ-1:0] HNICPIPE_PIPE_CFG_REG = HNICPIPE_PIPE_CFG;
reg [`HNICPIPE_QUAD__HNICPIPE_RX_CLKMUX_SEL_SZ-1:0] HNICPIPE_RX_CLKMUX_SEL_REG = HNICPIPE_RX_CLKMUX_SEL;
reg [`HNICPIPE_QUAD__HNICPIPE_RX_CLK_REMAP_CFG_SZ-1:0] HNICPIPE_RX_CLK_REMAP_CFG_REG = HNICPIPE_RX_CLK_REMAP_CFG;
reg [`HNICPIPE_QUAD__HNICPIPE_RX_DATA_REMAP_CFG_SZ-1:0] HNICPIPE_RX_DATA_REMAP_CFG_REG = HNICPIPE_RX_DATA_REMAP_CFG;
reg [`HNICPIPE_QUAD__HNICPIPE_TX_CLKMUX_SEL_SZ-1:0] HNICPIPE_TX_CLKMUX_SEL_REG = HNICPIPE_TX_CLKMUX_SEL;
reg [`HNICPIPE_QUAD__HNICPIPE_TX_CLK_REMAP_CFG_SZ-1:0] HNICPIPE_TX_CLK_REMAP_CFG_REG = HNICPIPE_TX_CLK_REMAP_CFG;
reg [`HNICPIPE_QUAD__HNICPIPE_TX_DATA_REMAP_CFG_SZ-1:0] HNICPIPE_TX_DATA_REMAP_CFG_REG = HNICPIPE_TX_DATA_REMAP_CFG;

initial begin
  ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG0] = HNICPIPE_HPIPE_CFG0;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG1] = HNICPIPE_HPIPE_CFG1;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG2] = HNICPIPE_HPIPE_CFG2;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG3] = HNICPIPE_HPIPE_CFG3;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG4] = HNICPIPE_HPIPE_CFG4;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG5] = HNICPIPE_HPIPE_CFG5;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG6] = HNICPIPE_HPIPE_CFG6;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_OPTDLY_CFG0] = HNICPIPE_OPTDLY_CFG0;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_OPTDLY_CFG1] = HNICPIPE_OPTDLY_CFG1;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_PIPE_CFG] = HNICPIPE_PIPE_CFG;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_RX_CLKMUX_SEL] = HNICPIPE_RX_CLKMUX_SEL;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_RX_CLK_REMAP_CFG] = HNICPIPE_RX_CLK_REMAP_CFG;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_RX_DATA_REMAP_CFG] = HNICPIPE_RX_DATA_REMAP_CFG;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_TX_CLKMUX_SEL] = HNICPIPE_TX_CLKMUX_SEL;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_TX_CLK_REMAP_CFG] = HNICPIPE_TX_CLK_REMAP_CFG;
  ATTR[`HNICPIPE_QUAD__HNICPIPE_TX_DATA_REMAP_CFG] = HNICPIPE_TX_DATA_REMAP_CFG;
end

always @(trig_attr) begin
  HNICPIPE_HPIPE_CFG0_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG0];
  HNICPIPE_HPIPE_CFG1_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG1];
  HNICPIPE_HPIPE_CFG2_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG2];
  HNICPIPE_HPIPE_CFG3_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG3];
  HNICPIPE_HPIPE_CFG4_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG4];
  HNICPIPE_HPIPE_CFG5_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG5];
  HNICPIPE_HPIPE_CFG6_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_HPIPE_CFG6];
  HNICPIPE_OPTDLY_CFG0_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_OPTDLY_CFG0];
  HNICPIPE_OPTDLY_CFG1_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_OPTDLY_CFG1];
  HNICPIPE_PIPE_CFG_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_PIPE_CFG];
  HNICPIPE_RX_CLKMUX_SEL_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_RX_CLKMUX_SEL];
  HNICPIPE_RX_CLK_REMAP_CFG_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_RX_CLK_REMAP_CFG];
  HNICPIPE_RX_DATA_REMAP_CFG_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_RX_DATA_REMAP_CFG];
  HNICPIPE_TX_CLKMUX_SEL_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_TX_CLKMUX_SEL];
  HNICPIPE_TX_CLK_REMAP_CFG_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_TX_CLK_REMAP_CFG];
  HNICPIPE_TX_DATA_REMAP_CFG_REG = ATTR[`HNICPIPE_QUAD__HNICPIPE_TX_DATA_REMAP_CFG];
end

// procedures to override, read attribute values

task write_attr;
  input  [`HNICPIPE_QUAD_ADDR_SZ-1:0] addr;
  input  [`HNICPIPE_QUAD_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`HNICPIPE_QUAD_DATA_SZ-1:0] read_attr;
  input  [`HNICPIPE_QUAD_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
