`include "B_ISP2_defines.vh"

reg [`ISP2_DATA_SZ-1:0] ATTR [0:`ISP2_ADDR_N-1];
reg [`ISP2__ISP_CORE_0_FRAME_RATE_SZ-1:0] ISP_CORE_0_FRAME_RATE_REG = ISP_CORE_0_FRAME_RATE;
reg [`ISP2__ISP_CORE_0_NO_OF_SENSORS_SZ-1:0] ISP_CORE_0_NO_OF_SENSORS_REG = ISP_CORE_0_NO_OF_SENSORS;
reg [`ISP2__ISP_CORE_0_RESOLUTION_MP_SZ-1:0] ISP_CORE_0_RESOLUTION_MP_REG = ISP_CORE_0_RESOLUTION_MP;
reg [`ISP2__ISP_CORE_1_FRAME_RATE_SZ-1:0] ISP_CORE_1_FRAME_RATE_REG = ISP_CORE_1_FRAME_RATE;
reg [`ISP2__ISP_CORE_1_NO_OF_SENSORS_SZ-1:0] ISP_CORE_1_NO_OF_SENSORS_REG = ISP_CORE_1_NO_OF_SENSORS;
reg [`ISP2__ISP_CORE_1_RESOLUTION_MP_SZ-1:0] ISP_CORE_1_RESOLUTION_MP_REG = ISP_CORE_1_RESOLUTION_MP;

initial begin
  ATTR[`ISP2__ISP_CORE_0_FRAME_RATE] = ISP_CORE_0_FRAME_RATE;
  ATTR[`ISP2__ISP_CORE_0_NO_OF_SENSORS] = ISP_CORE_0_NO_OF_SENSORS;
  ATTR[`ISP2__ISP_CORE_0_RESOLUTION_MP] = ISP_CORE_0_RESOLUTION_MP;
  ATTR[`ISP2__ISP_CORE_1_FRAME_RATE] = ISP_CORE_1_FRAME_RATE;
  ATTR[`ISP2__ISP_CORE_1_NO_OF_SENSORS] = ISP_CORE_1_NO_OF_SENSORS;
  ATTR[`ISP2__ISP_CORE_1_RESOLUTION_MP] = ISP_CORE_1_RESOLUTION_MP;
end

always @(trig_attr) begin
  ISP_CORE_0_FRAME_RATE_REG = ATTR[`ISP2__ISP_CORE_0_FRAME_RATE];
  ISP_CORE_0_NO_OF_SENSORS_REG = ATTR[`ISP2__ISP_CORE_0_NO_OF_SENSORS];
  ISP_CORE_0_RESOLUTION_MP_REG = ATTR[`ISP2__ISP_CORE_0_RESOLUTION_MP];
  ISP_CORE_1_FRAME_RATE_REG = ATTR[`ISP2__ISP_CORE_1_FRAME_RATE];
  ISP_CORE_1_NO_OF_SENSORS_REG = ATTR[`ISP2__ISP_CORE_1_NO_OF_SENSORS];
  ISP_CORE_1_RESOLUTION_MP_REG = ATTR[`ISP2__ISP_CORE_1_RESOLUTION_MP];
end

// procedures to override, read attribute values

task write_attr;
  input  [`ISP2_ADDR_SZ-1:0] addr;
  input  [`ISP2_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`ISP2_DATA_SZ-1:0] read_attr;
  input  [`ISP2_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
