`include "B_MMI_defines.vh"

reg [`MMI_DATA_SZ-1:0] ATTR [0:`MMI_ADDR_N-1];
reg [`MMI__DISPLAY_CONTROLLER_MODE_SZ:1] DISPLAY_CONTROLLER_MODE_REG = DISPLAY_CONTROLLER_MODE;
reg [`MMI__DISPLAY_PORT_ENABLE_SZ:1] DISPLAY_PORT_ENABLE_REG = DISPLAY_PORT_ENABLE;
reg [`MMI__DISPLAY_PORT_LANES_SZ-1:0] DISPLAY_PORT_LANES_REG = DISPLAY_PORT_LANES;
reg [`MMI__ETHERNET_ENABLE_SZ:1] ETHERNET_ENABLE_REG = ETHERNET_ENABLE;
real GPU_CORE0_ACTIVITY_FACTOR_REG = GPU_CORE0_ACTIVITY_FACTOR;
reg [`MMI__GPU_CORE0_CLOCK_ENABLE_SZ:1] GPU_CORE0_CLOCK_ENABLE_REG = GPU_CORE0_CLOCK_ENABLE;
reg [`MMI__GPU_CORE0_POWER_ENABLE_SZ:1] GPU_CORE0_POWER_ENABLE_REG = GPU_CORE0_POWER_ENABLE;
real GPU_CORE1_ACTIVITY_FACTOR_REG = GPU_CORE1_ACTIVITY_FACTOR;
reg [`MMI__GPU_CORE1_CLOCK_ENABLE_SZ:1] GPU_CORE1_CLOCK_ENABLE_REG = GPU_CORE1_CLOCK_ENABLE;
reg [`MMI__GPU_CORE1_POWER_ENABLE_SZ:1] GPU_CORE1_POWER_ENABLE_REG = GPU_CORE1_POWER_ENABLE;
real GPU_CORE2_ACTIVITY_FACTOR_REG = GPU_CORE2_ACTIVITY_FACTOR;
reg [`MMI__GPU_CORE2_CLOCK_ENABLE_SZ:1] GPU_CORE2_CLOCK_ENABLE_REG = GPU_CORE2_CLOCK_ENABLE;
reg [`MMI__GPU_CORE2_POWER_ENABLE_SZ:1] GPU_CORE2_POWER_ENABLE_REG = GPU_CORE2_POWER_ENABLE;
real GPU_CORE3_ACTIVITY_FACTOR_REG = GPU_CORE3_ACTIVITY_FACTOR;
reg [`MMI__GPU_CORE3_CLOCK_ENABLE_SZ:1] GPU_CORE3_CLOCK_ENABLE_REG = GPU_CORE3_CLOCK_ENABLE;
reg [`MMI__GPU_CORE3_POWER_ENABLE_SZ:1] GPU_CORE3_POWER_ENABLE_REG = GPU_CORE3_POWER_ENABLE;
reg [`MMI__GPU_FREQUENCY_SZ-1:0] GPU_FREQUENCY_REG = GPU_FREQUENCY;
reg [`MMI__PCIE0_LINK_SPEED_SZ:1] PCIE0_LINK_SPEED_REG = PCIE0_LINK_SPEED;
reg [`MMI__PCIE0_LINK_WIDTH_SZ:1] PCIE0_LINK_WIDTH_REG = PCIE0_LINK_WIDTH;
reg [`MMI__PCIE1_LINK_SPEED_SZ:1] PCIE1_LINK_SPEED_REG = PCIE1_LINK_SPEED;
reg [`MMI__PCIE1_LINK_WIDTH_SZ:1] PCIE1_LINK_WIDTH_REG = PCIE1_LINK_WIDTH;
reg [`MMI__SIM_MMI_CDO_FILE_NAME_SZ:1] SIM_MMI_CDO_FILE_NAME_REG = SIM_MMI_CDO_FILE_NAME;
reg [`MMI__SIM_MMI_CDO_MODE_SZ-1:0] SIM_MMI_CDO_MODE_REG = SIM_MMI_CDO_MODE;
reg [`MMI__SIM_VERSION_SZ-1:0] SIM_VERSION_REG = SIM_VERSION;
real SLICE0_ACTIVITY_FACTOR_REG = SLICE0_ACTIVITY_FACTOR;
reg [`MMI__SLICE0_CLOCK_ENABLE_SZ:1] SLICE0_CLOCK_ENABLE_REG = SLICE0_CLOCK_ENABLE;
reg [`MMI__SLICE0_POWER_ENABLE_SZ:1] SLICE0_POWER_ENABLE_REG = SLICE0_POWER_ENABLE;
real SLICE1_ACTIVITY_FACTOR_REG = SLICE1_ACTIVITY_FACTOR;
reg [`MMI__SLICE1_CLOCK_ENABLE_SZ:1] SLICE1_CLOCK_ENABLE_REG = SLICE1_CLOCK_ENABLE;
reg [`MMI__SLICE1_POWER_ENABLE_SZ:1] SLICE1_POWER_ENABLE_REG = SLICE1_POWER_ENABLE;
reg [`MMI__USB2_ENABLE_SZ:1] USB2_ENABLE_REG = USB2_ENABLE;
reg [`MMI__USB3_ENABLE_SZ:1] USB3_ENABLE_REG = USB3_ENABLE;

initial begin
  ATTR[`MMI__DISPLAY_CONTROLLER_MODE] = DISPLAY_CONTROLLER_MODE;
  ATTR[`MMI__DISPLAY_PORT_ENABLE] = DISPLAY_PORT_ENABLE;
  ATTR[`MMI__DISPLAY_PORT_LANES] = DISPLAY_PORT_LANES;
  ATTR[`MMI__ETHERNET_ENABLE] = ETHERNET_ENABLE;
  ATTR[`MMI__GPU_CORE0_ACTIVITY_FACTOR] = $realtobits(GPU_CORE0_ACTIVITY_FACTOR);
  ATTR[`MMI__GPU_CORE0_CLOCK_ENABLE] = GPU_CORE0_CLOCK_ENABLE;
  ATTR[`MMI__GPU_CORE0_POWER_ENABLE] = GPU_CORE0_POWER_ENABLE;
  ATTR[`MMI__GPU_CORE1_ACTIVITY_FACTOR] = $realtobits(GPU_CORE1_ACTIVITY_FACTOR);
  ATTR[`MMI__GPU_CORE1_CLOCK_ENABLE] = GPU_CORE1_CLOCK_ENABLE;
  ATTR[`MMI__GPU_CORE1_POWER_ENABLE] = GPU_CORE1_POWER_ENABLE;
  ATTR[`MMI__GPU_CORE2_ACTIVITY_FACTOR] = $realtobits(GPU_CORE2_ACTIVITY_FACTOR);
  ATTR[`MMI__GPU_CORE2_CLOCK_ENABLE] = GPU_CORE2_CLOCK_ENABLE;
  ATTR[`MMI__GPU_CORE2_POWER_ENABLE] = GPU_CORE2_POWER_ENABLE;
  ATTR[`MMI__GPU_CORE3_ACTIVITY_FACTOR] = $realtobits(GPU_CORE3_ACTIVITY_FACTOR);
  ATTR[`MMI__GPU_CORE3_CLOCK_ENABLE] = GPU_CORE3_CLOCK_ENABLE;
  ATTR[`MMI__GPU_CORE3_POWER_ENABLE] = GPU_CORE3_POWER_ENABLE;
  ATTR[`MMI__GPU_FREQUENCY] = GPU_FREQUENCY;
  ATTR[`MMI__PCIE0_LINK_SPEED] = PCIE0_LINK_SPEED;
  ATTR[`MMI__PCIE0_LINK_WIDTH] = PCIE0_LINK_WIDTH;
  ATTR[`MMI__PCIE1_LINK_SPEED] = PCIE1_LINK_SPEED;
  ATTR[`MMI__PCIE1_LINK_WIDTH] = PCIE1_LINK_WIDTH;
  ATTR[`MMI__SIM_MMI_CDO_FILE_NAME] = SIM_MMI_CDO_FILE_NAME;
  ATTR[`MMI__SIM_MMI_CDO_MODE] = SIM_MMI_CDO_MODE;
  ATTR[`MMI__SIM_VERSION] = SIM_VERSION;
  ATTR[`MMI__SLICE0_ACTIVITY_FACTOR] = $realtobits(SLICE0_ACTIVITY_FACTOR);
  ATTR[`MMI__SLICE0_CLOCK_ENABLE] = SLICE0_CLOCK_ENABLE;
  ATTR[`MMI__SLICE0_POWER_ENABLE] = SLICE0_POWER_ENABLE;
  ATTR[`MMI__SLICE1_ACTIVITY_FACTOR] = $realtobits(SLICE1_ACTIVITY_FACTOR);
  ATTR[`MMI__SLICE1_CLOCK_ENABLE] = SLICE1_CLOCK_ENABLE;
  ATTR[`MMI__SLICE1_POWER_ENABLE] = SLICE1_POWER_ENABLE;
  ATTR[`MMI__USB2_ENABLE] = USB2_ENABLE;
  ATTR[`MMI__USB3_ENABLE] = USB3_ENABLE;
end

always @(trig_attr) begin
  DISPLAY_CONTROLLER_MODE_REG = ATTR[`MMI__DISPLAY_CONTROLLER_MODE];
  DISPLAY_PORT_ENABLE_REG = ATTR[`MMI__DISPLAY_PORT_ENABLE];
  DISPLAY_PORT_LANES_REG = ATTR[`MMI__DISPLAY_PORT_LANES];
  ETHERNET_ENABLE_REG = ATTR[`MMI__ETHERNET_ENABLE];
  GPU_CORE0_ACTIVITY_FACTOR_REG = $bitstoreal(ATTR[`MMI__GPU_CORE0_ACTIVITY_FACTOR]);
  GPU_CORE0_CLOCK_ENABLE_REG = ATTR[`MMI__GPU_CORE0_CLOCK_ENABLE];
  GPU_CORE0_POWER_ENABLE_REG = ATTR[`MMI__GPU_CORE0_POWER_ENABLE];
  GPU_CORE1_ACTIVITY_FACTOR_REG = $bitstoreal(ATTR[`MMI__GPU_CORE1_ACTIVITY_FACTOR]);
  GPU_CORE1_CLOCK_ENABLE_REG = ATTR[`MMI__GPU_CORE1_CLOCK_ENABLE];
  GPU_CORE1_POWER_ENABLE_REG = ATTR[`MMI__GPU_CORE1_POWER_ENABLE];
  GPU_CORE2_ACTIVITY_FACTOR_REG = $bitstoreal(ATTR[`MMI__GPU_CORE2_ACTIVITY_FACTOR]);
  GPU_CORE2_CLOCK_ENABLE_REG = ATTR[`MMI__GPU_CORE2_CLOCK_ENABLE];
  GPU_CORE2_POWER_ENABLE_REG = ATTR[`MMI__GPU_CORE2_POWER_ENABLE];
  GPU_CORE3_ACTIVITY_FACTOR_REG = $bitstoreal(ATTR[`MMI__GPU_CORE3_ACTIVITY_FACTOR]);
  GPU_CORE3_CLOCK_ENABLE_REG = ATTR[`MMI__GPU_CORE3_CLOCK_ENABLE];
  GPU_CORE3_POWER_ENABLE_REG = ATTR[`MMI__GPU_CORE3_POWER_ENABLE];
  GPU_FREQUENCY_REG = ATTR[`MMI__GPU_FREQUENCY];
  PCIE0_LINK_SPEED_REG = ATTR[`MMI__PCIE0_LINK_SPEED];
  PCIE0_LINK_WIDTH_REG = ATTR[`MMI__PCIE0_LINK_WIDTH];
  PCIE1_LINK_SPEED_REG = ATTR[`MMI__PCIE1_LINK_SPEED];
  PCIE1_LINK_WIDTH_REG = ATTR[`MMI__PCIE1_LINK_WIDTH];
  SIM_MMI_CDO_FILE_NAME_REG = ATTR[`MMI__SIM_MMI_CDO_FILE_NAME];
  SIM_MMI_CDO_MODE_REG = ATTR[`MMI__SIM_MMI_CDO_MODE];
  SIM_VERSION_REG = ATTR[`MMI__SIM_VERSION];
  SLICE0_ACTIVITY_FACTOR_REG = $bitstoreal(ATTR[`MMI__SLICE0_ACTIVITY_FACTOR]);
  SLICE0_CLOCK_ENABLE_REG = ATTR[`MMI__SLICE0_CLOCK_ENABLE];
  SLICE0_POWER_ENABLE_REG = ATTR[`MMI__SLICE0_POWER_ENABLE];
  SLICE1_ACTIVITY_FACTOR_REG = $bitstoreal(ATTR[`MMI__SLICE1_ACTIVITY_FACTOR]);
  SLICE1_CLOCK_ENABLE_REG = ATTR[`MMI__SLICE1_CLOCK_ENABLE];
  SLICE1_POWER_ENABLE_REG = ATTR[`MMI__SLICE1_POWER_ENABLE];
  USB2_ENABLE_REG = ATTR[`MMI__USB2_ENABLE];
  USB3_ENABLE_REG = ATTR[`MMI__USB3_ENABLE];
end

// procedures to override, read attribute values

task write_attr;
  input  [`MMI_ADDR_SZ-1:0] addr;
  input  [`MMI_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`MMI_DATA_SZ-1:0] read_attr;
  input  [`MMI_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
