`include "B_NOC2_XBR4X2_defines.vh"

reg [`NOC2_XBR4X2_DATA_SZ-1:0] ATTR [0:`NOC2_XBR4X2_ADDR_N-1];
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP0_VCA_RD_TOKEN_SZ-1:0] REG_DDR2NOC_DP0_NP0_VCA_RD_TOKEN_REG = REG_DDR2NOC_DP0_NP0_VCA_RD_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP0_VCA_WR_TOKEN_SZ-1:0] REG_DDR2NOC_DP0_NP0_VCA_WR_TOKEN_REG = REG_DDR2NOC_DP0_NP0_VCA_WR_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP1_VCA_RD_TOKEN_SZ-1:0] REG_DDR2NOC_DP0_NP1_VCA_RD_TOKEN_REG = REG_DDR2NOC_DP0_NP1_VCA_RD_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP1_VCA_WR_TOKEN_SZ-1:0] REG_DDR2NOC_DP0_NP1_VCA_WR_TOKEN_REG = REG_DDR2NOC_DP0_NP1_VCA_WR_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP2_VCA_RD_TOKEN_SZ-1:0] REG_DDR2NOC_DP0_NP2_VCA_RD_TOKEN_REG = REG_DDR2NOC_DP0_NP2_VCA_RD_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP2_VCA_WR_TOKEN_SZ-1:0] REG_DDR2NOC_DP0_NP2_VCA_WR_TOKEN_REG = REG_DDR2NOC_DP0_NP2_VCA_WR_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP3_VCA_RD_TOKEN_SZ-1:0] REG_DDR2NOC_DP0_NP3_VCA_RD_TOKEN_REG = REG_DDR2NOC_DP0_NP3_VCA_RD_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP3_VCA_WR_TOKEN_SZ-1:0] REG_DDR2NOC_DP0_NP3_VCA_WR_TOKEN_REG = REG_DDR2NOC_DP0_NP3_VCA_WR_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP0_VCA_RD_TOKEN_SZ-1:0] REG_DDR2NOC_DP1_NP0_VCA_RD_TOKEN_REG = REG_DDR2NOC_DP1_NP0_VCA_RD_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP0_VCA_WR_TOKEN_SZ-1:0] REG_DDR2NOC_DP1_NP0_VCA_WR_TOKEN_REG = REG_DDR2NOC_DP1_NP0_VCA_WR_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP1_VCA_RD_TOKEN_SZ-1:0] REG_DDR2NOC_DP1_NP1_VCA_RD_TOKEN_REG = REG_DDR2NOC_DP1_NP1_VCA_RD_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP1_VCA_WR_TOKEN_SZ-1:0] REG_DDR2NOC_DP1_NP1_VCA_WR_TOKEN_REG = REG_DDR2NOC_DP1_NP1_VCA_WR_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP2_VCA_RD_TOKEN_SZ-1:0] REG_DDR2NOC_DP1_NP2_VCA_RD_TOKEN_REG = REG_DDR2NOC_DP1_NP2_VCA_RD_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP2_VCA_WR_TOKEN_SZ-1:0] REG_DDR2NOC_DP1_NP2_VCA_WR_TOKEN_REG = REG_DDR2NOC_DP1_NP2_VCA_WR_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP3_VCA_RD_TOKEN_SZ-1:0] REG_DDR2NOC_DP1_NP3_VCA_RD_TOKEN_REG = REG_DDR2NOC_DP1_NP3_VCA_RD_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP3_VCA_WR_TOKEN_SZ-1:0] REG_DDR2NOC_DP1_NP3_VCA_WR_TOKEN_REG = REG_DDR2NOC_DP1_NP3_VCA_WR_TOKEN;
reg [`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP0_SZ-1:0] REG_DDR2NOC_PRI_NP0_REG = REG_DDR2NOC_PRI_NP0;
reg [`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP1_SZ-1:0] REG_DDR2NOC_PRI_NP1_REG = REG_DDR2NOC_PRI_NP1;
reg [`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP2_SZ-1:0] REG_DDR2NOC_PRI_NP2_REG = REG_DDR2NOC_PRI_NP2;
reg [`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP3_SZ-1:0] REG_DDR2NOC_PRI_NP3_REG = REG_DDR2NOC_PRI_NP3;
reg [`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP0_SZ-1:0] REG_DDR2NOC_RD_VC_MAP_NP0_REG = REG_DDR2NOC_RD_VC_MAP_NP0;
reg [`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP1_SZ-1:0] REG_DDR2NOC_RD_VC_MAP_NP1_REG = REG_DDR2NOC_RD_VC_MAP_NP1;
reg [`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP2_SZ-1:0] REG_DDR2NOC_RD_VC_MAP_NP2_REG = REG_DDR2NOC_RD_VC_MAP_NP2;
reg [`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP3_SZ-1:0] REG_DDR2NOC_RD_VC_MAP_NP3_REG = REG_DDR2NOC_RD_VC_MAP_NP3;
reg [`NOC2_XBR4X2__REG_DST_ID_P0_SZ-1:0] REG_DST_ID_P0_REG = REG_DST_ID_P0;
reg [`NOC2_XBR4X2__REG_DST_ID_P1_SZ-1:0] REG_DST_ID_P1_REG = REG_DST_ID_P1;
reg [`NOC2_XBR4X2__REG_NOC2DDR_NP0_DP0_VCA_TOKEN_SZ-1:0] REG_NOC2DDR_NP0_DP0_VCA_TOKEN_REG = REG_NOC2DDR_NP0_DP0_VCA_TOKEN;
reg [`NOC2_XBR4X2__REG_NOC2DDR_NP0_DP1_VCA_TOKEN_SZ-1:0] REG_NOC2DDR_NP0_DP1_VCA_TOKEN_REG = REG_NOC2DDR_NP0_DP1_VCA_TOKEN;
reg [`NOC2_XBR4X2__REG_NOC2DDR_NP1_DP0_VCA_TOKEN_SZ-1:0] REG_NOC2DDR_NP1_DP0_VCA_TOKEN_REG = REG_NOC2DDR_NP1_DP0_VCA_TOKEN;
reg [`NOC2_XBR4X2__REG_NOC2DDR_NP1_DP1_VCA_TOKEN_SZ-1:0] REG_NOC2DDR_NP1_DP1_VCA_TOKEN_REG = REG_NOC2DDR_NP1_DP1_VCA_TOKEN;
reg [`NOC2_XBR4X2__REG_NOC2DDR_NP2_DP0_VCA_TOKEN_SZ-1:0] REG_NOC2DDR_NP2_DP0_VCA_TOKEN_REG = REG_NOC2DDR_NP2_DP0_VCA_TOKEN;
reg [`NOC2_XBR4X2__REG_NOC2DDR_NP2_DP1_VCA_TOKEN_SZ-1:0] REG_NOC2DDR_NP2_DP1_VCA_TOKEN_REG = REG_NOC2DDR_NP2_DP1_VCA_TOKEN;
reg [`NOC2_XBR4X2__REG_NOC2DDR_NP3_DP0_VCA_TOKEN_SZ-1:0] REG_NOC2DDR_NP3_DP0_VCA_TOKEN_REG = REG_NOC2DDR_NP3_DP0_VCA_TOKEN;
reg [`NOC2_XBR4X2__REG_NOC2DDR_NP3_DP1_VCA_TOKEN_SZ-1:0] REG_NOC2DDR_NP3_DP1_VCA_TOKEN_REG = REG_NOC2DDR_NP3_DP1_VCA_TOKEN;
reg [`NOC2_XBR4X2__REG_NOC2DDR_PRI_DP0_SZ-1:0] REG_NOC2DDR_PRI_DP0_REG = REG_NOC2DDR_PRI_DP0;
reg [`NOC2_XBR4X2__REG_NOC2DDR_PRI_DP1_SZ-1:0] REG_NOC2DDR_PRI_DP1_REG = REG_NOC2DDR_PRI_DP1;
reg [`NOC2_XBR4X2__REG_NOC2DDR_RD_CH_IDX_MAP_DP0_SZ-1:0] REG_NOC2DDR_RD_CH_IDX_MAP_DP0_REG = REG_NOC2DDR_RD_CH_IDX_MAP_DP0;
reg [`NOC2_XBR4X2__REG_NOC2DDR_RD_CH_IDX_MAP_DP1_SZ-1:0] REG_NOC2DDR_RD_CH_IDX_MAP_DP1_REG = REG_NOC2DDR_RD_CH_IDX_MAP_DP1;
reg REG_NOC_CTL_REG = REG_NOC_CTL;

initial begin
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP0_VCA_RD_TOKEN] = REG_DDR2NOC_DP0_NP0_VCA_RD_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP0_VCA_WR_TOKEN] = REG_DDR2NOC_DP0_NP0_VCA_WR_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP1_VCA_RD_TOKEN] = REG_DDR2NOC_DP0_NP1_VCA_RD_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP1_VCA_WR_TOKEN] = REG_DDR2NOC_DP0_NP1_VCA_WR_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP2_VCA_RD_TOKEN] = REG_DDR2NOC_DP0_NP2_VCA_RD_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP2_VCA_WR_TOKEN] = REG_DDR2NOC_DP0_NP2_VCA_WR_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP3_VCA_RD_TOKEN] = REG_DDR2NOC_DP0_NP3_VCA_RD_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP3_VCA_WR_TOKEN] = REG_DDR2NOC_DP0_NP3_VCA_WR_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP0_VCA_RD_TOKEN] = REG_DDR2NOC_DP1_NP0_VCA_RD_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP0_VCA_WR_TOKEN] = REG_DDR2NOC_DP1_NP0_VCA_WR_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP1_VCA_RD_TOKEN] = REG_DDR2NOC_DP1_NP1_VCA_RD_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP1_VCA_WR_TOKEN] = REG_DDR2NOC_DP1_NP1_VCA_WR_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP2_VCA_RD_TOKEN] = REG_DDR2NOC_DP1_NP2_VCA_RD_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP2_VCA_WR_TOKEN] = REG_DDR2NOC_DP1_NP2_VCA_WR_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP3_VCA_RD_TOKEN] = REG_DDR2NOC_DP1_NP3_VCA_RD_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP3_VCA_WR_TOKEN] = REG_DDR2NOC_DP1_NP3_VCA_WR_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP0] = REG_DDR2NOC_PRI_NP0;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP1] = REG_DDR2NOC_PRI_NP1;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP2] = REG_DDR2NOC_PRI_NP2;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP3] = REG_DDR2NOC_PRI_NP3;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP0] = REG_DDR2NOC_RD_VC_MAP_NP0;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP1] = REG_DDR2NOC_RD_VC_MAP_NP1;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP2] = REG_DDR2NOC_RD_VC_MAP_NP2;
  ATTR[`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP3] = REG_DDR2NOC_RD_VC_MAP_NP3;
  ATTR[`NOC2_XBR4X2__REG_DST_ID_P0] = REG_DST_ID_P0;
  ATTR[`NOC2_XBR4X2__REG_DST_ID_P1] = REG_DST_ID_P1;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP0_DP0_VCA_TOKEN] = REG_NOC2DDR_NP0_DP0_VCA_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP0_DP1_VCA_TOKEN] = REG_NOC2DDR_NP0_DP1_VCA_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP1_DP0_VCA_TOKEN] = REG_NOC2DDR_NP1_DP0_VCA_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP1_DP1_VCA_TOKEN] = REG_NOC2DDR_NP1_DP1_VCA_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP2_DP0_VCA_TOKEN] = REG_NOC2DDR_NP2_DP0_VCA_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP2_DP1_VCA_TOKEN] = REG_NOC2DDR_NP2_DP1_VCA_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP3_DP0_VCA_TOKEN] = REG_NOC2DDR_NP3_DP0_VCA_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP3_DP1_VCA_TOKEN] = REG_NOC2DDR_NP3_DP1_VCA_TOKEN;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_PRI_DP0] = REG_NOC2DDR_PRI_DP0;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_PRI_DP1] = REG_NOC2DDR_PRI_DP1;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_RD_CH_IDX_MAP_DP0] = REG_NOC2DDR_RD_CH_IDX_MAP_DP0;
  ATTR[`NOC2_XBR4X2__REG_NOC2DDR_RD_CH_IDX_MAP_DP1] = REG_NOC2DDR_RD_CH_IDX_MAP_DP1;
  ATTR[`NOC2_XBR4X2__REG_NOC_CTL] = REG_NOC_CTL;
end

always @(trig_attr) begin
  REG_DDR2NOC_DP0_NP0_VCA_RD_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP0_VCA_RD_TOKEN];
  REG_DDR2NOC_DP0_NP0_VCA_WR_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP0_VCA_WR_TOKEN];
  REG_DDR2NOC_DP0_NP1_VCA_RD_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP1_VCA_RD_TOKEN];
  REG_DDR2NOC_DP0_NP1_VCA_WR_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP1_VCA_WR_TOKEN];
  REG_DDR2NOC_DP0_NP2_VCA_RD_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP2_VCA_RD_TOKEN];
  REG_DDR2NOC_DP0_NP2_VCA_WR_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP2_VCA_WR_TOKEN];
  REG_DDR2NOC_DP0_NP3_VCA_RD_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP3_VCA_RD_TOKEN];
  REG_DDR2NOC_DP0_NP3_VCA_WR_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP0_NP3_VCA_WR_TOKEN];
  REG_DDR2NOC_DP1_NP0_VCA_RD_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP0_VCA_RD_TOKEN];
  REG_DDR2NOC_DP1_NP0_VCA_WR_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP0_VCA_WR_TOKEN];
  REG_DDR2NOC_DP1_NP1_VCA_RD_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP1_VCA_RD_TOKEN];
  REG_DDR2NOC_DP1_NP1_VCA_WR_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP1_VCA_WR_TOKEN];
  REG_DDR2NOC_DP1_NP2_VCA_RD_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP2_VCA_RD_TOKEN];
  REG_DDR2NOC_DP1_NP2_VCA_WR_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP2_VCA_WR_TOKEN];
  REG_DDR2NOC_DP1_NP3_VCA_RD_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP3_VCA_RD_TOKEN];
  REG_DDR2NOC_DP1_NP3_VCA_WR_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_DP1_NP3_VCA_WR_TOKEN];
  REG_DDR2NOC_PRI_NP0_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP0];
  REG_DDR2NOC_PRI_NP1_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP1];
  REG_DDR2NOC_PRI_NP2_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP2];
  REG_DDR2NOC_PRI_NP3_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_PRI_NP3];
  REG_DDR2NOC_RD_VC_MAP_NP0_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP0];
  REG_DDR2NOC_RD_VC_MAP_NP1_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP1];
  REG_DDR2NOC_RD_VC_MAP_NP2_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP2];
  REG_DDR2NOC_RD_VC_MAP_NP3_REG = ATTR[`NOC2_XBR4X2__REG_DDR2NOC_RD_VC_MAP_NP3];
  REG_DST_ID_P0_REG = ATTR[`NOC2_XBR4X2__REG_DST_ID_P0];
  REG_DST_ID_P1_REG = ATTR[`NOC2_XBR4X2__REG_DST_ID_P1];
  REG_NOC2DDR_NP0_DP0_VCA_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP0_DP0_VCA_TOKEN];
  REG_NOC2DDR_NP0_DP1_VCA_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP0_DP1_VCA_TOKEN];
  REG_NOC2DDR_NP1_DP0_VCA_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP1_DP0_VCA_TOKEN];
  REG_NOC2DDR_NP1_DP1_VCA_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP1_DP1_VCA_TOKEN];
  REG_NOC2DDR_NP2_DP0_VCA_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP2_DP0_VCA_TOKEN];
  REG_NOC2DDR_NP2_DP1_VCA_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP2_DP1_VCA_TOKEN];
  REG_NOC2DDR_NP3_DP0_VCA_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP3_DP0_VCA_TOKEN];
  REG_NOC2DDR_NP3_DP1_VCA_TOKEN_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_NP3_DP1_VCA_TOKEN];
  REG_NOC2DDR_PRI_DP0_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_PRI_DP0];
  REG_NOC2DDR_PRI_DP1_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_PRI_DP1];
  REG_NOC2DDR_RD_CH_IDX_MAP_DP0_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_RD_CH_IDX_MAP_DP0];
  REG_NOC2DDR_RD_CH_IDX_MAP_DP1_REG = ATTR[`NOC2_XBR4X2__REG_NOC2DDR_RD_CH_IDX_MAP_DP1];
  REG_NOC_CTL_REG = ATTR[`NOC2_XBR4X2__REG_NOC_CTL];
end

// procedures to override, read attribute values

task write_attr;
  input  [`NOC2_XBR4X2_ADDR_SZ-1:0] addr;
  input  [`NOC2_XBR4X2_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`NOC2_XBR4X2_DATA_SZ-1:0] read_attr;
  input  [`NOC2_XBR4X2_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
