`include "B_NOC_NPS4_defines.vh"

reg [`NOC_NPS4_DATA_SZ-1:0] ATTR [0:`NOC_NPS4_ADDR_N-1];
reg [`NOC_NPS4__REG_DST_ID_P0_SZ-1:0] REG_DST_ID_P0_REG = REG_DST_ID_P0;
reg [`NOC_NPS4__REG_DST_ID_P1_SZ-1:0] REG_DST_ID_P1_REG = REG_DST_ID_P1;
reg [`NOC_NPS4__REG_DST_ID_P2_SZ-1:0] REG_DST_ID_P2_REG = REG_DST_ID_P2;
reg [`NOC_NPS4__REG_DST_ID_P3_SZ-1:0] REG_DST_ID_P3_REG = REG_DST_ID_P3;
reg [`NOC_NPS4__REG_HBM2NOC_P0_P0_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P0_P0_VCA_TOKEN_REG = REG_HBM2NOC_P0_P0_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P0_P1_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P0_P1_VCA_TOKEN_REG = REG_HBM2NOC_P0_P1_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P0_P2_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P0_P2_VCA_TOKEN_REG = REG_HBM2NOC_P0_P2_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P0_P3_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P0_P3_VCA_TOKEN_REG = REG_HBM2NOC_P0_P3_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P1_P0_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P1_P0_VCA_TOKEN_REG = REG_HBM2NOC_P1_P0_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P1_P1_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P1_P1_VCA_TOKEN_REG = REG_HBM2NOC_P1_P1_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P1_P2_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P1_P2_VCA_TOKEN_REG = REG_HBM2NOC_P1_P2_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P1_P3_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P1_P3_VCA_TOKEN_REG = REG_HBM2NOC_P1_P3_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P2_P0_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P2_P0_VCA_TOKEN_REG = REG_HBM2NOC_P2_P0_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P2_P1_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P2_P1_VCA_TOKEN_REG = REG_HBM2NOC_P2_P1_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P2_P2_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P2_P2_VCA_TOKEN_REG = REG_HBM2NOC_P2_P2_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P2_P3_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P2_P3_VCA_TOKEN_REG = REG_HBM2NOC_P2_P3_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P3_P0_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P3_P0_VCA_TOKEN_REG = REG_HBM2NOC_P3_P0_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P3_P1_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P3_P1_VCA_TOKEN_REG = REG_HBM2NOC_P3_P1_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P3_P2_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P3_P2_VCA_TOKEN_REG = REG_HBM2NOC_P3_P2_VCA_TOKEN;
reg [`NOC_NPS4__REG_HBM2NOC_P3_P3_VCA_TOKEN_SZ-1:0] REG_HBM2NOC_P3_P3_VCA_TOKEN_REG = REG_HBM2NOC_P3_P3_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P0_P0_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P0_P0_VCA_TOKEN_REG = REG_NOC2HBM_P0_P0_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P0_P1_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P0_P1_VCA_TOKEN_REG = REG_NOC2HBM_P0_P1_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P0_P2_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P0_P2_VCA_TOKEN_REG = REG_NOC2HBM_P0_P2_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P0_P3_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P0_P3_VCA_TOKEN_REG = REG_NOC2HBM_P0_P3_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P1_P0_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P1_P0_VCA_TOKEN_REG = REG_NOC2HBM_P1_P0_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P1_P1_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P1_P1_VCA_TOKEN_REG = REG_NOC2HBM_P1_P1_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P1_P2_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P1_P2_VCA_TOKEN_REG = REG_NOC2HBM_P1_P2_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P1_P3_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P1_P3_VCA_TOKEN_REG = REG_NOC2HBM_P1_P3_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P2_P0_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P2_P0_VCA_TOKEN_REG = REG_NOC2HBM_P2_P0_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P2_P1_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P2_P1_VCA_TOKEN_REG = REG_NOC2HBM_P2_P1_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P2_P2_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P2_P2_VCA_TOKEN_REG = REG_NOC2HBM_P2_P2_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P2_P3_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P2_P3_VCA_TOKEN_REG = REG_NOC2HBM_P2_P3_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P3_P0_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P3_P0_VCA_TOKEN_REG = REG_NOC2HBM_P3_P0_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P3_P1_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P3_P1_VCA_TOKEN_REG = REG_NOC2HBM_P3_P1_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P3_P2_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P3_P2_VCA_TOKEN_REG = REG_NOC2HBM_P3_P2_VCA_TOKEN;
reg [`NOC_NPS4__REG_NOC2HBM_P3_P3_VCA_TOKEN_SZ-1:0] REG_NOC2HBM_P3_P3_VCA_TOKEN_REG = REG_NOC2HBM_P3_P3_VCA_TOKEN;
reg REG_NOC_CTL_REG = REG_NOC_CTL;

initial begin
  ATTR[`NOC_NPS4__REG_DST_ID_P0] = REG_DST_ID_P0;
  ATTR[`NOC_NPS4__REG_DST_ID_P1] = REG_DST_ID_P1;
  ATTR[`NOC_NPS4__REG_DST_ID_P2] = REG_DST_ID_P2;
  ATTR[`NOC_NPS4__REG_DST_ID_P3] = REG_DST_ID_P3;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P0_P0_VCA_TOKEN] = REG_HBM2NOC_P0_P0_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P0_P1_VCA_TOKEN] = REG_HBM2NOC_P0_P1_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P0_P2_VCA_TOKEN] = REG_HBM2NOC_P0_P2_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P0_P3_VCA_TOKEN] = REG_HBM2NOC_P0_P3_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P1_P0_VCA_TOKEN] = REG_HBM2NOC_P1_P0_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P1_P1_VCA_TOKEN] = REG_HBM2NOC_P1_P1_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P1_P2_VCA_TOKEN] = REG_HBM2NOC_P1_P2_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P1_P3_VCA_TOKEN] = REG_HBM2NOC_P1_P3_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P2_P0_VCA_TOKEN] = REG_HBM2NOC_P2_P0_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P2_P1_VCA_TOKEN] = REG_HBM2NOC_P2_P1_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P2_P2_VCA_TOKEN] = REG_HBM2NOC_P2_P2_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P2_P3_VCA_TOKEN] = REG_HBM2NOC_P2_P3_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P3_P0_VCA_TOKEN] = REG_HBM2NOC_P3_P0_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P3_P1_VCA_TOKEN] = REG_HBM2NOC_P3_P1_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P3_P2_VCA_TOKEN] = REG_HBM2NOC_P3_P2_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_HBM2NOC_P3_P3_VCA_TOKEN] = REG_HBM2NOC_P3_P3_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P0_P0_VCA_TOKEN] = REG_NOC2HBM_P0_P0_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P0_P1_VCA_TOKEN] = REG_NOC2HBM_P0_P1_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P0_P2_VCA_TOKEN] = REG_NOC2HBM_P0_P2_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P0_P3_VCA_TOKEN] = REG_NOC2HBM_P0_P3_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P1_P0_VCA_TOKEN] = REG_NOC2HBM_P1_P0_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P1_P1_VCA_TOKEN] = REG_NOC2HBM_P1_P1_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P1_P2_VCA_TOKEN] = REG_NOC2HBM_P1_P2_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P1_P3_VCA_TOKEN] = REG_NOC2HBM_P1_P3_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P2_P0_VCA_TOKEN] = REG_NOC2HBM_P2_P0_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P2_P1_VCA_TOKEN] = REG_NOC2HBM_P2_P1_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P2_P2_VCA_TOKEN] = REG_NOC2HBM_P2_P2_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P2_P3_VCA_TOKEN] = REG_NOC2HBM_P2_P3_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P3_P0_VCA_TOKEN] = REG_NOC2HBM_P3_P0_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P3_P1_VCA_TOKEN] = REG_NOC2HBM_P3_P1_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P3_P2_VCA_TOKEN] = REG_NOC2HBM_P3_P2_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC2HBM_P3_P3_VCA_TOKEN] = REG_NOC2HBM_P3_P3_VCA_TOKEN;
  ATTR[`NOC_NPS4__REG_NOC_CTL] = REG_NOC_CTL;
end

always @(trig_attr) begin
  REG_DST_ID_P0_REG = ATTR[`NOC_NPS4__REG_DST_ID_P0];
  REG_DST_ID_P1_REG = ATTR[`NOC_NPS4__REG_DST_ID_P1];
  REG_DST_ID_P2_REG = ATTR[`NOC_NPS4__REG_DST_ID_P2];
  REG_DST_ID_P3_REG = ATTR[`NOC_NPS4__REG_DST_ID_P3];
  REG_HBM2NOC_P0_P0_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P0_P0_VCA_TOKEN];
  REG_HBM2NOC_P0_P1_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P0_P1_VCA_TOKEN];
  REG_HBM2NOC_P0_P2_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P0_P2_VCA_TOKEN];
  REG_HBM2NOC_P0_P3_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P0_P3_VCA_TOKEN];
  REG_HBM2NOC_P1_P0_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P1_P0_VCA_TOKEN];
  REG_HBM2NOC_P1_P1_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P1_P1_VCA_TOKEN];
  REG_HBM2NOC_P1_P2_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P1_P2_VCA_TOKEN];
  REG_HBM2NOC_P1_P3_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P1_P3_VCA_TOKEN];
  REG_HBM2NOC_P2_P0_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P2_P0_VCA_TOKEN];
  REG_HBM2NOC_P2_P1_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P2_P1_VCA_TOKEN];
  REG_HBM2NOC_P2_P2_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P2_P2_VCA_TOKEN];
  REG_HBM2NOC_P2_P3_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P2_P3_VCA_TOKEN];
  REG_HBM2NOC_P3_P0_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P3_P0_VCA_TOKEN];
  REG_HBM2NOC_P3_P1_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P3_P1_VCA_TOKEN];
  REG_HBM2NOC_P3_P2_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P3_P2_VCA_TOKEN];
  REG_HBM2NOC_P3_P3_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_HBM2NOC_P3_P3_VCA_TOKEN];
  REG_NOC2HBM_P0_P0_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P0_P0_VCA_TOKEN];
  REG_NOC2HBM_P0_P1_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P0_P1_VCA_TOKEN];
  REG_NOC2HBM_P0_P2_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P0_P2_VCA_TOKEN];
  REG_NOC2HBM_P0_P3_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P0_P3_VCA_TOKEN];
  REG_NOC2HBM_P1_P0_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P1_P0_VCA_TOKEN];
  REG_NOC2HBM_P1_P1_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P1_P1_VCA_TOKEN];
  REG_NOC2HBM_P1_P2_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P1_P2_VCA_TOKEN];
  REG_NOC2HBM_P1_P3_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P1_P3_VCA_TOKEN];
  REG_NOC2HBM_P2_P0_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P2_P0_VCA_TOKEN];
  REG_NOC2HBM_P2_P1_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P2_P1_VCA_TOKEN];
  REG_NOC2HBM_P2_P2_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P2_P2_VCA_TOKEN];
  REG_NOC2HBM_P2_P3_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P2_P3_VCA_TOKEN];
  REG_NOC2HBM_P3_P0_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P3_P0_VCA_TOKEN];
  REG_NOC2HBM_P3_P1_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P3_P1_VCA_TOKEN];
  REG_NOC2HBM_P3_P2_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P3_P2_VCA_TOKEN];
  REG_NOC2HBM_P3_P3_VCA_TOKEN_REG = ATTR[`NOC_NPS4__REG_NOC2HBM_P3_P3_VCA_TOKEN];
  REG_NOC_CTL_REG = ATTR[`NOC_NPS4__REG_NOC_CTL];
end

// procedures to override, read attribute values

task write_attr;
  input  [`NOC_NPS4_ADDR_SZ-1:0] addr;
  input  [`NOC_NPS4_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`NOC_NPS4_DATA_SZ-1:0] read_attr;
  input  [`NOC_NPS4_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
