`include "B_NOC_NSU512_defines.vh"

reg [`NOC_NSU512_DATA_SZ-1:0] ATTR [0:`NOC_NSU512_ADDR_N-1];
reg [`NOC_NSU512__REG_AXI_LOOPBACK_SZ-1:0] REG_AXI_LOOPBACK_REG = REG_AXI_LOOPBACK;
reg [`NOC_NSU512__REG_COMP_ID_INDEX0_SZ-1:0] REG_COMP_ID_INDEX0_REG = REG_COMP_ID_INDEX0;
reg [`NOC_NSU512__REG_COMP_ID_INDEX1_SZ-1:0] REG_COMP_ID_INDEX1_REG = REG_COMP_ID_INDEX1;
reg REG_COMP_ID_MODE_REG = REG_COMP_ID_MODE;
reg REG_DISABLE_EX_MON_REG = REG_DISABLE_EX_MON;
reg [`NOC_NSU512__REG_DWIDTH_SZ-1:0] REG_DWIDTH_REG = REG_DWIDTH;
reg REG_ECC_CHK_EN_REG = REG_ECC_CHK_EN;
reg [`NOC_NSU512__REG_FIXED_COMP_ID_SZ-1:0] REG_FIXED_COMP_ID_REG = REG_FIXED_COMP_ID;
reg [`NOC_NSU512__REG_MODE_SELECT_SZ-1:0] REG_MODE_SELECT_REG = REG_MODE_SELECT;
reg REG_ODISABLE_AXI_RESP_REG = REG_ODISABLE_AXI_RESP;
reg [`NOC_NSU512__REG_OUTSTANDING_RD_TXN_SZ-1:0] REG_OUTSTANDING_RD_TXN_REG = REG_OUTSTANDING_RD_TXN;
reg [`NOC_NSU512__REG_OUTSTANDING_WR_TXN_SZ-1:0] REG_OUTSTANDING_WR_TXN_REG = REG_OUTSTANDING_WR_TXN;
reg [`NOC_NSU512__REG_PAR_CHK_SZ-1:0] REG_PAR_CHK_REG = REG_PAR_CHK;
reg [`NOC_NSU512__REG_RDTRK_VCA_TOKEN0_SZ-1:0] REG_RDTRK_VCA_TOKEN0_REG = REG_RDTRK_VCA_TOKEN0;
reg [`NOC_NSU512__REG_RDTRK_VCA_TOKEN1_SZ-1:0] REG_RDTRK_VCA_TOKEN1_REG = REG_RDTRK_VCA_TOKEN1;
reg [`NOC_NSU512__REG_RD_REQ_VC_MAP0_SZ-1:0] REG_RD_REQ_VC_MAP0_REG = REG_RD_REQ_VC_MAP0;
reg [`NOC_NSU512__REG_RD_REQ_VC_MAP1_SZ-1:0] REG_RD_REQ_VC_MAP1_REG = REG_RD_REQ_VC_MAP1;
reg [`NOC_NSU512__REG_RD_RESP_VC_MAP0_SZ-1:0] REG_RD_RESP_VC_MAP0_REG = REG_RD_RESP_VC_MAP0;
reg [`NOC_NSU512__REG_RD_RESP_VC_MAP1_SZ-1:0] REG_RD_RESP_VC_MAP1_REG = REG_RD_RESP_VC_MAP1;
reg [`NOC_NSU512__REG_RD_VCA_TOKEN0_SZ-1:0] REG_RD_VCA_TOKEN0_REG = REG_RD_VCA_TOKEN0;
reg [`NOC_NSU512__REG_RD_VCA_TOKEN1_SZ-1:0] REG_RD_VCA_TOKEN1_REG = REG_RD_VCA_TOKEN1;
reg [`NOC_NSU512__REG_SRC_SZ-1:0] REG_SRC_REG = REG_SRC;
reg [`NOC_NSU512__REG_TBASE_AXI_TIMEOUT_SZ-1:0] REG_TBASE_AXI_TIMEOUT_REG = REG_TBASE_AXI_TIMEOUT;
reg [`NOC_NSU512__REG_TBASE_TRK_TIMEOUT_SZ-1:0] REG_TBASE_TRK_TIMEOUT_REG = REG_TBASE_TRK_TIMEOUT;
reg [`NOC_NSU512__REG_VMAP_OUT_RD_TOKEN0_SZ-1:0] REG_VMAP_OUT_RD_TOKEN0_REG = REG_VMAP_OUT_RD_TOKEN0;
reg [`NOC_NSU512__REG_VMAP_OUT_RD_TOKEN1_SZ-1:0] REG_VMAP_OUT_RD_TOKEN1_REG = REG_VMAP_OUT_RD_TOKEN1;
reg [`NOC_NSU512__REG_VMAP_OUT_WR_TOKEN0_SZ-1:0] REG_VMAP_OUT_WR_TOKEN0_REG = REG_VMAP_OUT_WR_TOKEN0;
reg [`NOC_NSU512__REG_VMAP_OUT_WR_TOKEN1_SZ-1:0] REG_VMAP_OUT_WR_TOKEN1_REG = REG_VMAP_OUT_WR_TOKEN1;
reg [`NOC_NSU512__REG_WRTRK_VCA_TOKEN0_SZ-1:0] REG_WRTRK_VCA_TOKEN0_REG = REG_WRTRK_VCA_TOKEN0;
reg [`NOC_NSU512__REG_WRTRK_VCA_TOKEN1_SZ-1:0] REG_WRTRK_VCA_TOKEN1_REG = REG_WRTRK_VCA_TOKEN1;
reg [`NOC_NSU512__REG_WR_REQ_VC_MAP0_SZ-1:0] REG_WR_REQ_VC_MAP0_REG = REG_WR_REQ_VC_MAP0;
reg [`NOC_NSU512__REG_WR_REQ_VC_MAP1_SZ-1:0] REG_WR_REQ_VC_MAP1_REG = REG_WR_REQ_VC_MAP1;
reg [`NOC_NSU512__REG_WR_RESP_VC_MAP0_SZ-1:0] REG_WR_RESP_VC_MAP0_REG = REG_WR_RESP_VC_MAP0;
reg [`NOC_NSU512__REG_WR_RESP_VC_MAP1_SZ-1:0] REG_WR_RESP_VC_MAP1_REG = REG_WR_RESP_VC_MAP1;
reg [`NOC_NSU512__REG_WR_VCA_TOKEN0_SZ-1:0] REG_WR_VCA_TOKEN0_REG = REG_WR_VCA_TOKEN0;
reg [`NOC_NSU512__REG_WR_VCA_TOKEN1_SZ-1:0] REG_WR_VCA_TOKEN1_REG = REG_WR_VCA_TOKEN1;

initial begin
  ATTR[`NOC_NSU512__REG_AXI_LOOPBACK] = REG_AXI_LOOPBACK;
  ATTR[`NOC_NSU512__REG_COMP_ID_INDEX0] = REG_COMP_ID_INDEX0;
  ATTR[`NOC_NSU512__REG_COMP_ID_INDEX1] = REG_COMP_ID_INDEX1;
  ATTR[`NOC_NSU512__REG_COMP_ID_MODE] = REG_COMP_ID_MODE;
  ATTR[`NOC_NSU512__REG_DISABLE_EX_MON] = REG_DISABLE_EX_MON;
  ATTR[`NOC_NSU512__REG_DWIDTH] = REG_DWIDTH;
  ATTR[`NOC_NSU512__REG_ECC_CHK_EN] = REG_ECC_CHK_EN;
  ATTR[`NOC_NSU512__REG_FIXED_COMP_ID] = REG_FIXED_COMP_ID;
  ATTR[`NOC_NSU512__REG_MODE_SELECT] = REG_MODE_SELECT;
  ATTR[`NOC_NSU512__REG_ODISABLE_AXI_RESP] = REG_ODISABLE_AXI_RESP;
  ATTR[`NOC_NSU512__REG_OUTSTANDING_RD_TXN] = REG_OUTSTANDING_RD_TXN;
  ATTR[`NOC_NSU512__REG_OUTSTANDING_WR_TXN] = REG_OUTSTANDING_WR_TXN;
  ATTR[`NOC_NSU512__REG_PAR_CHK] = REG_PAR_CHK;
  ATTR[`NOC_NSU512__REG_RDTRK_VCA_TOKEN0] = REG_RDTRK_VCA_TOKEN0;
  ATTR[`NOC_NSU512__REG_RDTRK_VCA_TOKEN1] = REG_RDTRK_VCA_TOKEN1;
  ATTR[`NOC_NSU512__REG_RD_REQ_VC_MAP0] = REG_RD_REQ_VC_MAP0;
  ATTR[`NOC_NSU512__REG_RD_REQ_VC_MAP1] = REG_RD_REQ_VC_MAP1;
  ATTR[`NOC_NSU512__REG_RD_RESP_VC_MAP0] = REG_RD_RESP_VC_MAP0;
  ATTR[`NOC_NSU512__REG_RD_RESP_VC_MAP1] = REG_RD_RESP_VC_MAP1;
  ATTR[`NOC_NSU512__REG_RD_VCA_TOKEN0] = REG_RD_VCA_TOKEN0;
  ATTR[`NOC_NSU512__REG_RD_VCA_TOKEN1] = REG_RD_VCA_TOKEN1;
  ATTR[`NOC_NSU512__REG_SRC] = REG_SRC;
  ATTR[`NOC_NSU512__REG_TBASE_AXI_TIMEOUT] = REG_TBASE_AXI_TIMEOUT;
  ATTR[`NOC_NSU512__REG_TBASE_TRK_TIMEOUT] = REG_TBASE_TRK_TIMEOUT;
  ATTR[`NOC_NSU512__REG_VMAP_OUT_RD_TOKEN0] = REG_VMAP_OUT_RD_TOKEN0;
  ATTR[`NOC_NSU512__REG_VMAP_OUT_RD_TOKEN1] = REG_VMAP_OUT_RD_TOKEN1;
  ATTR[`NOC_NSU512__REG_VMAP_OUT_WR_TOKEN0] = REG_VMAP_OUT_WR_TOKEN0;
  ATTR[`NOC_NSU512__REG_VMAP_OUT_WR_TOKEN1] = REG_VMAP_OUT_WR_TOKEN1;
  ATTR[`NOC_NSU512__REG_WRTRK_VCA_TOKEN0] = REG_WRTRK_VCA_TOKEN0;
  ATTR[`NOC_NSU512__REG_WRTRK_VCA_TOKEN1] = REG_WRTRK_VCA_TOKEN1;
  ATTR[`NOC_NSU512__REG_WR_REQ_VC_MAP0] = REG_WR_REQ_VC_MAP0;
  ATTR[`NOC_NSU512__REG_WR_REQ_VC_MAP1] = REG_WR_REQ_VC_MAP1;
  ATTR[`NOC_NSU512__REG_WR_RESP_VC_MAP0] = REG_WR_RESP_VC_MAP0;
  ATTR[`NOC_NSU512__REG_WR_RESP_VC_MAP1] = REG_WR_RESP_VC_MAP1;
  ATTR[`NOC_NSU512__REG_WR_VCA_TOKEN0] = REG_WR_VCA_TOKEN0;
  ATTR[`NOC_NSU512__REG_WR_VCA_TOKEN1] = REG_WR_VCA_TOKEN1;
end

always @(trig_attr) begin
  REG_AXI_LOOPBACK_REG = ATTR[`NOC_NSU512__REG_AXI_LOOPBACK];
  REG_COMP_ID_INDEX0_REG = ATTR[`NOC_NSU512__REG_COMP_ID_INDEX0];
  REG_COMP_ID_INDEX1_REG = ATTR[`NOC_NSU512__REG_COMP_ID_INDEX1];
  REG_COMP_ID_MODE_REG = ATTR[`NOC_NSU512__REG_COMP_ID_MODE];
  REG_DISABLE_EX_MON_REG = ATTR[`NOC_NSU512__REG_DISABLE_EX_MON];
  REG_DWIDTH_REG = ATTR[`NOC_NSU512__REG_DWIDTH];
  REG_ECC_CHK_EN_REG = ATTR[`NOC_NSU512__REG_ECC_CHK_EN];
  REG_FIXED_COMP_ID_REG = ATTR[`NOC_NSU512__REG_FIXED_COMP_ID];
  REG_MODE_SELECT_REG = ATTR[`NOC_NSU512__REG_MODE_SELECT];
  REG_ODISABLE_AXI_RESP_REG = ATTR[`NOC_NSU512__REG_ODISABLE_AXI_RESP];
  REG_OUTSTANDING_RD_TXN_REG = ATTR[`NOC_NSU512__REG_OUTSTANDING_RD_TXN];
  REG_OUTSTANDING_WR_TXN_REG = ATTR[`NOC_NSU512__REG_OUTSTANDING_WR_TXN];
  REG_PAR_CHK_REG = ATTR[`NOC_NSU512__REG_PAR_CHK];
  REG_RDTRK_VCA_TOKEN0_REG = ATTR[`NOC_NSU512__REG_RDTRK_VCA_TOKEN0];
  REG_RDTRK_VCA_TOKEN1_REG = ATTR[`NOC_NSU512__REG_RDTRK_VCA_TOKEN1];
  REG_RD_REQ_VC_MAP0_REG = ATTR[`NOC_NSU512__REG_RD_REQ_VC_MAP0];
  REG_RD_REQ_VC_MAP1_REG = ATTR[`NOC_NSU512__REG_RD_REQ_VC_MAP1];
  REG_RD_RESP_VC_MAP0_REG = ATTR[`NOC_NSU512__REG_RD_RESP_VC_MAP0];
  REG_RD_RESP_VC_MAP1_REG = ATTR[`NOC_NSU512__REG_RD_RESP_VC_MAP1];
  REG_RD_VCA_TOKEN0_REG = ATTR[`NOC_NSU512__REG_RD_VCA_TOKEN0];
  REG_RD_VCA_TOKEN1_REG = ATTR[`NOC_NSU512__REG_RD_VCA_TOKEN1];
  REG_SRC_REG = ATTR[`NOC_NSU512__REG_SRC];
  REG_TBASE_AXI_TIMEOUT_REG = ATTR[`NOC_NSU512__REG_TBASE_AXI_TIMEOUT];
  REG_TBASE_TRK_TIMEOUT_REG = ATTR[`NOC_NSU512__REG_TBASE_TRK_TIMEOUT];
  REG_VMAP_OUT_RD_TOKEN0_REG = ATTR[`NOC_NSU512__REG_VMAP_OUT_RD_TOKEN0];
  REG_VMAP_OUT_RD_TOKEN1_REG = ATTR[`NOC_NSU512__REG_VMAP_OUT_RD_TOKEN1];
  REG_VMAP_OUT_WR_TOKEN0_REG = ATTR[`NOC_NSU512__REG_VMAP_OUT_WR_TOKEN0];
  REG_VMAP_OUT_WR_TOKEN1_REG = ATTR[`NOC_NSU512__REG_VMAP_OUT_WR_TOKEN1];
  REG_WRTRK_VCA_TOKEN0_REG = ATTR[`NOC_NSU512__REG_WRTRK_VCA_TOKEN0];
  REG_WRTRK_VCA_TOKEN1_REG = ATTR[`NOC_NSU512__REG_WRTRK_VCA_TOKEN1];
  REG_WR_REQ_VC_MAP0_REG = ATTR[`NOC_NSU512__REG_WR_REQ_VC_MAP0];
  REG_WR_REQ_VC_MAP1_REG = ATTR[`NOC_NSU512__REG_WR_REQ_VC_MAP1];
  REG_WR_RESP_VC_MAP0_REG = ATTR[`NOC_NSU512__REG_WR_RESP_VC_MAP0];
  REG_WR_RESP_VC_MAP1_REG = ATTR[`NOC_NSU512__REG_WR_RESP_VC_MAP1];
  REG_WR_VCA_TOKEN0_REG = ATTR[`NOC_NSU512__REG_WR_VCA_TOKEN0];
  REG_WR_VCA_TOKEN1_REG = ATTR[`NOC_NSU512__REG_WR_VCA_TOKEN1];
end

// procedures to override, read attribute values

task write_attr;
  input  [`NOC_NSU512_ADDR_SZ-1:0] addr;
  input  [`NOC_NSU512_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`NOC_NSU512_DATA_SZ-1:0] read_attr;
  input  [`NOC_NSU512_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
