`include "B_NOC_NIDB_defines.vh"

reg [`NOC_NIDB_DATA_SZ-1:0] ATTR [0:`NOC_NIDB_ADDR_N-1];
reg [`NOC_NIDB__REG_ADDR_REMAP0_SZ-1:0] REG_ADDR_REMAP0_REG = REG_ADDR_REMAP0;
reg [`NOC_NIDB__REG_ADDR_REMAP1_SZ-1:0] REG_ADDR_REMAP1_REG = REG_ADDR_REMAP1;
reg [`NOC_NIDB__REG_ADDR_REMAP_MASK0_SZ-1:0] REG_ADDR_REMAP_MASK0_REG = REG_ADDR_REMAP_MASK0;
reg [`NOC_NIDB__REG_ADDR_REMAP_MASK1_SZ-1:0] REG_ADDR_REMAP_MASK1_REG = REG_ADDR_REMAP_MASK1;
reg [`NOC_NIDB__REG_BYPASS_CNTL_SZ-1:0] REG_BYPASS_CNTL_REG = REG_BYPASS_CNTL;
reg [`NOC_NIDB__REG_DCC_CNTR_SZ-1:0] REG_DCC_CNTR_REG = REG_DCC_CNTR;
reg [`NOC_NIDB__REG_ECC_CHK_EN_SZ-1:0] REG_ECC_CHK_EN_REG = REG_ECC_CHK_EN;
reg [`NOC_NIDB__REG_ERR_PKT_DROP_DIS_SZ-1:0] REG_ERR_PKT_DROP_DIS_REG = REG_ERR_PKT_DROP_DIS;
reg [`NOC_NIDB__REG_IO_CHAR_EN_SZ-1:0] REG_IO_CHAR_EN_REG = REG_IO_CHAR_EN;
reg [`NOC_NIDB__REG_IO_CHAR_OUTPUT_MUX_SEL_SZ-1:0] REG_IO_CHAR_OUTPUT_MUX_SEL_REG = REG_IO_CHAR_OUTPUT_MUX_SEL;
reg [`NOC_NIDB__REG_IO_CNTRL_SZ-1:0] REG_IO_CNTRL_REG = REG_IO_CNTRL;
reg [`NOC_NIDB__REG_LOOPBACK_CNTL_SZ-1:0] REG_LOOPBACK_CNTL_REG = REG_LOOPBACK_CNTL;
reg [`NOC_NIDB__REG_NOC_CTL_SZ-1:0] REG_NOC_CTL_REG = REG_NOC_CTL;
reg [`NOC_NIDB__REG_P0_0_VCA_TOKEN_SZ-1:0] REG_P0_0_VCA_TOKEN_REG = REG_P0_0_VCA_TOKEN;
reg [`NOC_NIDB__REG_P0_1_VCA_TOKEN_SZ-1:0] REG_P0_1_VCA_TOKEN_REG = REG_P0_1_VCA_TOKEN;
reg [`NOC_NIDB__REG_RX_DELAY_EN_SZ-1:0] REG_RX_DELAY_EN_REG = REG_RX_DELAY_EN;
reg [`NOC_NIDB__REG_RX_DW0_DELAY_SZ-1:0] REG_RX_DW0_DELAY_REG = REG_RX_DW0_DELAY;
reg [`NOC_NIDB__REG_RX_DW1_DELAY_SZ-1:0] REG_RX_DW1_DELAY_REG = REG_RX_DW1_DELAY;
reg [`NOC_NIDB__REG_RX_DW2_DELAY_SZ-1:0] REG_RX_DW2_DELAY_REG = REG_RX_DW2_DELAY;
reg [`NOC_NIDB__REG_RX_DW3_DELAY_SZ-1:0] REG_RX_DW3_DELAY_REG = REG_RX_DW3_DELAY;
reg [`NOC_NIDB__REG_RX_DW4_DELAY_SZ-1:0] REG_RX_DW4_DELAY_REG = REG_RX_DW4_DELAY;
reg [`NOC_NIDB__REG_TX_DCC_DELAY_SZ-1:0] REG_TX_DCC_DELAY_REG = REG_TX_DCC_DELAY;
reg [`NOC_NIDB__REG_VC0_ARPROT_SEL_SZ-1:0] REG_VC0_ARPROT_SEL_REG = REG_VC0_ARPROT_SEL;
reg [`NOC_NIDB__REG_VC0_SMID_SEL_SZ-1:0] REG_VC0_SMID_SEL_REG = REG_VC0_SMID_SEL;
reg [`NOC_NIDB__REG_VC1_AWPROT_SEL_SZ-1:0] REG_VC1_AWPROT_SEL_REG = REG_VC1_AWPROT_SEL;
reg [`NOC_NIDB__REG_VC1_SMID_SEL_SZ-1:0] REG_VC1_SMID_SEL_REG = REG_VC1_SMID_SEL;
reg [`NOC_NIDB__REG_VC4_ARPROT_SEL_SZ-1:0] REG_VC4_ARPROT_SEL_REG = REG_VC4_ARPROT_SEL;
reg [`NOC_NIDB__REG_VC4_SMID_SEL_SZ-1:0] REG_VC4_SMID_SEL_REG = REG_VC4_SMID_SEL;
reg [`NOC_NIDB__REG_VC5_AWPROT_SEL_SZ-1:0] REG_VC5_AWPROT_SEL_REG = REG_VC5_AWPROT_SEL;
reg [`NOC_NIDB__REG_VC5_SMID_SEL_SZ-1:0] REG_VC5_SMID_SEL_REG = REG_VC5_SMID_SEL;

initial begin
  ATTR[`NOC_NIDB__REG_ADDR_REMAP0] = REG_ADDR_REMAP0;
  ATTR[`NOC_NIDB__REG_ADDR_REMAP1] = REG_ADDR_REMAP1;
  ATTR[`NOC_NIDB__REG_ADDR_REMAP_MASK0] = REG_ADDR_REMAP_MASK0;
  ATTR[`NOC_NIDB__REG_ADDR_REMAP_MASK1] = REG_ADDR_REMAP_MASK1;
  ATTR[`NOC_NIDB__REG_BYPASS_CNTL] = REG_BYPASS_CNTL;
  ATTR[`NOC_NIDB__REG_DCC_CNTR] = REG_DCC_CNTR;
  ATTR[`NOC_NIDB__REG_ECC_CHK_EN] = REG_ECC_CHK_EN;
  ATTR[`NOC_NIDB__REG_ERR_PKT_DROP_DIS] = REG_ERR_PKT_DROP_DIS;
  ATTR[`NOC_NIDB__REG_IO_CHAR_EN] = REG_IO_CHAR_EN;
  ATTR[`NOC_NIDB__REG_IO_CHAR_OUTPUT_MUX_SEL] = REG_IO_CHAR_OUTPUT_MUX_SEL;
  ATTR[`NOC_NIDB__REG_IO_CNTRL] = REG_IO_CNTRL;
  ATTR[`NOC_NIDB__REG_LOOPBACK_CNTL] = REG_LOOPBACK_CNTL;
  ATTR[`NOC_NIDB__REG_NOC_CTL] = REG_NOC_CTL;
  ATTR[`NOC_NIDB__REG_P0_0_VCA_TOKEN] = REG_P0_0_VCA_TOKEN;
  ATTR[`NOC_NIDB__REG_P0_1_VCA_TOKEN] = REG_P0_1_VCA_TOKEN;
  ATTR[`NOC_NIDB__REG_RX_DELAY_EN] = REG_RX_DELAY_EN;
  ATTR[`NOC_NIDB__REG_RX_DW0_DELAY] = REG_RX_DW0_DELAY;
  ATTR[`NOC_NIDB__REG_RX_DW1_DELAY] = REG_RX_DW1_DELAY;
  ATTR[`NOC_NIDB__REG_RX_DW2_DELAY] = REG_RX_DW2_DELAY;
  ATTR[`NOC_NIDB__REG_RX_DW3_DELAY] = REG_RX_DW3_DELAY;
  ATTR[`NOC_NIDB__REG_RX_DW4_DELAY] = REG_RX_DW4_DELAY;
  ATTR[`NOC_NIDB__REG_TX_DCC_DELAY] = REG_TX_DCC_DELAY;
  ATTR[`NOC_NIDB__REG_VC0_ARPROT_SEL] = REG_VC0_ARPROT_SEL;
  ATTR[`NOC_NIDB__REG_VC0_SMID_SEL] = REG_VC0_SMID_SEL;
  ATTR[`NOC_NIDB__REG_VC1_AWPROT_SEL] = REG_VC1_AWPROT_SEL;
  ATTR[`NOC_NIDB__REG_VC1_SMID_SEL] = REG_VC1_SMID_SEL;
  ATTR[`NOC_NIDB__REG_VC4_ARPROT_SEL] = REG_VC4_ARPROT_SEL;
  ATTR[`NOC_NIDB__REG_VC4_SMID_SEL] = REG_VC4_SMID_SEL;
  ATTR[`NOC_NIDB__REG_VC5_AWPROT_SEL] = REG_VC5_AWPROT_SEL;
  ATTR[`NOC_NIDB__REG_VC5_SMID_SEL] = REG_VC5_SMID_SEL;
end

always @(trig_attr) begin
  REG_ADDR_REMAP0_REG = ATTR[`NOC_NIDB__REG_ADDR_REMAP0];
  REG_ADDR_REMAP1_REG = ATTR[`NOC_NIDB__REG_ADDR_REMAP1];
  REG_ADDR_REMAP_MASK0_REG = ATTR[`NOC_NIDB__REG_ADDR_REMAP_MASK0];
  REG_ADDR_REMAP_MASK1_REG = ATTR[`NOC_NIDB__REG_ADDR_REMAP_MASK1];
  REG_BYPASS_CNTL_REG = ATTR[`NOC_NIDB__REG_BYPASS_CNTL];
  REG_DCC_CNTR_REG = ATTR[`NOC_NIDB__REG_DCC_CNTR];
  REG_ECC_CHK_EN_REG = ATTR[`NOC_NIDB__REG_ECC_CHK_EN];
  REG_ERR_PKT_DROP_DIS_REG = ATTR[`NOC_NIDB__REG_ERR_PKT_DROP_DIS];
  REG_IO_CHAR_EN_REG = ATTR[`NOC_NIDB__REG_IO_CHAR_EN];
  REG_IO_CHAR_OUTPUT_MUX_SEL_REG = ATTR[`NOC_NIDB__REG_IO_CHAR_OUTPUT_MUX_SEL];
  REG_IO_CNTRL_REG = ATTR[`NOC_NIDB__REG_IO_CNTRL];
  REG_LOOPBACK_CNTL_REG = ATTR[`NOC_NIDB__REG_LOOPBACK_CNTL];
  REG_NOC_CTL_REG = ATTR[`NOC_NIDB__REG_NOC_CTL];
  REG_P0_0_VCA_TOKEN_REG = ATTR[`NOC_NIDB__REG_P0_0_VCA_TOKEN];
  REG_P0_1_VCA_TOKEN_REG = ATTR[`NOC_NIDB__REG_P0_1_VCA_TOKEN];
  REG_RX_DELAY_EN_REG = ATTR[`NOC_NIDB__REG_RX_DELAY_EN];
  REG_RX_DW0_DELAY_REG = ATTR[`NOC_NIDB__REG_RX_DW0_DELAY];
  REG_RX_DW1_DELAY_REG = ATTR[`NOC_NIDB__REG_RX_DW1_DELAY];
  REG_RX_DW2_DELAY_REG = ATTR[`NOC_NIDB__REG_RX_DW2_DELAY];
  REG_RX_DW3_DELAY_REG = ATTR[`NOC_NIDB__REG_RX_DW3_DELAY];
  REG_RX_DW4_DELAY_REG = ATTR[`NOC_NIDB__REG_RX_DW4_DELAY];
  REG_TX_DCC_DELAY_REG = ATTR[`NOC_NIDB__REG_TX_DCC_DELAY];
  REG_VC0_ARPROT_SEL_REG = ATTR[`NOC_NIDB__REG_VC0_ARPROT_SEL];
  REG_VC0_SMID_SEL_REG = ATTR[`NOC_NIDB__REG_VC0_SMID_SEL];
  REG_VC1_AWPROT_SEL_REG = ATTR[`NOC_NIDB__REG_VC1_AWPROT_SEL];
  REG_VC1_SMID_SEL_REG = ATTR[`NOC_NIDB__REG_VC1_SMID_SEL];
  REG_VC4_ARPROT_SEL_REG = ATTR[`NOC_NIDB__REG_VC4_ARPROT_SEL];
  REG_VC4_SMID_SEL_REG = ATTR[`NOC_NIDB__REG_VC4_SMID_SEL];
  REG_VC5_AWPROT_SEL_REG = ATTR[`NOC_NIDB__REG_VC5_AWPROT_SEL];
  REG_VC5_SMID_SEL_REG = ATTR[`NOC_NIDB__REG_VC5_SMID_SEL];
end

// procedures to override, read attribute values

task write_attr;
  input  [`NOC_NIDB_ADDR_SZ-1:0] addr;
  input  [`NOC_NIDB_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`NOC_NIDB_DATA_SZ-1:0] read_attr;
  input  [`NOC_NIDB_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
