`include "B_RFADCE5_defines.vh"

reg [`RFADCE5_DATA_SZ-1:0] ATTR [0:`RFADCE5_ADDR_N-1];
reg [`RFADCE5__OPT_ANALOG_SZ-1:0] OPT_ANALOG_REG = OPT_ANALOG;
reg [`RFADCE5__SIM_DEVICE_SZ:1] SIM_DEVICE_REG = SIM_DEVICE;
reg [`RFADCE5__XPA_ACTIVE_DUTYCYCLE_SZ-1:0] XPA_ACTIVE_DUTYCYCLE_REG = XPA_ACTIVE_DUTYCYCLE;
reg [`RFADCE5__XPA_CHANNELIZER_ENABLE_SZ-1:0] XPA_CHANNELIZER_ENABLE_REG = XPA_CHANNELIZER_ENABLE;
reg [`RFADCE5__XPA_CHANNELS_PER_TILE_SZ-1:0] XPA_CHANNELS_PER_TILE_REG = XPA_CHANNELS_PER_TILE;
reg [`RFADCE5__XPA_CLOCK_SOURCE_SZ-1:0] XPA_CLOCK_SOURCE_REG = XPA_CLOCK_SOURCE;
reg [`RFADCE5__XPA_DATAPATH_MODE_SZ-1:0] XPA_DATAPATH_MODE_REG = XPA_DATAPATH_MODE;
reg [`RFADCE5__XPA_DECIMATION_SZ-1:0] XPA_DECIMATION_REG = XPA_DECIMATION;
reg [`RFADCE5__XPA_MIXING_SZ-1:0] XPA_MIXING_REG = XPA_MIXING;
reg [`RFADCE5__XPA_NUMBER_OF_DDC_SZ-1:0] XPA_NUMBER_OF_DDC_REG = XPA_NUMBER_OF_DDC;
reg XPA_PFIR_CHANNELIZER_LOCATION_REG = XPA_PFIR_CHANNELIZER_LOCATION;
reg [`RFADCE5__XPA_PFIR_TAPS_SZ-1:0] XPA_PFIR_TAPS_REG = XPA_PFIR_TAPS;
reg [`RFADCE5__XPA_QMC_TAPS_SZ-1:0] XPA_QMC_TAPS_REG = XPA_QMC_TAPS;
reg [`RFADCE5__XPA_SAMPLE_RATE_SZ-1:0] XPA_SAMPLE_RATE_REG = XPA_SAMPLE_RATE;
reg [`RFADCE5__XPA_SPARE_SZ-1:0] XPA_SPARE_REG = XPA_SPARE;

initial begin
  ATTR[`RFADCE5__OPT_ANALOG] = OPT_ANALOG;
  ATTR[`RFADCE5__SIM_DEVICE] = SIM_DEVICE;
  ATTR[`RFADCE5__XPA_ACTIVE_DUTYCYCLE] = XPA_ACTIVE_DUTYCYCLE;
  ATTR[`RFADCE5__XPA_CHANNELIZER_ENABLE] = XPA_CHANNELIZER_ENABLE;
  ATTR[`RFADCE5__XPA_CHANNELS_PER_TILE] = XPA_CHANNELS_PER_TILE;
  ATTR[`RFADCE5__XPA_CLOCK_SOURCE] = XPA_CLOCK_SOURCE;
  ATTR[`RFADCE5__XPA_DATAPATH_MODE] = XPA_DATAPATH_MODE;
  ATTR[`RFADCE5__XPA_DECIMATION] = XPA_DECIMATION;
  ATTR[`RFADCE5__XPA_MIXING] = XPA_MIXING;
  ATTR[`RFADCE5__XPA_NUMBER_OF_DDC] = XPA_NUMBER_OF_DDC;
  ATTR[`RFADCE5__XPA_PFIR_CHANNELIZER_LOCATION] = XPA_PFIR_CHANNELIZER_LOCATION;
  ATTR[`RFADCE5__XPA_PFIR_TAPS] = XPA_PFIR_TAPS;
  ATTR[`RFADCE5__XPA_QMC_TAPS] = XPA_QMC_TAPS;
  ATTR[`RFADCE5__XPA_SAMPLE_RATE] = XPA_SAMPLE_RATE;
  ATTR[`RFADCE5__XPA_SPARE] = XPA_SPARE;
end

always @(trig_attr) begin
  OPT_ANALOG_REG = ATTR[`RFADCE5__OPT_ANALOG];
  SIM_DEVICE_REG = ATTR[`RFADCE5__SIM_DEVICE];
  XPA_ACTIVE_DUTYCYCLE_REG = ATTR[`RFADCE5__XPA_ACTIVE_DUTYCYCLE];
  XPA_CHANNELIZER_ENABLE_REG = ATTR[`RFADCE5__XPA_CHANNELIZER_ENABLE];
  XPA_CHANNELS_PER_TILE_REG = ATTR[`RFADCE5__XPA_CHANNELS_PER_TILE];
  XPA_CLOCK_SOURCE_REG = ATTR[`RFADCE5__XPA_CLOCK_SOURCE];
  XPA_DATAPATH_MODE_REG = ATTR[`RFADCE5__XPA_DATAPATH_MODE];
  XPA_DECIMATION_REG = ATTR[`RFADCE5__XPA_DECIMATION];
  XPA_MIXING_REG = ATTR[`RFADCE5__XPA_MIXING];
  XPA_NUMBER_OF_DDC_REG = ATTR[`RFADCE5__XPA_NUMBER_OF_DDC];
  XPA_PFIR_CHANNELIZER_LOCATION_REG = ATTR[`RFADCE5__XPA_PFIR_CHANNELIZER_LOCATION];
  XPA_PFIR_TAPS_REG = ATTR[`RFADCE5__XPA_PFIR_TAPS];
  XPA_QMC_TAPS_REG = ATTR[`RFADCE5__XPA_QMC_TAPS];
  XPA_SAMPLE_RATE_REG = ATTR[`RFADCE5__XPA_SAMPLE_RATE];
  XPA_SPARE_REG = ATTR[`RFADCE5__XPA_SPARE];
end

// procedures to override, read attribute values

task write_attr;
  input  [`RFADCE5_ADDR_SZ-1:0] addr;
  input  [`RFADCE5_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`RFADCE5_DATA_SZ-1:0] read_attr;
  input  [`RFADCE5_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
