`include "B_RFDACE5_defines.vh"

reg [`RFDACE5_DATA_SZ-1:0] ATTR [0:`RFDACE5_ADDR_N-1];
reg [`RFDACE5__MEMORY_INIT_FILE_SZ:1] MEMORY_INIT_FILE_REG = MEMORY_INIT_FILE;
reg [`RFDACE5__SIM_DEVICE_SZ:1] SIM_DEVICE_REG = SIM_DEVICE;
reg [`RFDACE5__XPA_ACTIVE_DUTYCYCLE_SZ-1:0] XPA_ACTIVE_DUTYCYCLE_REG = XPA_ACTIVE_DUTYCYCLE;
reg [`RFDACE5__XPA_CHANNELIZER_ENABLE_SZ-1:0] XPA_CHANNELIZER_ENABLE_REG = XPA_CHANNELIZER_ENABLE;
reg [`RFDACE5__XPA_CHANNELS_PER_TILE_SZ-1:0] XPA_CHANNELS_PER_TILE_REG = XPA_CHANNELS_PER_TILE;
reg [`RFDACE5__XPA_CLOCK_SOURCE_SZ-1:0] XPA_CLOCK_SOURCE_REG = XPA_CLOCK_SOURCE;
reg [`RFDACE5__XPA_DATAPATH_MODE_SZ-1:0] XPA_DATAPATH_MODE_REG = XPA_DATAPATH_MODE;
reg [`RFDACE5__XPA_INTERPOLATION_SZ-1:0] XPA_INTERPOLATION_REG = XPA_INTERPOLATION;
reg [`RFDACE5__XPA_MIXING_SZ-1:0] XPA_MIXING_REG = XPA_MIXING;
reg [`RFDACE5__XPA_NUMBER_OF_DUC_SZ-1:0] XPA_NUMBER_OF_DUC_REG = XPA_NUMBER_OF_DUC;
reg XPA_PFIR_CHANNELIZER_LOCATION_REG = XPA_PFIR_CHANNELIZER_LOCATION;
reg [`RFDACE5__XPA_PFIR_TAPS_SZ-1:0] XPA_PFIR_TAPS_REG = XPA_PFIR_TAPS;
reg [`RFDACE5__XPA_QMC_TAPS_SZ-1:0] XPA_QMC_TAPS_REG = XPA_QMC_TAPS;
reg [`RFDACE5__XPA_SAMPLE_RATE_SZ-1:0] XPA_SAMPLE_RATE_REG = XPA_SAMPLE_RATE;
reg [`RFDACE5__XPA_SPARE_SZ-1:0] XPA_SPARE_REG = XPA_SPARE;

initial begin
  ATTR[`RFDACE5__MEMORY_INIT_FILE] = MEMORY_INIT_FILE;
  ATTR[`RFDACE5__SIM_DEVICE] = SIM_DEVICE;
  ATTR[`RFDACE5__XPA_ACTIVE_DUTYCYCLE] = XPA_ACTIVE_DUTYCYCLE;
  ATTR[`RFDACE5__XPA_CHANNELIZER_ENABLE] = XPA_CHANNELIZER_ENABLE;
  ATTR[`RFDACE5__XPA_CHANNELS_PER_TILE] = XPA_CHANNELS_PER_TILE;
  ATTR[`RFDACE5__XPA_CLOCK_SOURCE] = XPA_CLOCK_SOURCE;
  ATTR[`RFDACE5__XPA_DATAPATH_MODE] = XPA_DATAPATH_MODE;
  ATTR[`RFDACE5__XPA_INTERPOLATION] = XPA_INTERPOLATION;
  ATTR[`RFDACE5__XPA_MIXING] = XPA_MIXING;
  ATTR[`RFDACE5__XPA_NUMBER_OF_DUC] = XPA_NUMBER_OF_DUC;
  ATTR[`RFDACE5__XPA_PFIR_CHANNELIZER_LOCATION] = XPA_PFIR_CHANNELIZER_LOCATION;
  ATTR[`RFDACE5__XPA_PFIR_TAPS] = XPA_PFIR_TAPS;
  ATTR[`RFDACE5__XPA_QMC_TAPS] = XPA_QMC_TAPS;
  ATTR[`RFDACE5__XPA_SAMPLE_RATE] = XPA_SAMPLE_RATE;
  ATTR[`RFDACE5__XPA_SPARE] = XPA_SPARE;
end

always @(trig_attr) begin
  MEMORY_INIT_FILE_REG = ATTR[`RFDACE5__MEMORY_INIT_FILE];
  SIM_DEVICE_REG = ATTR[`RFDACE5__SIM_DEVICE];
  XPA_ACTIVE_DUTYCYCLE_REG = ATTR[`RFDACE5__XPA_ACTIVE_DUTYCYCLE];
  XPA_CHANNELIZER_ENABLE_REG = ATTR[`RFDACE5__XPA_CHANNELIZER_ENABLE];
  XPA_CHANNELS_PER_TILE_REG = ATTR[`RFDACE5__XPA_CHANNELS_PER_TILE];
  XPA_CLOCK_SOURCE_REG = ATTR[`RFDACE5__XPA_CLOCK_SOURCE];
  XPA_DATAPATH_MODE_REG = ATTR[`RFDACE5__XPA_DATAPATH_MODE];
  XPA_INTERPOLATION_REG = ATTR[`RFDACE5__XPA_INTERPOLATION];
  XPA_MIXING_REG = ATTR[`RFDACE5__XPA_MIXING];
  XPA_NUMBER_OF_DUC_REG = ATTR[`RFDACE5__XPA_NUMBER_OF_DUC];
  XPA_PFIR_CHANNELIZER_LOCATION_REG = ATTR[`RFDACE5__XPA_PFIR_CHANNELIZER_LOCATION];
  XPA_PFIR_TAPS_REG = ATTR[`RFDACE5__XPA_PFIR_TAPS];
  XPA_QMC_TAPS_REG = ATTR[`RFDACE5__XPA_QMC_TAPS];
  XPA_SAMPLE_RATE_REG = ATTR[`RFDACE5__XPA_SAMPLE_RATE];
  XPA_SPARE_REG = ATTR[`RFDACE5__XPA_SPARE];
end

// procedures to override, read attribute values

task write_attr;
  input  [`RFDACE5_ADDR_SZ-1:0] addr;
  input  [`RFDACE5_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`RFDACE5_DATA_SZ-1:0] read_attr;
  input  [`RFDACE5_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
