`include "B_SYSMONE5_SAT_TEST_defines.vh"

reg [`SYSMONE5_SAT_TEST_DATA_SZ-1:0] ATTR [0:`SYSMONE5_SAT_TEST_ADDR_N-1];
reg [31:0] INIT_ATTR_0_REG = INIT_ATTR_0;
reg [31:0] INIT_ATTR_1_REG = INIT_ATTR_1;
reg [31:0] INIT_ATTR_10_REG = INIT_ATTR_10;
reg [31:0] INIT_ATTR_11_REG = INIT_ATTR_11;
reg [31:0] INIT_ATTR_12_REG = INIT_ATTR_12;
reg [31:0] INIT_ATTR_13_REG = INIT_ATTR_13;
reg [31:0] INIT_ATTR_14_REG = INIT_ATTR_14;
reg [31:0] INIT_ATTR_15_REG = INIT_ATTR_15;
reg [31:0] INIT_ATTR_16_REG = INIT_ATTR_16;
reg [31:0] INIT_ATTR_17_REG = INIT_ATTR_17;
reg [31:0] INIT_ATTR_18_REG = INIT_ATTR_18;
reg [31:0] INIT_ATTR_19_REG = INIT_ATTR_19;
reg [31:0] INIT_ATTR_1A_REG = INIT_ATTR_1A;
reg [31:0] INIT_ATTR_1B_REG = INIT_ATTR_1B;
reg [31:0] INIT_ATTR_1C_REG = INIT_ATTR_1C;
reg [31:0] INIT_ATTR_1D_REG = INIT_ATTR_1D;
reg [31:0] INIT_ATTR_1E_REG = INIT_ATTR_1E;
reg [31:0] INIT_ATTR_1F_REG = INIT_ATTR_1F;
reg [31:0] INIT_ATTR_2_REG = INIT_ATTR_2;
reg [31:0] INIT_ATTR_20_REG = INIT_ATTR_20;
reg [31:0] INIT_ATTR_21_REG = INIT_ATTR_21;
reg [31:0] INIT_ATTR_22_REG = INIT_ATTR_22;
reg [31:0] INIT_ATTR_23_REG = INIT_ATTR_23;
reg [31:0] INIT_ATTR_24_REG = INIT_ATTR_24;
reg [31:0] INIT_ATTR_25_REG = INIT_ATTR_25;
reg [31:0] INIT_ATTR_26_REG = INIT_ATTR_26;
reg [31:0] INIT_ATTR_27_REG = INIT_ATTR_27;
reg [31:0] INIT_ATTR_28_REG = INIT_ATTR_28;
reg [31:0] INIT_ATTR_29_REG = INIT_ATTR_29;
reg [31:0] INIT_ATTR_2A_REG = INIT_ATTR_2A;
reg [31:0] INIT_ATTR_2B_REG = INIT_ATTR_2B;
reg [31:0] INIT_ATTR_2C_REG = INIT_ATTR_2C;
reg [31:0] INIT_ATTR_2D_REG = INIT_ATTR_2D;
reg [31:0] INIT_ATTR_2E_REG = INIT_ATTR_2E;
reg [31:0] INIT_ATTR_2F_REG = INIT_ATTR_2F;
reg [31:0] INIT_ATTR_3_REG = INIT_ATTR_3;
reg [31:0] INIT_ATTR_30_REG = INIT_ATTR_30;
reg [31:0] INIT_ATTR_31_REG = INIT_ATTR_31;
reg [31:0] INIT_ATTR_32_REG = INIT_ATTR_32;
reg [31:0] INIT_ATTR_33_REG = INIT_ATTR_33;
reg [31:0] INIT_ATTR_34_REG = INIT_ATTR_34;
reg [31:0] INIT_ATTR_35_REG = INIT_ATTR_35;
reg [31:0] INIT_ATTR_36_REG = INIT_ATTR_36;
reg [31:0] INIT_ATTR_37_REG = INIT_ATTR_37;
reg [31:0] INIT_ATTR_38_REG = INIT_ATTR_38;
reg [31:0] INIT_ATTR_39_REG = INIT_ATTR_39;
reg [31:0] INIT_ATTR_3A_REG = INIT_ATTR_3A;
reg [31:0] INIT_ATTR_3B_REG = INIT_ATTR_3B;
reg [31:0] INIT_ATTR_3C_REG = INIT_ATTR_3C;
reg [31:0] INIT_ATTR_3D_REG = INIT_ATTR_3D;
reg [31:0] INIT_ATTR_3E_REG = INIT_ATTR_3E;
reg [31:0] INIT_ATTR_3F_REG = INIT_ATTR_3F;
reg [31:0] INIT_ATTR_4_REG = INIT_ATTR_4;
reg [31:0] INIT_ATTR_5_REG = INIT_ATTR_5;
reg [31:0] INIT_ATTR_6_REG = INIT_ATTR_6;
reg [31:0] INIT_ATTR_7_REG = INIT_ATTR_7;
reg [31:0] INIT_ATTR_8_REG = INIT_ATTR_8;
reg [31:0] INIT_ATTR_9_REG = INIT_ATTR_9;
reg [31:0] INIT_ATTR_A_REG = INIT_ATTR_A;
reg [31:0] INIT_ATTR_B_REG = INIT_ATTR_B;
reg [31:0] INIT_ATTR_C_REG = INIT_ATTR_C;
reg [31:0] INIT_ATTR_D_REG = INIT_ATTR_D;
reg [31:0] INIT_ATTR_E_REG = INIT_ATTR_E;
reg [31:0] INIT_ATTR_F_REG = INIT_ATTR_F;

initial begin
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_0] = INIT_ATTR_0;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_10] = INIT_ATTR_10;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_11] = INIT_ATTR_11;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_12] = INIT_ATTR_12;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_13] = INIT_ATTR_13;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_14] = INIT_ATTR_14;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_15] = INIT_ATTR_15;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_16] = INIT_ATTR_16;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_17] = INIT_ATTR_17;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_18] = INIT_ATTR_18;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_19] = INIT_ATTR_19;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1A] = INIT_ATTR_1A;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1B] = INIT_ATTR_1B;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1C] = INIT_ATTR_1C;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1D] = INIT_ATTR_1D;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1E] = INIT_ATTR_1E;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1F] = INIT_ATTR_1F;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1] = INIT_ATTR_1;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_20] = INIT_ATTR_20;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_21] = INIT_ATTR_21;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_22] = INIT_ATTR_22;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_23] = INIT_ATTR_23;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_24] = INIT_ATTR_24;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_25] = INIT_ATTR_25;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_26] = INIT_ATTR_26;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_27] = INIT_ATTR_27;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_28] = INIT_ATTR_28;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_29] = INIT_ATTR_29;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2A] = INIT_ATTR_2A;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2B] = INIT_ATTR_2B;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2C] = INIT_ATTR_2C;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2D] = INIT_ATTR_2D;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2E] = INIT_ATTR_2E;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2F] = INIT_ATTR_2F;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2] = INIT_ATTR_2;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_30] = INIT_ATTR_30;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_31] = INIT_ATTR_31;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_32] = INIT_ATTR_32;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_33] = INIT_ATTR_33;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_34] = INIT_ATTR_34;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_35] = INIT_ATTR_35;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_36] = INIT_ATTR_36;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_37] = INIT_ATTR_37;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_38] = INIT_ATTR_38;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_39] = INIT_ATTR_39;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3A] = INIT_ATTR_3A;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3B] = INIT_ATTR_3B;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3C] = INIT_ATTR_3C;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3D] = INIT_ATTR_3D;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3E] = INIT_ATTR_3E;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3F] = INIT_ATTR_3F;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3] = INIT_ATTR_3;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_4] = INIT_ATTR_4;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_5] = INIT_ATTR_5;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_6] = INIT_ATTR_6;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_7] = INIT_ATTR_7;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_8] = INIT_ATTR_8;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_9] = INIT_ATTR_9;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_A] = INIT_ATTR_A;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_B] = INIT_ATTR_B;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_C] = INIT_ATTR_C;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_D] = INIT_ATTR_D;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_E] = INIT_ATTR_E;
  ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_F] = INIT_ATTR_F;
end

always @(trig_attr) begin
  INIT_ATTR_0_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_0];
  INIT_ATTR_10_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_10];
  INIT_ATTR_11_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_11];
  INIT_ATTR_12_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_12];
  INIT_ATTR_13_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_13];
  INIT_ATTR_14_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_14];
  INIT_ATTR_15_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_15];
  INIT_ATTR_16_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_16];
  INIT_ATTR_17_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_17];
  INIT_ATTR_18_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_18];
  INIT_ATTR_19_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_19];
  INIT_ATTR_1A_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1A];
  INIT_ATTR_1B_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1B];
  INIT_ATTR_1C_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1C];
  INIT_ATTR_1D_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1D];
  INIT_ATTR_1E_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1E];
  INIT_ATTR_1F_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1F];
  INIT_ATTR_1_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_1];
  INIT_ATTR_20_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_20];
  INIT_ATTR_21_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_21];
  INIT_ATTR_22_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_22];
  INIT_ATTR_23_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_23];
  INIT_ATTR_24_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_24];
  INIT_ATTR_25_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_25];
  INIT_ATTR_26_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_26];
  INIT_ATTR_27_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_27];
  INIT_ATTR_28_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_28];
  INIT_ATTR_29_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_29];
  INIT_ATTR_2A_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2A];
  INIT_ATTR_2B_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2B];
  INIT_ATTR_2C_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2C];
  INIT_ATTR_2D_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2D];
  INIT_ATTR_2E_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2E];
  INIT_ATTR_2F_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2F];
  INIT_ATTR_2_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_2];
  INIT_ATTR_30_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_30];
  INIT_ATTR_31_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_31];
  INIT_ATTR_32_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_32];
  INIT_ATTR_33_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_33];
  INIT_ATTR_34_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_34];
  INIT_ATTR_35_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_35];
  INIT_ATTR_36_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_36];
  INIT_ATTR_37_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_37];
  INIT_ATTR_38_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_38];
  INIT_ATTR_39_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_39];
  INIT_ATTR_3A_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3A];
  INIT_ATTR_3B_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3B];
  INIT_ATTR_3C_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3C];
  INIT_ATTR_3D_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3D];
  INIT_ATTR_3E_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3E];
  INIT_ATTR_3F_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3F];
  INIT_ATTR_3_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_3];
  INIT_ATTR_4_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_4];
  INIT_ATTR_5_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_5];
  INIT_ATTR_6_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_6];
  INIT_ATTR_7_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_7];
  INIT_ATTR_8_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_8];
  INIT_ATTR_9_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_9];
  INIT_ATTR_A_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_A];
  INIT_ATTR_B_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_B];
  INIT_ATTR_C_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_C];
  INIT_ATTR_D_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_D];
  INIT_ATTR_E_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_E];
  INIT_ATTR_F_REG = ATTR[`SYSMONE5_SAT_TEST__INIT_ATTR_F];
end

// procedures to override, read attribute values

task write_attr;
  input  [`SYSMONE5_SAT_TEST_ADDR_SZ-1:0] addr;
  input  [`SYSMONE5_SAT_TEST_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`SYSMONE5_SAT_TEST_DATA_SZ-1:0] read_attr;
  input  [`SYSMONE5_SAT_TEST_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
