`include "B_URAM288_TEST_defines.vh"

reg [`URAM288_TEST_DATA_SZ-1:0] ATTR [0:`URAM288_TEST_ADDR_N-1];
reg [3:0] AUTO_SLEEP_LATENCY_REG = AUTO_SLEEP_LATENCY;
reg [16:0] AVG_CONS_INACTIVE_CYCLES_REG = AVG_CONS_INACTIVE_CYCLES;
reg [144:1] BWE_MODE_A_REG = BWE_MODE_A;
reg [144:1] BWE_MODE_B_REG = BWE_MODE_B;
reg [48:1] CASCADE_ORDER_A_REG = CASCADE_ORDER_A;
reg [48:1] CASCADE_ORDER_B_REG = CASCADE_ORDER_B;
reg [40:1] CAS_CLEAR16_REG = CAS_CLEAR16;
reg [40:1] EN_AUTO_SLEEP_MODE_REG = EN_AUTO_SLEEP_MODE;
reg [40:1] EN_ECC_RD_A_REG = EN_ECC_RD_A;
reg [40:1] EN_ECC_RD_B_REG = EN_ECC_RD_B;
reg [40:1] EN_ECC_WR_A_REG = EN_ECC_WR_A;
reg [40:1] EN_ECC_WR_B_REG = EN_ECC_WR_B;
reg [24:1] EN_PWRGATE_REG = EN_PWRGATE;
reg [40:1] IREG_PRE_A_REG = IREG_PRE_A;
reg [40:1] IREG_PRE_B_REG = IREG_PRE_B;
reg IS_CLK_INVERTED_REG = IS_CLK_INVERTED;
reg IS_EN_A_INVERTED_REG = IS_EN_A_INVERTED;
reg IS_EN_B_INVERTED_REG = IS_EN_B_INVERTED;
reg IS_RDB_WR_A_INVERTED_REG = IS_RDB_WR_A_INVERTED;
reg IS_RDB_WR_B_INVERTED_REG = IS_RDB_WR_B_INVERTED;
reg IS_RST_A_INVERTED_REG = IS_RST_A_INVERTED;
reg IS_RST_B_INVERTED_REG = IS_RST_B_INVERTED;
reg [32:1] MATRIX_ID_REG = MATRIX_ID;
reg [11:0] NUM_UNIQUE_SELF_ADDR_A_REG = NUM_UNIQUE_SELF_ADDR_A;
reg [11:0] NUM_UNIQUE_SELF_ADDR_B_REG = NUM_UNIQUE_SELF_ADDR_B;
reg [11:0] NUM_URAM_IN_MATRIX_REG = NUM_URAM_IN_MATRIX;
reg [40:1] OREG_A_REG = OREG_A;
reg [40:1] OREG_B_REG = OREG_B;
reg [40:1] OREG_ECC_A_REG = OREG_ECC_A;
reg [40:1] OREG_ECC_B_REG = OREG_ECC_B;
reg [40:1] REG_CAS_A_REG = REG_CAS_A;
reg [40:1] REG_CAS_B_REG = REG_CAS_B;
reg [40:1] RST_MODE_A_REG = RST_MODE_A;
reg [40:1] RST_MODE_B_REG = RST_MODE_B;
reg [10:0] SELF_ADDR_A_REG = SELF_ADDR_A;
reg [10:0] SELF_ADDR_B_REG = SELF_ADDR_B;
reg [10:0] SELF_MASK_A_REG = SELF_MASK_A;
reg [10:0] SELF_MASK_B_REG = SELF_MASK_B;
reg [40:1] TRM_CAS_CLEAR16_REG = TRM_CAS_CLEAR16;
reg [2:0] TRM_TST_CKP2HSEL_REG = TRM_TST_CKP2HSEL;
reg [1:0] TRM_TST_CKP2SEL_REG = TRM_TST_CKP2SEL;
reg [40:1] TRM_TST_DIS_CLEAR_REG = TRM_TST_DIS_CLEAR;
reg [3:0] TRM_TST_DSLPSEL_REG = TRM_TST_DSLPSEL;
reg [5:0] TRM_TST_FADIOL_REG = TRM_TST_FADIOL;
reg [5:0] TRM_TST_FADIOR_REG = TRM_TST_FADIOR;
reg [40:1] TRM_TST_REDENIOL_REG = TRM_TST_REDENIOL;
reg [40:1] TRM_TST_REDENIOR_REG = TRM_TST_REDENIOR;
reg [2:0] TRM_TST_RTSEL_REG = TRM_TST_RTSEL;
reg [1:0] TRM_TST_SAPW_OPT_REG = TRM_TST_SAPW_OPT;
reg [48:1] TRM_TST_TM_REG = TRM_TST_TM;
reg [2:0] TRM_TST_WTSEL_REG = TRM_TST_WTSEL;
reg [2:0] TST_CKP2HSEL_REG = TST_CKP2HSEL;
reg [2:0] TST_CKP2SEL_REG = TST_CKP2SEL;
reg [40:1] TST_DIS_CLEAR_REG = TST_DIS_CLEAR;
reg [3:0] TST_DSLPSEL_REG = TST_DSLPSEL;
reg [40:1] TST_RING_EN_REG = TST_RING_EN;
reg [2:0] TST_RTSEL_REG = TST_RTSEL;
reg [1:0] TST_SAPW_OPT_REG = TST_SAPW_OPT;
reg [48:1] TST_TM_REG = TST_TM;
reg [2:0] TST_WTSEL_REG = TST_WTSEL;
reg [40:1] USE_EXT_CE_A_REG = USE_EXT_CE_A;
reg [40:1] USE_EXT_CE_B_REG = USE_EXT_CE_B;

initial begin
  ATTR[`URAM288_TEST__AUTO_SLEEP_LATENCY] = AUTO_SLEEP_LATENCY;
  ATTR[`URAM288_TEST__AVG_CONS_INACTIVE_CYCLES] = AVG_CONS_INACTIVE_CYCLES;
  ATTR[`URAM288_TEST__BWE_MODE_A] = BWE_MODE_A;
  ATTR[`URAM288_TEST__BWE_MODE_B] = BWE_MODE_B;
  ATTR[`URAM288_TEST__CASCADE_ORDER_A] = CASCADE_ORDER_A;
  ATTR[`URAM288_TEST__CASCADE_ORDER_B] = CASCADE_ORDER_B;
  ATTR[`URAM288_TEST__CAS_CLEAR16] = CAS_CLEAR16;
  ATTR[`URAM288_TEST__EN_AUTO_SLEEP_MODE] = EN_AUTO_SLEEP_MODE;
  ATTR[`URAM288_TEST__EN_ECC_RD_A] = EN_ECC_RD_A;
  ATTR[`URAM288_TEST__EN_ECC_RD_B] = EN_ECC_RD_B;
  ATTR[`URAM288_TEST__EN_ECC_WR_A] = EN_ECC_WR_A;
  ATTR[`URAM288_TEST__EN_ECC_WR_B] = EN_ECC_WR_B;
  ATTR[`URAM288_TEST__EN_PWRGATE] = EN_PWRGATE;
  ATTR[`URAM288_TEST__IREG_PRE_A] = IREG_PRE_A;
  ATTR[`URAM288_TEST__IREG_PRE_B] = IREG_PRE_B;
  ATTR[`URAM288_TEST__IS_CLK_INVERTED] = IS_CLK_INVERTED;
  ATTR[`URAM288_TEST__IS_EN_A_INVERTED] = IS_EN_A_INVERTED;
  ATTR[`URAM288_TEST__IS_EN_B_INVERTED] = IS_EN_B_INVERTED;
  ATTR[`URAM288_TEST__IS_RDB_WR_A_INVERTED] = IS_RDB_WR_A_INVERTED;
  ATTR[`URAM288_TEST__IS_RDB_WR_B_INVERTED] = IS_RDB_WR_B_INVERTED;
  ATTR[`URAM288_TEST__IS_RST_A_INVERTED] = IS_RST_A_INVERTED;
  ATTR[`URAM288_TEST__IS_RST_B_INVERTED] = IS_RST_B_INVERTED;
  ATTR[`URAM288_TEST__MATRIX_ID] = MATRIX_ID;
  ATTR[`URAM288_TEST__NUM_UNIQUE_SELF_ADDR_A] = NUM_UNIQUE_SELF_ADDR_A;
  ATTR[`URAM288_TEST__NUM_UNIQUE_SELF_ADDR_B] = NUM_UNIQUE_SELF_ADDR_B;
  ATTR[`URAM288_TEST__NUM_URAM_IN_MATRIX] = NUM_URAM_IN_MATRIX;
  ATTR[`URAM288_TEST__OREG_A] = OREG_A;
  ATTR[`URAM288_TEST__OREG_B] = OREG_B;
  ATTR[`URAM288_TEST__OREG_ECC_A] = OREG_ECC_A;
  ATTR[`URAM288_TEST__OREG_ECC_B] = OREG_ECC_B;
  ATTR[`URAM288_TEST__REG_CAS_A] = REG_CAS_A;
  ATTR[`URAM288_TEST__REG_CAS_B] = REG_CAS_B;
  ATTR[`URAM288_TEST__RST_MODE_A] = RST_MODE_A;
  ATTR[`URAM288_TEST__RST_MODE_B] = RST_MODE_B;
  ATTR[`URAM288_TEST__SELF_ADDR_A] = SELF_ADDR_A;
  ATTR[`URAM288_TEST__SELF_ADDR_B] = SELF_ADDR_B;
  ATTR[`URAM288_TEST__SELF_MASK_A] = SELF_MASK_A;
  ATTR[`URAM288_TEST__SELF_MASK_B] = SELF_MASK_B;
  ATTR[`URAM288_TEST__TRM_CAS_CLEAR16] = TRM_CAS_CLEAR16;
  ATTR[`URAM288_TEST__TRM_TST_CKP2HSEL] = TRM_TST_CKP2HSEL;
  ATTR[`URAM288_TEST__TRM_TST_CKP2SEL] = TRM_TST_CKP2SEL;
  ATTR[`URAM288_TEST__TRM_TST_DIS_CLEAR] = TRM_TST_DIS_CLEAR;
  ATTR[`URAM288_TEST__TRM_TST_DSLPSEL] = TRM_TST_DSLPSEL;
  ATTR[`URAM288_TEST__TRM_TST_FADIOL] = TRM_TST_FADIOL;
  ATTR[`URAM288_TEST__TRM_TST_FADIOR] = TRM_TST_FADIOR;
  ATTR[`URAM288_TEST__TRM_TST_REDENIOL] = TRM_TST_REDENIOL;
  ATTR[`URAM288_TEST__TRM_TST_REDENIOR] = TRM_TST_REDENIOR;
  ATTR[`URAM288_TEST__TRM_TST_RTSEL] = TRM_TST_RTSEL;
  ATTR[`URAM288_TEST__TRM_TST_SAPW_OPT] = TRM_TST_SAPW_OPT;
  ATTR[`URAM288_TEST__TRM_TST_TM] = TRM_TST_TM;
  ATTR[`URAM288_TEST__TRM_TST_WTSEL] = TRM_TST_WTSEL;
  ATTR[`URAM288_TEST__TST_CKP2HSEL] = TST_CKP2HSEL;
  ATTR[`URAM288_TEST__TST_CKP2SEL] = TST_CKP2SEL;
  ATTR[`URAM288_TEST__TST_DIS_CLEAR] = TST_DIS_CLEAR;
  ATTR[`URAM288_TEST__TST_DSLPSEL] = TST_DSLPSEL;
  ATTR[`URAM288_TEST__TST_RING_EN] = TST_RING_EN;
  ATTR[`URAM288_TEST__TST_RTSEL] = TST_RTSEL;
  ATTR[`URAM288_TEST__TST_SAPW_OPT] = TST_SAPW_OPT;
  ATTR[`URAM288_TEST__TST_TM] = TST_TM;
  ATTR[`URAM288_TEST__TST_WTSEL] = TST_WTSEL;
  ATTR[`URAM288_TEST__USE_EXT_CE_A] = USE_EXT_CE_A;
  ATTR[`URAM288_TEST__USE_EXT_CE_B] = USE_EXT_CE_B;
end

always @(trig_attr) begin
  AUTO_SLEEP_LATENCY_REG = ATTR[`URAM288_TEST__AUTO_SLEEP_LATENCY];
  AVG_CONS_INACTIVE_CYCLES_REG = ATTR[`URAM288_TEST__AVG_CONS_INACTIVE_CYCLES];
  BWE_MODE_A_REG = ATTR[`URAM288_TEST__BWE_MODE_A];
  BWE_MODE_B_REG = ATTR[`URAM288_TEST__BWE_MODE_B];
  CASCADE_ORDER_A_REG = ATTR[`URAM288_TEST__CASCADE_ORDER_A];
  CASCADE_ORDER_B_REG = ATTR[`URAM288_TEST__CASCADE_ORDER_B];
  CAS_CLEAR16_REG = ATTR[`URAM288_TEST__CAS_CLEAR16];
  EN_AUTO_SLEEP_MODE_REG = ATTR[`URAM288_TEST__EN_AUTO_SLEEP_MODE];
  EN_ECC_RD_A_REG = ATTR[`URAM288_TEST__EN_ECC_RD_A];
  EN_ECC_RD_B_REG = ATTR[`URAM288_TEST__EN_ECC_RD_B];
  EN_ECC_WR_A_REG = ATTR[`URAM288_TEST__EN_ECC_WR_A];
  EN_ECC_WR_B_REG = ATTR[`URAM288_TEST__EN_ECC_WR_B];
  EN_PWRGATE_REG = ATTR[`URAM288_TEST__EN_PWRGATE];
  IREG_PRE_A_REG = ATTR[`URAM288_TEST__IREG_PRE_A];
  IREG_PRE_B_REG = ATTR[`URAM288_TEST__IREG_PRE_B];
  IS_CLK_INVERTED_REG = ATTR[`URAM288_TEST__IS_CLK_INVERTED];
  IS_EN_A_INVERTED_REG = ATTR[`URAM288_TEST__IS_EN_A_INVERTED];
  IS_EN_B_INVERTED_REG = ATTR[`URAM288_TEST__IS_EN_B_INVERTED];
  IS_RDB_WR_A_INVERTED_REG = ATTR[`URAM288_TEST__IS_RDB_WR_A_INVERTED];
  IS_RDB_WR_B_INVERTED_REG = ATTR[`URAM288_TEST__IS_RDB_WR_B_INVERTED];
  IS_RST_A_INVERTED_REG = ATTR[`URAM288_TEST__IS_RST_A_INVERTED];
  IS_RST_B_INVERTED_REG = ATTR[`URAM288_TEST__IS_RST_B_INVERTED];
  MATRIX_ID_REG = ATTR[`URAM288_TEST__MATRIX_ID];
  NUM_UNIQUE_SELF_ADDR_A_REG = ATTR[`URAM288_TEST__NUM_UNIQUE_SELF_ADDR_A];
  NUM_UNIQUE_SELF_ADDR_B_REG = ATTR[`URAM288_TEST__NUM_UNIQUE_SELF_ADDR_B];
  NUM_URAM_IN_MATRIX_REG = ATTR[`URAM288_TEST__NUM_URAM_IN_MATRIX];
  OREG_A_REG = ATTR[`URAM288_TEST__OREG_A];
  OREG_B_REG = ATTR[`URAM288_TEST__OREG_B];
  OREG_ECC_A_REG = ATTR[`URAM288_TEST__OREG_ECC_A];
  OREG_ECC_B_REG = ATTR[`URAM288_TEST__OREG_ECC_B];
  REG_CAS_A_REG = ATTR[`URAM288_TEST__REG_CAS_A];
  REG_CAS_B_REG = ATTR[`URAM288_TEST__REG_CAS_B];
  RST_MODE_A_REG = ATTR[`URAM288_TEST__RST_MODE_A];
  RST_MODE_B_REG = ATTR[`URAM288_TEST__RST_MODE_B];
  SELF_ADDR_A_REG = ATTR[`URAM288_TEST__SELF_ADDR_A];
  SELF_ADDR_B_REG = ATTR[`URAM288_TEST__SELF_ADDR_B];
  SELF_MASK_A_REG = ATTR[`URAM288_TEST__SELF_MASK_A];
  SELF_MASK_B_REG = ATTR[`URAM288_TEST__SELF_MASK_B];
  TRM_CAS_CLEAR16_REG = ATTR[`URAM288_TEST__TRM_CAS_CLEAR16];
  TRM_TST_CKP2HSEL_REG = ATTR[`URAM288_TEST__TRM_TST_CKP2HSEL];
  TRM_TST_CKP2SEL_REG = ATTR[`URAM288_TEST__TRM_TST_CKP2SEL];
  TRM_TST_DIS_CLEAR_REG = ATTR[`URAM288_TEST__TRM_TST_DIS_CLEAR];
  TRM_TST_DSLPSEL_REG = ATTR[`URAM288_TEST__TRM_TST_DSLPSEL];
  TRM_TST_FADIOL_REG = ATTR[`URAM288_TEST__TRM_TST_FADIOL];
  TRM_TST_FADIOR_REG = ATTR[`URAM288_TEST__TRM_TST_FADIOR];
  TRM_TST_REDENIOL_REG = ATTR[`URAM288_TEST__TRM_TST_REDENIOL];
  TRM_TST_REDENIOR_REG = ATTR[`URAM288_TEST__TRM_TST_REDENIOR];
  TRM_TST_RTSEL_REG = ATTR[`URAM288_TEST__TRM_TST_RTSEL];
  TRM_TST_SAPW_OPT_REG = ATTR[`URAM288_TEST__TRM_TST_SAPW_OPT];
  TRM_TST_TM_REG = ATTR[`URAM288_TEST__TRM_TST_TM];
  TRM_TST_WTSEL_REG = ATTR[`URAM288_TEST__TRM_TST_WTSEL];
  TST_CKP2HSEL_REG = ATTR[`URAM288_TEST__TST_CKP2HSEL];
  TST_CKP2SEL_REG = ATTR[`URAM288_TEST__TST_CKP2SEL];
  TST_DIS_CLEAR_REG = ATTR[`URAM288_TEST__TST_DIS_CLEAR];
  TST_DSLPSEL_REG = ATTR[`URAM288_TEST__TST_DSLPSEL];
  TST_RING_EN_REG = ATTR[`URAM288_TEST__TST_RING_EN];
  TST_RTSEL_REG = ATTR[`URAM288_TEST__TST_RTSEL];
  TST_SAPW_OPT_REG = ATTR[`URAM288_TEST__TST_SAPW_OPT];
  TST_TM_REG = ATTR[`URAM288_TEST__TST_TM];
  TST_WTSEL_REG = ATTR[`URAM288_TEST__TST_WTSEL];
  USE_EXT_CE_A_REG = ATTR[`URAM288_TEST__USE_EXT_CE_A];
  USE_EXT_CE_B_REG = ATTR[`URAM288_TEST__USE_EXT_CE_B];
end

// procedures to override, read attribute values

task write_attr;
  input  [`URAM288_TEST_ADDR_SZ-1:0] addr;
  input  [`URAM288_TEST_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`URAM288_TEST_DATA_SZ-1:0] read_attr;
  input  [`URAM288_TEST_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
