`include "B_VCU_defines.vh"

reg [`VCU_DATA_SZ-1:0] ATTR [0:`VCU_ADDR_N-1];
reg [31:0] CORECLKREQ_REG = CORECLKREQ;
reg [31:0] DECHORRESOLUTION_REG = DECHORRESOLUTION;
reg [40:1] DECODERCHROMAFORMAT_REG = DECODERCHROMAFORMAT;
reg [40:1] DECODERCODING_REG = DECODERCODING;
reg [31:0] DECODERCOLORDEPTH_REG = DECODERCOLORDEPTH;
reg [31:0] DECODERNUMCORES_REG = DECODERNUMCORES;
reg [31:0] DECVERTRESOLUTION_REG = DECVERTRESOLUTION;
reg [40:1] ENABLEDECODER_REG = ENABLEDECODER;
reg [40:1] ENABLEENCODER_REG = ENABLEENCODER;
reg [31:0] ENCHORRESOLUTION_REG = ENCHORRESOLUTION;
reg [40:1] ENCODERCHROMAFORMAT_REG = ENCODERCHROMAFORMAT;
reg [40:1] ENCODERCODING_REG = ENCODERCODING;
reg [31:0] ENCODERCOLORDEPTH_REG = ENCODERCOLORDEPTH;
reg [31:0] ENCODERNUMCORES_REG = ENCODERNUMCORES;
reg [31:0] ENCVERTRESOLUTION_REG = ENCVERTRESOLUTION;

initial begin
  ATTR[`VCU__CORECLKREQ] = CORECLKREQ;
  ATTR[`VCU__DECHORRESOLUTION] = DECHORRESOLUTION;
  ATTR[`VCU__DECODERCHROMAFORMAT] = DECODERCHROMAFORMAT;
  ATTR[`VCU__DECODERCODING] = DECODERCODING;
  ATTR[`VCU__DECODERCOLORDEPTH] = DECODERCOLORDEPTH;
  ATTR[`VCU__DECODERNUMCORES] = DECODERNUMCORES;
  ATTR[`VCU__DECVERTRESOLUTION] = DECVERTRESOLUTION;
  ATTR[`VCU__ENABLEDECODER] = ENABLEDECODER;
  ATTR[`VCU__ENABLEENCODER] = ENABLEENCODER;
  ATTR[`VCU__ENCHORRESOLUTION] = ENCHORRESOLUTION;
  ATTR[`VCU__ENCODERCHROMAFORMAT] = ENCODERCHROMAFORMAT;
  ATTR[`VCU__ENCODERCODING] = ENCODERCODING;
  ATTR[`VCU__ENCODERCOLORDEPTH] = ENCODERCOLORDEPTH;
  ATTR[`VCU__ENCODERNUMCORES] = ENCODERNUMCORES;
  ATTR[`VCU__ENCVERTRESOLUTION] = ENCVERTRESOLUTION;
end

always @(trig_attr) begin
  CORECLKREQ_REG = ATTR[`VCU__CORECLKREQ];
  DECHORRESOLUTION_REG = ATTR[`VCU__DECHORRESOLUTION];
  DECODERCHROMAFORMAT_REG = ATTR[`VCU__DECODERCHROMAFORMAT];
  DECODERCODING_REG = ATTR[`VCU__DECODERCODING];
  DECODERCOLORDEPTH_REG = ATTR[`VCU__DECODERCOLORDEPTH];
  DECODERNUMCORES_REG = ATTR[`VCU__DECODERNUMCORES];
  DECVERTRESOLUTION_REG = ATTR[`VCU__DECVERTRESOLUTION];
  ENABLEDECODER_REG = ATTR[`VCU__ENABLEDECODER];
  ENABLEENCODER_REG = ATTR[`VCU__ENABLEENCODER];
  ENCHORRESOLUTION_REG = ATTR[`VCU__ENCHORRESOLUTION];
  ENCODERCHROMAFORMAT_REG = ATTR[`VCU__ENCODERCHROMAFORMAT];
  ENCODERCODING_REG = ATTR[`VCU__ENCODERCODING];
  ENCODERCOLORDEPTH_REG = ATTR[`VCU__ENCODERCOLORDEPTH];
  ENCODERNUMCORES_REG = ATTR[`VCU__ENCODERNUMCORES];
  ENCVERTRESOLUTION_REG = ATTR[`VCU__ENCVERTRESOLUTION];
end

// procedures to override, read attribute values

task write_attr;
  input  [`VCU_ADDR_SZ-1:0] addr;
  input  [`VCU_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`VCU_DATA_SZ-1:0] read_attr;
  input  [`VCU_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
