`include "B_X5PHIO_CMU_X32_defines.vh"

reg [`X5PHIO_CMU_X32_DATA_SZ-1:0] ATTR [0:`X5PHIO_CMU_X32_ADDR_N-1];
reg [`X5PHIO_CMU_X32__ANATERM_NVAL_SZ-1:0] ANATERM_NVAL_REG = ANATERM_NVAL;
reg [`X5PHIO_CMU_X32__ANATERM_PVAL_SZ-1:0] ANATERM_PVAL_REG = ANATERM_PVAL;
reg [`X5PHIO_CMU_X32__ANATERM_SEL_SZ:1] ANATERM_SEL_REG = ANATERM_SEL;
reg [`X5PHIO_CMU_X32__ATBMUX_SEL_SZ-1:0] ATBMUX_SEL_REG = ATBMUX_SEL;
reg [`X5PHIO_CMU_X32__ATB_PATH_SEL_SZ:1] ATB_PATH_SEL_REG = ATB_PATH_SEL;
reg [`X5PHIO_CMU_X32__BYP_FREQ_DIV_S2P_CMU_SZ:1] BYP_FREQ_DIV_S2P_CMU_REG = BYP_FREQ_DIV_S2P_CMU;
reg [`X5PHIO_CMU_X32__BYP_FREQ_DIV_X5PLL_SZ:1] BYP_FREQ_DIV_X5PLL_REG = BYP_FREQ_DIV_X5PLL;
reg [`X5PHIO_CMU_X32__CALTX_RCAL_EN_SZ:1] CALTX_RCAL_EN_REG = CALTX_RCAL_EN;
reg [`X5PHIO_CMU_X32__CALTX_RCAL_VAL_SZ-1:0] CALTX_RCAL_VAL_REG = CALTX_RCAL_VAL;
reg [`X5PHIO_CMU_X32__CMU_ADLY_BIAS_SZ-1:0] CMU_ADLY_BIAS_REG = CMU_ADLY_BIAS;
reg [`X5PHIO_CMU_X32__CMU_APB_CLK_SEL_SZ:1] CMU_APB_CLK_SEL_REG = CMU_APB_CLK_SEL;
reg [`X5PHIO_CMU_X32__CMU_CTLE_BIAS_SZ-1:0] CMU_CTLE_BIAS_REG = CMU_CTLE_BIAS;
reg [`X5PHIO_CMU_X32__CMU_D2C_BIAS_SZ-1:0] CMU_D2C_BIAS_REG = CMU_D2C_BIAS;
reg [`X5PHIO_CMU_X32__CMU_DFE_BIAS_SZ-1:0] CMU_DFE_BIAS_REG = CMU_DFE_BIAS;
reg [`X5PHIO_CMU_X32__CMU_LPRXBIAS_SEL_SZ-1:0] CMU_LPRXBIAS_SEL_REG = CMU_LPRXBIAS_SEL;
reg [`X5PHIO_CMU_X32__CMU_NPI_CLK_SEL_SZ:1] CMU_NPI_CLK_SEL_REG = CMU_NPI_CLK_SEL;
reg [`X5PHIO_CMU_X32__CMU_RXBIAS_SPARE_SZ-1:0] CMU_RXBIAS_SPARE_REG = CMU_RXBIAS_SPARE;
reg [`X5PHIO_CMU_X32__CMU_SRCH_ALGORITHM_SZ:1] CMU_SRCH_ALGORITHM_REG = CMU_SRCH_ALGORITHM;
reg [`X5PHIO_CMU_X32__CMU_TXBIAS_SEL_SZ-1:0] CMU_TXBIAS_SEL_REG = CMU_TXBIAS_SEL;
reg [`X5PHIO_CMU_X32__CMU_VREF_BIAS_SZ-1:0] CMU_VREF_BIAS_REG = CMU_VREF_BIAS;
reg [`X5PHIO_CMU_X32__DCI2LTCH_NCODE_SZ-1:0] DCI2LTCH_NCODE_REG = DCI2LTCH_NCODE;
reg [`X5PHIO_CMU_X32__DCI2LTCH_PCODE_SZ-1:0] DCI2LTCH_PCODE_REG = DCI2LTCH_PCODE;
reg [`X5PHIO_CMU_X32__DCIUPDATEMODE_SZ:1] DCIUPDATEMODE_REG = DCIUPDATEMODE;
reg [`X5PHIO_CMU_X32__DCI_CASCADE_SEL_SZ-1:0] DCI_CASCADE_SEL_REG = DCI_CASCADE_SEL;
reg [`X5PHIO_CMU_X32__DCI_CONFIG_SZ:1] DCI_CONFIG_REG = DCI_CONFIG;
reg [`X5PHIO_CMU_X32__DCI_DEBUG_SEL_SZ-1:0] DCI_DEBUG_SEL_REG = DCI_DEBUG_SEL;
reg [`X5PHIO_CMU_X32__DCI_FLTR_CTRL_SZ-1:0] DCI_FLTR_CTRL_REG = DCI_FLTR_CTRL;
reg [`X5PHIO_CMU_X32__DCI_ITER_SEL_SZ:1] DCI_ITER_SEL_REG = DCI_ITER_SEL;
reg [`X5PHIO_CMU_X32__DCI_LOCK_DIR_SZ:1] DCI_LOCK_DIR_REG = DCI_LOCK_DIR;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_N0_SZ-1:0] DCI_SCL_CTRL_N0_REG = DCI_SCL_CTRL_N0;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_N1_SZ-1:0] DCI_SCL_CTRL_N1_REG = DCI_SCL_CTRL_N1;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_N2_SZ-1:0] DCI_SCL_CTRL_N2_REG = DCI_SCL_CTRL_N2;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_N3_SZ-1:0] DCI_SCL_CTRL_N3_REG = DCI_SCL_CTRL_N3;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_N4_SZ-1:0] DCI_SCL_CTRL_N4_REG = DCI_SCL_CTRL_N4;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_P0_SZ-1:0] DCI_SCL_CTRL_P0_REG = DCI_SCL_CTRL_P0;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_P1_SZ-1:0] DCI_SCL_CTRL_P1_REG = DCI_SCL_CTRL_P1;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_P2_SZ-1:0] DCI_SCL_CTRL_P2_REG = DCI_SCL_CTRL_P2;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_P3_SZ-1:0] DCI_SCL_CTRL_P3_REG = DCI_SCL_CTRL_P3;
reg [`X5PHIO_CMU_X32__DCI_SCL_CTRL_P4_SZ-1:0] DCI_SCL_CTRL_P4_REG = DCI_SCL_CTRL_P4;
reg [`X5PHIO_CMU_X32__DCI_TYPE_SZ-1:0] DCI_TYPE_REG = DCI_TYPE;
reg [`X5PHIO_CMU_X32__DEBUG_CALTX_RCAL_EN_SZ:1] DEBUG_CALTX_RCAL_EN_REG = DEBUG_CALTX_RCAL_EN;
reg [`X5PHIO_CMU_X32__DEBUG_CALTX_RCAL_VAL_SZ-1:0] DEBUG_CALTX_RCAL_VAL_REG = DEBUG_CALTX_RCAL_VAL;
reg [`X5PHIO_CMU_X32__DEBUG_DCI_LOCK_DIR_SZ:1] DEBUG_DCI_LOCK_DIR_REG = DEBUG_DCI_LOCK_DIR;
reg [`X5PHIO_CMU_X32__DEBUG_RCAL_M_OVERRIDE_SZ:1] DEBUG_RCAL_M_OVERRIDE_REG = DEBUG_RCAL_M_OVERRIDE;
reg [`X5PHIO_CMU_X32__DEBUG_VREF_APB_SEL_SZ:1] DEBUG_VREF_APB_SEL_REG = DEBUG_VREF_APB_SEL;
reg [`X5PHIO_CMU_X32__DEBUG_VREF_MONITOR_SZ:1] DEBUG_VREF_MONITOR_REG = DEBUG_VREF_MONITOR;
reg [`X5PHIO_CMU_X32__EN_DCI_SZ:1] EN_DCI_REG = EN_DCI;
reg [`X5PHIO_CMU_X32__EN_OUT_FLTR_SZ:1] EN_OUT_FLTR_REG = EN_OUT_FLTR;
reg [`X5PHIO_CMU_X32__RCAL_BUS_SZ-1:0] RCAL_BUS_REG = RCAL_BUS;
reg [`X5PHIO_CMU_X32__RCAL_ITER_SEL_SZ:1] RCAL_ITER_SEL_REG = RCAL_ITER_SEL;
reg [`X5PHIO_CMU_X32__RCAL_MODE_SZ:1] RCAL_MODE_REG = RCAL_MODE;
reg [`X5PHIO_CMU_X32__RCAL_M_OVERRIDE_SZ:1] RCAL_M_OVERRIDE_REG = RCAL_M_OVERRIDE;
reg [`X5PHIO_CMU_X32__RCAL_SCALE_SZ-1:0] RCAL_SCALE_REG = RCAL_SCALE;
reg [`X5PHIO_CMU_X32__TST_EN_SZ:1] TST_EN_REG = TST_EN;
reg [`X5PHIO_CMU_X32__VREF_0P3_CODE_SZ-1:0] VREF_0P3_CODE_REG = VREF_0P3_CODE;
reg [`X5PHIO_CMU_X32__VREF_0P5_CODE_SZ-1:0] VREF_0P5_CODE_REG = VREF_0P5_CODE;
reg [`X5PHIO_CMU_X32__VREF_0P75_CODE_SZ-1:0] VREF_0P75_CODE_REG = VREF_0P75_CODE;
reg [`X5PHIO_CMU_X32__VREF_12P5_CODE_SZ-1:0] VREF_12P5_CODE_REG = VREF_12P5_CODE;
reg [`X5PHIO_CMU_X32__VREF_16P7_CODE_SZ-1:0] VREF_16P7_CODE_REG = VREF_16P7_CODE;
reg [`X5PHIO_CMU_X32__VREF_MONITOR_SZ:1] VREF_MONITOR_REG = VREF_MONITOR;
reg [`X5PHIO_CMU_X32__WAIT_BYPASS_SZ:1] WAIT_BYPASS_REG = WAIT_BYPASS;

initial begin
  ATTR[`X5PHIO_CMU_X32__ANATERM_NVAL] = ANATERM_NVAL;
  ATTR[`X5PHIO_CMU_X32__ANATERM_PVAL] = ANATERM_PVAL;
  ATTR[`X5PHIO_CMU_X32__ANATERM_SEL] = ANATERM_SEL;
  ATTR[`X5PHIO_CMU_X32__ATBMUX_SEL] = ATBMUX_SEL;
  ATTR[`X5PHIO_CMU_X32__ATB_PATH_SEL] = ATB_PATH_SEL;
  ATTR[`X5PHIO_CMU_X32__BYP_FREQ_DIV_S2P_CMU] = BYP_FREQ_DIV_S2P_CMU;
  ATTR[`X5PHIO_CMU_X32__BYP_FREQ_DIV_X5PLL] = BYP_FREQ_DIV_X5PLL;
  ATTR[`X5PHIO_CMU_X32__CALTX_RCAL_EN] = CALTX_RCAL_EN;
  ATTR[`X5PHIO_CMU_X32__CALTX_RCAL_VAL] = CALTX_RCAL_VAL;
  ATTR[`X5PHIO_CMU_X32__CMU_ADLY_BIAS] = CMU_ADLY_BIAS;
  ATTR[`X5PHIO_CMU_X32__CMU_APB_CLK_SEL] = CMU_APB_CLK_SEL;
  ATTR[`X5PHIO_CMU_X32__CMU_CTLE_BIAS] = CMU_CTLE_BIAS;
  ATTR[`X5PHIO_CMU_X32__CMU_D2C_BIAS] = CMU_D2C_BIAS;
  ATTR[`X5PHIO_CMU_X32__CMU_DFE_BIAS] = CMU_DFE_BIAS;
  ATTR[`X5PHIO_CMU_X32__CMU_LPRXBIAS_SEL] = CMU_LPRXBIAS_SEL;
  ATTR[`X5PHIO_CMU_X32__CMU_NPI_CLK_SEL] = CMU_NPI_CLK_SEL;
  ATTR[`X5PHIO_CMU_X32__CMU_RXBIAS_SPARE] = CMU_RXBIAS_SPARE;
  ATTR[`X5PHIO_CMU_X32__CMU_SRCH_ALGORITHM] = CMU_SRCH_ALGORITHM;
  ATTR[`X5PHIO_CMU_X32__CMU_TXBIAS_SEL] = CMU_TXBIAS_SEL;
  ATTR[`X5PHIO_CMU_X32__CMU_VREF_BIAS] = CMU_VREF_BIAS;
  ATTR[`X5PHIO_CMU_X32__DCI2LTCH_NCODE] = DCI2LTCH_NCODE;
  ATTR[`X5PHIO_CMU_X32__DCI2LTCH_PCODE] = DCI2LTCH_PCODE;
  ATTR[`X5PHIO_CMU_X32__DCIUPDATEMODE] = DCIUPDATEMODE;
  ATTR[`X5PHIO_CMU_X32__DCI_CASCADE_SEL] = DCI_CASCADE_SEL;
  ATTR[`X5PHIO_CMU_X32__DCI_CONFIG] = DCI_CONFIG;
  ATTR[`X5PHIO_CMU_X32__DCI_DEBUG_SEL] = DCI_DEBUG_SEL;
  ATTR[`X5PHIO_CMU_X32__DCI_FLTR_CTRL] = DCI_FLTR_CTRL;
  ATTR[`X5PHIO_CMU_X32__DCI_ITER_SEL] = DCI_ITER_SEL;
  ATTR[`X5PHIO_CMU_X32__DCI_LOCK_DIR] = DCI_LOCK_DIR;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N0] = DCI_SCL_CTRL_N0;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N1] = DCI_SCL_CTRL_N1;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N2] = DCI_SCL_CTRL_N2;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N3] = DCI_SCL_CTRL_N3;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N4] = DCI_SCL_CTRL_N4;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P0] = DCI_SCL_CTRL_P0;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P1] = DCI_SCL_CTRL_P1;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P2] = DCI_SCL_CTRL_P2;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P3] = DCI_SCL_CTRL_P3;
  ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P4] = DCI_SCL_CTRL_P4;
  ATTR[`X5PHIO_CMU_X32__DCI_TYPE] = DCI_TYPE;
  ATTR[`X5PHIO_CMU_X32__DEBUG_CALTX_RCAL_EN] = DEBUG_CALTX_RCAL_EN;
  ATTR[`X5PHIO_CMU_X32__DEBUG_CALTX_RCAL_VAL] = DEBUG_CALTX_RCAL_VAL;
  ATTR[`X5PHIO_CMU_X32__DEBUG_DCI_LOCK_DIR] = DEBUG_DCI_LOCK_DIR;
  ATTR[`X5PHIO_CMU_X32__DEBUG_RCAL_M_OVERRIDE] = DEBUG_RCAL_M_OVERRIDE;
  ATTR[`X5PHIO_CMU_X32__DEBUG_VREF_APB_SEL] = DEBUG_VREF_APB_SEL;
  ATTR[`X5PHIO_CMU_X32__DEBUG_VREF_MONITOR] = DEBUG_VREF_MONITOR;
  ATTR[`X5PHIO_CMU_X32__EN_DCI] = EN_DCI;
  ATTR[`X5PHIO_CMU_X32__EN_OUT_FLTR] = EN_OUT_FLTR;
  ATTR[`X5PHIO_CMU_X32__RCAL_BUS] = RCAL_BUS;
  ATTR[`X5PHIO_CMU_X32__RCAL_ITER_SEL] = RCAL_ITER_SEL;
  ATTR[`X5PHIO_CMU_X32__RCAL_MODE] = RCAL_MODE;
  ATTR[`X5PHIO_CMU_X32__RCAL_M_OVERRIDE] = RCAL_M_OVERRIDE;
  ATTR[`X5PHIO_CMU_X32__RCAL_SCALE] = RCAL_SCALE;
  ATTR[`X5PHIO_CMU_X32__TST_EN] = TST_EN;
  ATTR[`X5PHIO_CMU_X32__VREF_0P3_CODE] = VREF_0P3_CODE;
  ATTR[`X5PHIO_CMU_X32__VREF_0P5_CODE] = VREF_0P5_CODE;
  ATTR[`X5PHIO_CMU_X32__VREF_0P75_CODE] = VREF_0P75_CODE;
  ATTR[`X5PHIO_CMU_X32__VREF_12P5_CODE] = VREF_12P5_CODE;
  ATTR[`X5PHIO_CMU_X32__VREF_16P7_CODE] = VREF_16P7_CODE;
  ATTR[`X5PHIO_CMU_X32__VREF_MONITOR] = VREF_MONITOR;
  ATTR[`X5PHIO_CMU_X32__WAIT_BYPASS] = WAIT_BYPASS;
end

always @(trig_attr) begin
  ANATERM_NVAL_REG = ATTR[`X5PHIO_CMU_X32__ANATERM_NVAL];
  ANATERM_PVAL_REG = ATTR[`X5PHIO_CMU_X32__ANATERM_PVAL];
  ANATERM_SEL_REG = ATTR[`X5PHIO_CMU_X32__ANATERM_SEL];
  ATBMUX_SEL_REG = ATTR[`X5PHIO_CMU_X32__ATBMUX_SEL];
  ATB_PATH_SEL_REG = ATTR[`X5PHIO_CMU_X32__ATB_PATH_SEL];
  BYP_FREQ_DIV_S2P_CMU_REG = ATTR[`X5PHIO_CMU_X32__BYP_FREQ_DIV_S2P_CMU];
  BYP_FREQ_DIV_X5PLL_REG = ATTR[`X5PHIO_CMU_X32__BYP_FREQ_DIV_X5PLL];
  CALTX_RCAL_EN_REG = ATTR[`X5PHIO_CMU_X32__CALTX_RCAL_EN];
  CALTX_RCAL_VAL_REG = ATTR[`X5PHIO_CMU_X32__CALTX_RCAL_VAL];
  CMU_ADLY_BIAS_REG = ATTR[`X5PHIO_CMU_X32__CMU_ADLY_BIAS];
  CMU_APB_CLK_SEL_REG = ATTR[`X5PHIO_CMU_X32__CMU_APB_CLK_SEL];
  CMU_CTLE_BIAS_REG = ATTR[`X5PHIO_CMU_X32__CMU_CTLE_BIAS];
  CMU_D2C_BIAS_REG = ATTR[`X5PHIO_CMU_X32__CMU_D2C_BIAS];
  CMU_DFE_BIAS_REG = ATTR[`X5PHIO_CMU_X32__CMU_DFE_BIAS];
  CMU_LPRXBIAS_SEL_REG = ATTR[`X5PHIO_CMU_X32__CMU_LPRXBIAS_SEL];
  CMU_NPI_CLK_SEL_REG = ATTR[`X5PHIO_CMU_X32__CMU_NPI_CLK_SEL];
  CMU_RXBIAS_SPARE_REG = ATTR[`X5PHIO_CMU_X32__CMU_RXBIAS_SPARE];
  CMU_SRCH_ALGORITHM_REG = ATTR[`X5PHIO_CMU_X32__CMU_SRCH_ALGORITHM];
  CMU_TXBIAS_SEL_REG = ATTR[`X5PHIO_CMU_X32__CMU_TXBIAS_SEL];
  CMU_VREF_BIAS_REG = ATTR[`X5PHIO_CMU_X32__CMU_VREF_BIAS];
  DCI2LTCH_NCODE_REG = ATTR[`X5PHIO_CMU_X32__DCI2LTCH_NCODE];
  DCI2LTCH_PCODE_REG = ATTR[`X5PHIO_CMU_X32__DCI2LTCH_PCODE];
  DCIUPDATEMODE_REG = ATTR[`X5PHIO_CMU_X32__DCIUPDATEMODE];
  DCI_CASCADE_SEL_REG = ATTR[`X5PHIO_CMU_X32__DCI_CASCADE_SEL];
  DCI_CONFIG_REG = ATTR[`X5PHIO_CMU_X32__DCI_CONFIG];
  DCI_DEBUG_SEL_REG = ATTR[`X5PHIO_CMU_X32__DCI_DEBUG_SEL];
  DCI_FLTR_CTRL_REG = ATTR[`X5PHIO_CMU_X32__DCI_FLTR_CTRL];
  DCI_ITER_SEL_REG = ATTR[`X5PHIO_CMU_X32__DCI_ITER_SEL];
  DCI_LOCK_DIR_REG = ATTR[`X5PHIO_CMU_X32__DCI_LOCK_DIR];
  DCI_SCL_CTRL_N0_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N0];
  DCI_SCL_CTRL_N1_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N1];
  DCI_SCL_CTRL_N2_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N2];
  DCI_SCL_CTRL_N3_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N3];
  DCI_SCL_CTRL_N4_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_N4];
  DCI_SCL_CTRL_P0_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P0];
  DCI_SCL_CTRL_P1_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P1];
  DCI_SCL_CTRL_P2_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P2];
  DCI_SCL_CTRL_P3_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P3];
  DCI_SCL_CTRL_P4_REG = ATTR[`X5PHIO_CMU_X32__DCI_SCL_CTRL_P4];
  DCI_TYPE_REG = ATTR[`X5PHIO_CMU_X32__DCI_TYPE];
  DEBUG_CALTX_RCAL_EN_REG = ATTR[`X5PHIO_CMU_X32__DEBUG_CALTX_RCAL_EN];
  DEBUG_CALTX_RCAL_VAL_REG = ATTR[`X5PHIO_CMU_X32__DEBUG_CALTX_RCAL_VAL];
  DEBUG_DCI_LOCK_DIR_REG = ATTR[`X5PHIO_CMU_X32__DEBUG_DCI_LOCK_DIR];
  DEBUG_RCAL_M_OVERRIDE_REG = ATTR[`X5PHIO_CMU_X32__DEBUG_RCAL_M_OVERRIDE];
  DEBUG_VREF_APB_SEL_REG = ATTR[`X5PHIO_CMU_X32__DEBUG_VREF_APB_SEL];
  DEBUG_VREF_MONITOR_REG = ATTR[`X5PHIO_CMU_X32__DEBUG_VREF_MONITOR];
  EN_DCI_REG = ATTR[`X5PHIO_CMU_X32__EN_DCI];
  EN_OUT_FLTR_REG = ATTR[`X5PHIO_CMU_X32__EN_OUT_FLTR];
  RCAL_BUS_REG = ATTR[`X5PHIO_CMU_X32__RCAL_BUS];
  RCAL_ITER_SEL_REG = ATTR[`X5PHIO_CMU_X32__RCAL_ITER_SEL];
  RCAL_MODE_REG = ATTR[`X5PHIO_CMU_X32__RCAL_MODE];
  RCAL_M_OVERRIDE_REG = ATTR[`X5PHIO_CMU_X32__RCAL_M_OVERRIDE];
  RCAL_SCALE_REG = ATTR[`X5PHIO_CMU_X32__RCAL_SCALE];
  TST_EN_REG = ATTR[`X5PHIO_CMU_X32__TST_EN];
  VREF_0P3_CODE_REG = ATTR[`X5PHIO_CMU_X32__VREF_0P3_CODE];
  VREF_0P5_CODE_REG = ATTR[`X5PHIO_CMU_X32__VREF_0P5_CODE];
  VREF_0P75_CODE_REG = ATTR[`X5PHIO_CMU_X32__VREF_0P75_CODE];
  VREF_12P5_CODE_REG = ATTR[`X5PHIO_CMU_X32__VREF_12P5_CODE];
  VREF_16P7_CODE_REG = ATTR[`X5PHIO_CMU_X32__VREF_16P7_CODE];
  VREF_MONITOR_REG = ATTR[`X5PHIO_CMU_X32__VREF_MONITOR];
  WAIT_BYPASS_REG = ATTR[`X5PHIO_CMU_X32__WAIT_BYPASS];
end

// procedures to override, read attribute values

task write_attr;
  input  [`X5PHIO_CMU_X32_ADDR_SZ-1:0] addr;
  input  [`X5PHIO_CMU_X32_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`X5PHIO_CMU_X32_DATA_SZ-1:0] read_attr;
  input  [`X5PHIO_CMU_X32_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
