`include "B_XPIO_ZMATCH_BLK_defines.vh"

reg [`XPIO_ZMATCH_BLK_DATA_SZ-1:0] ATTR [0:`XPIO_ZMATCH_BLK_ADDR_N-1];
reg [`XPIO_ZMATCH_BLK__CASCADE_SZ:1] CASCADE_REG = CASCADE;
reg [`XPIO_ZMATCH_BLK__DCIUPDATEMODE_SZ:1] DCIUPDATEMODE_REG = DCIUPDATEMODE;
reg [`XPIO_ZMATCH_BLK__DCI_CASCADE_SEL_SZ-1:0] DCI_CASCADE_SEL_REG = DCI_CASCADE_SEL;
reg [`XPIO_ZMATCH_BLK__DCI_CONFIG_SZ:1] DCI_CONFIG_REG = DCI_CONFIG;
reg [`XPIO_ZMATCH_BLK__DCI_CSSD_CTRL_SZ-1:0] DCI_CSSD_CTRL_REG = DCI_CSSD_CTRL;
reg [`XPIO_ZMATCH_BLK__DCI_DEBUG_SEL_SZ-1:0] DCI_DEBUG_SEL_REG = DCI_DEBUG_SEL;
reg [`XPIO_ZMATCH_BLK__DCI_DEBUG_SEL_ADV_SZ-1:0] DCI_DEBUG_SEL_ADV_REG = DCI_DEBUG_SEL_ADV;
reg [`XPIO_ZMATCH_BLK__DCI_FLTR_CTRL_SZ-1:0] DCI_FLTR_CTRL_REG = DCI_FLTR_CTRL;
reg [`XPIO_ZMATCH_BLK__DCI_REF_OPT_SZ-1:0] DCI_REF_OPT_REG = DCI_REF_OPT;
reg [`XPIO_ZMATCH_BLK__DCI_SCL_CTRL_SZ-1:0] DCI_SCL_CTRL_REG = DCI_SCL_CTRL;
reg [`XPIO_ZMATCH_BLK__EN_DCI_SZ:1] EN_DCI_REG = EN_DCI;
reg [`XPIO_ZMATCH_BLK__EN_OUT_FLTR_SZ:1] EN_OUT_FLTR_REG = EN_OUT_FLTR;
reg [`XPIO_ZMATCH_BLK__TST_EN_SZ:1] TST_EN_REG = TST_EN;
reg [`XPIO_ZMATCH_BLK__UPDATE_CONTROL_SZ-1:0] UPDATE_CONTROL_REG = UPDATE_CONTROL;
reg [`XPIO_ZMATCH_BLK__WAIT_BYPASS_SZ:1] WAIT_BYPASS_REG = WAIT_BYPASS;

initial begin
  ATTR[`XPIO_ZMATCH_BLK__CASCADE] = CASCADE;
  ATTR[`XPIO_ZMATCH_BLK__DCIUPDATEMODE] = DCIUPDATEMODE;
  ATTR[`XPIO_ZMATCH_BLK__DCI_CASCADE_SEL] = DCI_CASCADE_SEL;
  ATTR[`XPIO_ZMATCH_BLK__DCI_CONFIG] = DCI_CONFIG;
  ATTR[`XPIO_ZMATCH_BLK__DCI_CSSD_CTRL] = DCI_CSSD_CTRL;
  ATTR[`XPIO_ZMATCH_BLK__DCI_DEBUG_SEL] = DCI_DEBUG_SEL;
  ATTR[`XPIO_ZMATCH_BLK__DCI_DEBUG_SEL_ADV] = DCI_DEBUG_SEL_ADV;
  ATTR[`XPIO_ZMATCH_BLK__DCI_FLTR_CTRL] = DCI_FLTR_CTRL;
  ATTR[`XPIO_ZMATCH_BLK__DCI_REF_OPT] = DCI_REF_OPT;
  ATTR[`XPIO_ZMATCH_BLK__DCI_SCL_CTRL] = DCI_SCL_CTRL;
  ATTR[`XPIO_ZMATCH_BLK__EN_DCI] = EN_DCI;
  ATTR[`XPIO_ZMATCH_BLK__EN_OUT_FLTR] = EN_OUT_FLTR;
  ATTR[`XPIO_ZMATCH_BLK__TST_EN] = TST_EN;
  ATTR[`XPIO_ZMATCH_BLK__UPDATE_CONTROL] = UPDATE_CONTROL;
  ATTR[`XPIO_ZMATCH_BLK__WAIT_BYPASS] = WAIT_BYPASS;
end

always @(trig_attr) begin
  CASCADE_REG = ATTR[`XPIO_ZMATCH_BLK__CASCADE];
  DCIUPDATEMODE_REG = ATTR[`XPIO_ZMATCH_BLK__DCIUPDATEMODE];
  DCI_CASCADE_SEL_REG = ATTR[`XPIO_ZMATCH_BLK__DCI_CASCADE_SEL];
  DCI_CONFIG_REG = ATTR[`XPIO_ZMATCH_BLK__DCI_CONFIG];
  DCI_CSSD_CTRL_REG = ATTR[`XPIO_ZMATCH_BLK__DCI_CSSD_CTRL];
  DCI_DEBUG_SEL_ADV_REG = ATTR[`XPIO_ZMATCH_BLK__DCI_DEBUG_SEL_ADV];
  DCI_DEBUG_SEL_REG = ATTR[`XPIO_ZMATCH_BLK__DCI_DEBUG_SEL];
  DCI_FLTR_CTRL_REG = ATTR[`XPIO_ZMATCH_BLK__DCI_FLTR_CTRL];
  DCI_REF_OPT_REG = ATTR[`XPIO_ZMATCH_BLK__DCI_REF_OPT];
  DCI_SCL_CTRL_REG = ATTR[`XPIO_ZMATCH_BLK__DCI_SCL_CTRL];
  EN_DCI_REG = ATTR[`XPIO_ZMATCH_BLK__EN_DCI];
  EN_OUT_FLTR_REG = ATTR[`XPIO_ZMATCH_BLK__EN_OUT_FLTR];
  TST_EN_REG = ATTR[`XPIO_ZMATCH_BLK__TST_EN];
  UPDATE_CONTROL_REG = ATTR[`XPIO_ZMATCH_BLK__UPDATE_CONTROL];
  WAIT_BYPASS_REG = ATTR[`XPIO_ZMATCH_BLK__WAIT_BYPASS];
end

// procedures to override, read attribute values

task write_attr;
  input  [`XPIO_ZMATCH_BLK_ADDR_SZ-1:0] addr;
  input  [`XPIO_ZMATCH_BLK_DATA_SZ-1:0] data;
  begin
    ATTR[addr] = data;
    trig_attr = ~trig_attr; // to be removed
  end
endtask

function [`XPIO_ZMATCH_BLK_DATA_SZ-1:0] read_attr;
  input  [`XPIO_ZMATCH_BLK_ADDR_SZ-1:0] addr;
  begin
    read_attr = ATTR[addr];
  end
endfunction

task commit_attr;
  begin
trig_attr = ~trig_attr;
  end
endtask
